### ISSUE TITLE
Demo that “quantitative scales always start at zero” broken

### ISSUE THREAD

**Issue by pierre-haessig** [altair-viz/altair#2201] opened 2020-06-09 10:27 UTC
Hi, 

I just noticed a broken example in the section [Effect of Data Type on Axis Scales](https://altair-viz.github.io/user_guide/encoding.html#effect-of-data-type-on-axis-scales) of the Encoding doc chapter (Altair 4.1.0). There is a pair of charts serving as a demo that “quantitative scales always start at zero unless otherwise specified”. However, in the left panel (title: year=quantitative), the zero value is not in the scale. Perhaps a smart heuristic was recently added in Vega lite, for example remove zero from the scale if the ratio xmin/xmax is "close enough" to 1 (altough I didn't see this mentioned in the doc on  [Continuous Scales](https://vega.github.io/vega-lite/docs/scale.html#continuous-scales))?

The following chart with the customized scale `scale=alt.Scale(zero=False)` appears identical.

Still, it is useful to have this customization example (this is what I was looking for while reading the docs: in the chart I'm working on, zero is indeed included!).

To solve the issue, another dataset may be needed? I made some test with the cars dataset (e.g setting the cylinder, displacement of miles per gallon to ordinal), but the results are not great. Cylinders have not enough values to show how tick labels are simplified with the quantitative type. On the other hand, displacement and MPG have too many unique values making the ordinal scale extremely wide.

Best,
Pierre

**Comment by jakevdp** [comment] 2020-06-09 16:20
Thanks, I think this has been fixed in master, but it's been a while since we pushed a doc build.

**Comment by jakevdp** [comment] 2020-06-09 16:21
The issue is that Vega-Lite changed its behavior between v3 and v4, and some parts of Altair's docs have become stale as a result.

**Comment by joelostblom** [comment] 2022-03-23 00:21
There is now an example of this behavior here https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits

**Closed by joelostblom** 2022-03-23 00:21 UTC
Labels: bug, documentation

**Comment by pierre-haessig** [comment] 2022-04-07 09:08
Thanks!
