### ISSUE TITLE
Ordering does not work when layer 2 charts together

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1371] opened 2019-03-16 06:06 UTC
Behavior
=======
When I only have the base chart, it orders properly, but when I layer the cross-filter highlight chart on it, I cannot find a proper way to keep it in order

You can find my notebook demonstrating the problem here, data included.
https://github.com/noklam/BugDemo/blob/master/data%20challenge.ipynb

Expected Behavior
=========
The highlight part should keep the order.

Current Behavior
----------------
![image](https://user-images.githubusercontent.com/18221871/54471435-c0df5e80-47f3-11e9-845d-968a6831d9b9.png)

Imaginary chart
--------------
![image](https://user-images.githubusercontent.com/18221871/54471363-c8eace80-47f2-11e9-935c-ce87d1c087c4.png)

Comments
------------
Again, I really like the interaction provided by vega, it is very smooth and beautiful. However, I found it is less easy than I thought to combine different components to form a chart. When I start to combine 2 charts / adding aggregation, things start to work in a way unexpected. I found it hard to create charts that are not exist in the current Example Gallery.

Also, I found ordering the chart is a bit verbose and a bit confuse between `sort` and `order`. For example, if I need to create a sorted bar chart according to the Example Gallery.
```python
alt.Chart(source).mark_bar().encode(
    x='sum(yield):Q',
    y=alt.Y(
        'site:N',
        sort=alt.EncodingSortField(
            field="yield",  # The field to use for the sort
            op="sum",  # The operation to run on the field prior to sorting
            order="descending"  # The order to sort in
        )
    )
)
```
Ther sort argument here is quite verbose, for 90% of the time user will simply want to sorted it according to encoding x, is there an easy way passing something like sort='descending'? There is `EncodingSortField` and `SortField` and I am not sure about their difference.

Reference Example Gallery
------------------------------
Cross filter
https://altair-viz.github.io/gallery/interactive_layered_crossfilter.html

Order bar
https://altair-viz.github.io/gallery/bar_chart_sorted.html

**Comment by jakevdp** [comment] 2019-03-16 15:21
Thanks for the report!

This is a known issue: #820 

It has been fixed upstream, but that fix has not yet made it into a release: https://github.com/vega/vega-lite/issues/2177

Closing as a duplicate of #820

**Closed by jakevdp** 2019-03-16 15:21 UTC

**Comment by noklam** [comment] 2019-03-16 17:27
Thanks @jakevdp  for quick response.
`.resolve_scale(x='independent')` 
Good to know there is a workaround from #820, but I probably would never find this solution by myself.  :cry:
