### ISSUE TITLE
Enhance Group Bar Example

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#2113] opened 2020-04-26 06:36 UTC
I am working in a small project that trying to reproduce [BBC R cookbook](https://bbc.github.io/rcookbook/) with `plotnine` and `altair`. I found that the current example of a grouped bar is not what we would normally used. It is not straight forward to tweak it, so I think an example would be helpful.

I would love to see if you have any advice to simplify the syntax as it requires quite a lot of configuration. I would be happy to add it in the current Gallery Example if you think this is useful.

## Current Group Bar example
![image](https://user-images.githubusercontent.com/18221871/80299928-fadaac80-87ca-11ea-8a48-3d0caea9a1c9.png)
## enhance grouped bar 
![image](https://user-images.githubusercontent.com/18221871/80299942-1645b780-87cb-11ea-98fa-facf1f9296a1.png)

# Gist
https://nbviewer.jupyter.org/gist/noklam/2a1bd2d6e37bf954c7c707109f495f2e

# Reference
Work in Progress:
https://mediumnok.ml/python/2020/04/13/Recreating-the-BBC-graphs-in-Python-plotnine-altair.html

**Comment by jakevdp** [comment] 2020-04-26 12:46
I think rather than changing the example (which uses a straightforward approach by design), this would be useful as a section in the [Customizing visualizations](https://altair-viz.github.io/user_guide/customization.html) documentation, with descriptions/links to what features are being used.

**Comment by noklam** [comment] 2020-04-26 14:07
If you think this is useful,  I can try to write an example extending the customization with thus example step by step.

**Comment by jakevdp** [comment] 2020-04-26 14:15
That would be great!

**Comment by joelostblom** [comment] 2023-01-16 19:19
A simpler grouped bar example using the new offset channels has been added to the developer docs so closing this https://joelostblom.github.io/altair-docs/gallery/grouped_bar_chart2.html

**Closed by joelostblom** 2023-01-16 19:19 UTC
Labels: enhancement, documentation
