### ISSUE TITLE
Color / legend overrides order of data

### ISSUE THREAD

**Issue by jasonhof** [altair-viz/altair#2450] opened 2021-04-07 07:38 UTC
Mick encouraged me to file this bug, as I hit it when developing [Assignment 1 for Data Visualization class](https://courses.cs.washington.edu/courses/cse512/21sp/a1.html) using [this dataset](https://observablehq.com/@uwdata/hours-of-sunshine).  He says that it seems like the color scale overrides the order of the data.

First of all, I created a function to transform and add data for use in the visualization:
``` python
def get_cum_val(df, cityname, mon_num, num_mons = 3):
  agg_sum = 0
  for i in range(num_mons):
    ind = i+ mon_num
    if ind > 11:
      ind = ind - 11
  agg_sum = agg_sum + df.loc[(df['city']==cityname) & (df['monthnum']==(ind))]['sunshine'].values[0]
  return agg_sum

def get_col_val(df,agg3mo):
  col = 'gray'
  if agg3mo > 630:
    col = 'plant'
  elif agg3mo > 550:
    col = 'maybe plant'
  elif agg3mo > 400:
    col = 'don\'t plant'
  else:
    col = 'not a chance'
  return col

def agg_mo(df, cityname, num_mons=3):
  df_3mo = df
  df_3mo['sum3mo'] = 0
  num_rows = df_3mo.shape[0]
  print(df_3mo.iloc[1])
  print(df_3mo.shape)
  df_3mo['sum3mo'] = df_3mo.apply(lambda row : get_cum_val(df_3mo,cityname,row['monthnum'],num_mons),axis=1)
  df_3mo['plant?'] = df_3mo.apply(lambda row : get_col_val(df_3mo,row['sum3mo']),axis=1)
  return df_3mo
```

And now, here are two versions of the same code, which don't work well together:

VERSION 1: Working in chronological order with alt.condition for coloring (no legend):
``` python
def create_sun_chart_bar_f1(df, cityname):
 df_3mo = df.copy()
 df_3mo = agg_mo(df_3mo, cityname, 3)
 print(df)
 print(df_3mo)
 print(df_3mo.loc[df_3mo['city']=='Seattle'])
 print(df_3mo.loc[df_3mo['city']=='MIami'])
 yran = [0,1000]
 mons = [11,0,1]
 sun_chart_city_3mo = alt.Chart(df_3mo).mark_bar(
 ).transform_filter(
 (datum.city == cityname) 
 ).encode(
 alt.X('month', sort=alt.EncodingSortField(field='monthnum',order='ascending')),
 alt.Y('sum3mo:Q', title=('Sun Hours'),scale=Scale(domain=yran)),
 # color = (alt.Color('plant?',
 # scale=alt.Scale(domain=['plant', 'maybe plant','don\'t plant','not a chance'], range=['green','yellow', 'pink','brown']),
 # legend=alt.Legend(orient='right'),
 # )),
 color = alt.condition(
  alt.datum.sum3mo > 600,
  alt.value('green'), alt.value('brown')),
 ).properties(
  width=800,
  height=300
 )
 sun_chart_city_pts = alt.Chart(df_3mo, title=cityname).mark_line(color = 'orange').encode(
  alt.X('month', sort=alt.EncodingSortField(field='monthnum',order='ascending')),
  alt.Y('sunshine', title=('Sun Hours')),
 ).transform_filter(
  (datum.city == cityname)
 )
 sun_chart_city = alt.layer(sun_chart_city_3mo, sun_chart_city_pts)
 return sun_chart_city.copy()

sun_chart_sea = create_sun_chart_bar_f1(sun_df,'Seattle')
sun_chart_chi = create_sun_chart_bar_f1(sun_df,'San Francisco')
sun_chart_mia = create_sun_chart_bar_f1(sun_df,'Miami')

alt.vconcat(sun_chart_sea,sun_chart_chi,sun_chart_mia,title=titleQ)
```

VERSION 2: Not working in chronological order after un-commenting alt.Scale for coloring (legend appears):
``` python
def create_sun_chart_bar_f1(df, cityname):
 df_3mo = df.copy()
 df_3mo = agg_mo(df_3mo, cityname, 3)
 yran = [0,1000]
 mons = [11,0,1]
 sun_chart_city_3mo = alt.Chart(df_3mo).mark_bar(
 ).transform_filter(
  (datum.city == cityname) 
 ).encode(
  alt.X('month', sort=alt.EncodingSortField(field='monthnum',order='ascending')),
  alt.Y('sum3mo:Q', title=('Sun Hours'),scale=Scale(domain=yran)),
  color = (alt.Color('plant?',
  scale=alt.Scale(domain=['plant', 'maybe plant','don\'t plant','not a chance'], range=['green','yellow', 'pink','brown']),
  legend=alt.Legend(orient='right'),
 )),
 # color = alt.condition(
 # alt.datum.sum3mo > 600,
 # alt.value('green'), alt.value('brown')),
 ).properties(
  width=800,
  height=300
 )
 sun_chart_city_pts = alt.Chart(df_3mo, title=cityname).mark_line(color = 'orange').encode(
  alt.X('month', sort=alt.EncodingSortField(field='monthnum',order='ascending')),
  alt.Y('sunshine', title=('Sun Hours')),
 ).transform_filter(
  (datum.city == cityname)
 )
 sun_chart_city = alt.layer(sun_chart_city_3mo, sun_chart_city_pts)
 return sun_chart_city.copy()

sun_chart_sea = create_sun_chart_bar_f1(sun_df,'Seattle')
sun_chart_chi = create_sun_chart_bar_f1(sun_df,'San Francisco')
sun_chart_mia = create_sun_chart_bar_f1(sun_df,'Miami')

alt.vconcat(sun_chart_sea,sun_chart_chi,sun_chart_mia,title=titleQ)
```

I can also share images of the resultant charts if needed.  I fixed it by using:

``` python
months = ['Jan', 'Feb', ..., 'Dec']
alt.X('month', scale=alt.Scale(domain=months))
```
But the other behavior seems unintuitive, so Mick told me I should file a bug.  Thanks for taking a look!

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [ ] Search for duplicate issues.
- [ ] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by jheer** [comment] 2021-04-07 08:11
@domoritz @kanitw while filed here on Altair, this may be an underlying Vega-Lite issue.

**Comment by jakevdp** [comment] 2021-04-07 22:55
Thanks for the report - can you provide a minimal reproducible example that demonstrates the issue? (the above code does not include the data). Thanks!

**Comment by jasonhof** [comment] 2021-04-07 23:39
Sure- just attaching the data I linked to at the beginning of the post.  I hope this works for you!  Thanks for looking into it.

[sunshine.csv.zip](https://github.com/altair-viz/altair/files/6275063/sunshine.csv.zip)

**Comment by jakevdp** [comment] 2021-04-07 23:42
Could you provide a self-contained minimal example that doesn't require guessing how you load the data?

**Comment by jasonhof** [comment] 2021-04-08 00:07
Sure- I've cleaned up and attached the full code. Please let me know if that works.

[DV_HW1_JasonHoffman_v2ta.zip](https://github.com/altair-viz/altair/files/6275115/DV_HW1_JasonHoffman_v2ta.zip)

Also, sorry for the back and forth.  You don't need to fix this if you don't want to.  I was only filing the bug because Mick encouraged me to.  I'm new to Altair, so I'm not sure if this behavior is intended, but it seems unintuitive to me, so I figured I would share my experience.

**Comment by jakevdp** [comment] 2021-04-08 03:37
Sorry, I’m not really interested in downloading a zip file. If you can create a minimal reproducible example and paste the code here, I’ll take a look.

**Comment by joelostblom** [comment] 2023-02-06 01:16
I downloaded the data and tried the two sets of code: they both produce the same charts as far as I can see and I don't see anything out of order in the second chart (months are in alphabetical order in both charts). This might have been fixed in a later version of altair, but if you still see the error, please upload a minimal code example and post images highlighting what the issue is.

**Closed by joelostblom** 2023-02-06 01:16 UTC
Labels: bug
