### ISSUE TITLE
Mark_area for layered histograms 

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#1701] opened 2019-09-24 04:37 UTC
I am trying to figure out how to plot histograms in Altair layered on top of each other, but the interpolation type and bins is throwing me off. Bit of a complex question but I think I've broken it down into pieces.

Here is a MWE:

## Layered histogram in Altair (plot 1)

```import pandas as pd
import altair as alt
import numpy as np
np.random.seed(42)
np.random.normal(70, 10, 90)

# Generating Data
source = pd.DataFrame({
    'Trial A': np.append([0]*10, np.random.normal(70, 10, 90)),
    'Trial B': np.append([0]*15, np.random.normal(75, 10, 85)),
    'Trial C': np.append([0]*20, np.random.normal(65, 10, 80))
})

# Melt data to wrangle beforehand
source = source.melt()
alt.Chart(source).mark_area(
    opacity=0.6,
    interpolate='step'
).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[
        0, 100], step=5)),
    alt.Y('count()', stack=None),
    alt.Color('variable:N')
)
```

Output: 
![visualization-2](https://user-images.githubusercontent.com/2507459/65481003-95939700-de48-11e9-9490-1be4b2001c36.png)

## Faceted plot using the same data in Altair (Plot 2A,2B,2C)

```
alt.Chart(source).mark_area(
    opacity=0.9,
    interpolate='step'
).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[
          0, 100], step=5)),
    alt.Y('count()'),
    alt.Color('variable:N'),facet='variable:N'
).properties(columns=1)
```

Output:

![visualization-3](https://user-images.githubusercontent.com/2507459/65481329-b9a3a800-de49-11e9-9d00-87a5bf21e04e.png)

## Faceted plot in Seaborn (Ground truth) (Plot 3A,3B,3C)

```
import seaborn as sns 

g = sns.FacetGrid(source, row='variable', hue='variable')
g.map(sns.distplot, "value", rug=False, hist=True,
      norm_hist=False, kde=False, bins=np.arange(0, 100, 5))
```

Output:
![Unknown](https://user-images.githubusercontent.com/2507459/65481300-9547cb80-de49-11e9-97fa-1b5664e06d7e.png)

My questions:

1) How come Plot 1 is not the same as Plot 2A,2B,2C overlaid on top of each other? 
2) There should be no numbers between x=1 and x=~35
3) What's going on with the bins at x=0 in Plots 1 and 2 ? (see Plot 3 for what is expected)
4) Notice that in Plot 2A and 2C, the values at 0 are not shown!
5) Is there a way to mark_area without interpolation?

Any advice is welcome

**Comment by jakevdp** [comment] 2019-09-24 05:43
The issue is that an ``area`` mark with ``interpolate='step'`` is not doing what you think it is. You can see this by changing the mark to a line:
```python
alt.Chart(source).mark_line(point=True).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[0, 100], step=5)),
    alt.Y('count()', stack=None),
    alt.Color('variable:N')
)
```
![visualization - 2019-09-23T221638 434](https://user-images.githubusercontent.com/781659/65483083-d2af5780-de4f-11e9-85ff-93ccc2ae1bf7.png)

When you choose ``interpolate='step'``, you are specifying that the line should draw a step midway between each defined point:
```python
alt.Chart(source).mark_line(
    point=True,
    interpolate='step'
).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[0, 100], step=5)),
    alt.Y('count()', stack=None),
    alt.Color('variable:N')
)
```
![visualization - 2019-09-23T223410 061](https://user-images.githubusercontent.com/781659/65483769-4488a080-de52-11e9-9886-fa79e5f6c8f9.png)

I agree that this isn't very intuitive – I would expect ``count()`` to actually return zero within the empty bins. Probably the easiest way around this is to use a bar mark rather than a stepped-area mark:
```python
alt.Chart(source).mark_bar(
    opacity=0.6,
).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[0, 100], step=5)),
    alt.Y('count()', stack=None),
    alt.Color('variable:N')
)
```
![visualization - 2019-09-23T224131 862](https://user-images.githubusercontent.com/781659/65484129-4c951000-de53-11e9-9026-52df62cc87cf.png)

Though if you're really attached to stepped-area charts, you could probably use the [impute property](https://vega.github.io/vega-lite/docs/impute.html) to impute the missing values within the bins.

**Comment by jakevdp** [comment] 2019-09-24 06:00
I raised this issue in the Vega-Lite repository to see if they have any ideas: https://github.com/vega/vega-lite/issues/5403

**Comment by firasm** [comment] 2019-09-24 06:36
Aha! I am not crazy...

Great, thanks for your explanation!

Actually I was able to get stepped-area charts just by setting `binwidth` to 0 using `mark_bar`:

```
alt.Chart(source).mark_bar(
    opacity=0.6,
    binSpacing=0
).encode(
    alt.X('value:Q', bin=alt.Bin(extent=[0, 100], step=5)),
    alt.Y('count()', stack=None),
    alt.Color('variable:N'),facet='variable:N'
).properties(columns=1)
```

output: 

![visualization-4](https://user-images.githubusercontent.com/2507459/65486965-ad741680-de5a-11e9-9734-5857d122339e.png)

That being said, I maintain that this behaviour actually produces incorrect graphs when using quantitative data, and there could be a warning.

Happy to close the issue here or leave open till the linked one is resolved.

**Comment by joelostblom** [comment] 2023-09-21 02:39
Closing as this is tracked in https://github.com/vega/vega-lite/issues/5403 and there is nothing that can be done on the altair side of things to fix it.

**Closed by joelostblom** 2023-09-21 02:39 UTC
Labels: enhancement, question, vega-lite-related
