### ISSUE TITLE
Bug in `transform_density`

### ISSUE THREAD

**Issue by SergioMarreroMarrero** [altair-viz/altair#2518] opened 2021-11-10 12:59 UTC
When using this template code for producing a `density plot` I get an unusual error. 

```
pip install vega_datasets altair
```

```
import altair as alt
from vega_datasets import data

alt.Chart(data.movies.url).transform_density(
    'IMDB_Rating',
    as_=['IMDB_Rating', 'density'],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
)
```
output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_114833/675806787.py in <module>
      2 from vega_datasets import data
      3 
----> 4 alt.Chart(data.movies.url).transform_density(
      5     'IMDB_Rating',
      6     as_=['IMDB_Rating', 'density'],

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/vegalite/v4/api.py in transform_density(self, density, as_, bandwidth, counts, cumulative, extent, groupby, maxsteps, minsteps, steps)
    942         """
    943         return self._add_transform(
--> 944             core.DensityTransform(
    945                 density=density,
    946                 bandwidth=bandwidth,

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/vegalite/v4/schema/core.py in __init__(self, density, bandwidth, counts, cumulative, extent, groupby, maxsteps, minsteps, steps, **kwds)
  18098                  extent=Undefined, groupby=Undefined, maxsteps=Undefined, minsteps=Undefined,
  18099                  steps=Undefined, **kwds):
> 18100         super(DensityTransform, self).__init__(density=density, bandwidth=bandwidth, counts=counts,
  18101                                                cumulative=cumulative, extent=extent, groupby=groupby,
  18102                                                maxsteps=maxsteps, minsteps=minsteps, steps=steps, **kwds)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/vegalite/v4/schema/core.py in __init__(self, *args, **kwds)
  17973 
  17974     def __init__(self, *args, **kwds):
> 17975         super(Transform, self).__init__(*args, **kwds)
  17976 
  17977 

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/utils/schemapi.py in __init__(self, *args, **kwds)
    174 
    175         if DEBUG_MODE and self._class_is_valid_at_instantiation:
--> 176             self.to_dict(validate=True)
    177 
    178     def copy(self, deep=True, ignore=()):

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/utils/schemapi.py in to_dict(self, validate, ignore, context)
    335         if validate:
    336             try:
--> 337                 self.validate(result)
    338             except jsonschema.ValidationError as err:
    339                 raise SchemaValidationError(self, err)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/altair/utils/schemapi.py in validate(cls, instance, schema)
    440             schema = cls._schema
    441         resolver = jsonschema.RefResolver.from_schema(cls._rootschema or cls._schema)
--> 442         return jsonschema.validate(instance, schema, resolver=resolver)
    443 
    444     @classmethod

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in validate(instance, schema, cls, *args, **kwargs)
    963     cls.check_schema(schema)
    964     validator = cls(schema, *args, **kwargs)
--> 965     error = exceptions.best_match(validator.iter_errors(instance))
    966     if error is not None:
    967         raise error

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/exceptions.py in best_match(errors, key)
    352     """
    353     errors = iter(errors)
--> 354     best = next(errors, None)
    355     if best is None:
    356         return

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in iter_errors(self, instance, _schema)
    222 
    223                     errors = validator(self, v, instance, _schema) or ()
--> 224                     for error in errors:
    225                         # set details if not already set by the called fn
    226                         error._set(

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/_validators.py in ref(validator, ref, instance, schema)
    296 
    297         try:
--> 298             yield from validator.descend(instance, resolved)
    299         finally:
    300             validator.resolver.pop_scope()

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in descend(self, instance, schema, path, schema_path)
    238 
    239         def descend(self, instance, schema, path=None, schema_path=None):
--> 240             for error in self.evolve(schema=schema).iter_errors(instance):
    241                 if path is not None:
    242                     error.path.appendleft(path)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in iter_errors(self, instance, _schema)
    222 
    223                     errors = validator(self, v, instance, _schema) or ()
--> 224                     for error in errors:
    225                         # set details if not already set by the called fn
    226                         error._set(

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/_validators.py in properties(validator, properties, instance, schema)
    330     for property, subschema in properties.items():
    331         if property in instance:
--> 332             yield from validator.descend(
    333                 instance[property],
    334                 subschema,

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in descend(self, instance, schema, path, schema_path)
    238 
    239         def descend(self, instance, schema, path=None, schema_path=None):
--> 240             for error in self.evolve(schema=schema).iter_errors(instance):
    241                 if path is not None:
    242                     error.path.appendleft(path)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in iter_errors(self, instance, _schema)
    222 
    223                     errors = validator(self, v, instance, _schema) or ()
--> 224                     for error in errors:
    225                         # set details if not already set by the called fn
    226                         error._set(

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/_validators.py in items(validator, items, instance, schema)
     74     else:
     75         for index in range(prefix, total):
---> 76             yield from validator.descend(
     77                 instance=instance[index],
     78                 schema=items,

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in descend(self, instance, schema, path, schema_path)
    238 
    239         def descend(self, instance, schema, path=None, schema_path=None):
--> 240             for error in self.evolve(schema=schema).iter_errors(instance):
    241                 if path is not None:
    242                     error.path.appendleft(path)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in iter_errors(self, instance, _schema)
    212                 return
    213 
--> 214             scope = id_of(_schema)
    215             if scope:
    216                 self.resolver.push_scope(scope)

~/Documents/repos/prueba/venv/lib/python3.8/site-packages/jsonschema/validators.py in _id_of(schema)
     88     if schema is True or schema is False:
     89         return ""
---> 90     return schema.get("$id", "")
     91 
     92 

AttributeError: 'list' object has no attribute 'get'
```

System:
- Ubuntu 20.04
- python 3.8.10

**Comment by jakevdp** [comment] 2021-11-10 13:18
This is an issue with version 4.0 of the jsonschema package. To fix it, run
```
pip install jsonschema<4.0
```
Altair's next release will be made compatible with jsonschema 4.0. and newer.

**Comment by jakevdp** [comment] 2021-11-10 13:19
Duplicate of #2496

**Closed by jakevdp** 2021-11-10 13:19 UTC
Labels: bug
