### ISSUE TITLE
Z-zag time series plots

### ISSUE THREAD

**Issue by elksie5000** [altair-viz/altair#3212] opened 2023-10-02 07:17 UTC
I'm not sure this is a bug report but I often seem to have what I call a  zig-zag plot while trying plot time series 

Probably best described with a question on Stackoverflow - [the question](https://stackoverflow.com/questions/77213646/how-to-solve-unusual-time-series-plots-in-altair)

<img width="196" alt="image" src="https://github.com/altair-viz/altair/assets/890324/f39aa074-815e-4ff0-bc5f-76e9e57b9c40">

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [ ] Search for duplicate issues.
- [ ] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by elksie5000** [comment] 2023-10-02 13:46
https://stackoverflow.com/questions/77213646/how-to-solve-unusual-time-series-plots-in-altair

**Comment by ChristopherDavisUCI** [comment] 2023-10-02 14:09
Your Altair code looks fine to me, so my best guess is that it is an issue with the data.  Maybe something with missing values?  I tried using your sample data and was not able to reproduce the issue.  (Is `df` a pandas DataFrame?)

<img width="405" alt="linechart" src="https://github.com/altair-viz/altair/assets/82750240/4d1eb3c9-ddc1-4517-b793-97e1c1767b48">

**Comment by elksie5000** [comment] 2023-10-03 08:42
Good morning,

I hope you're well.  I'm enjoying Voltaire and seeing what I can do with
iit.

Here's another example of odd plots. Not sure why. There is another quirk
with a chart that I've attached on obesity-related hospital admissions.
Sometimes you get that and when the chart loads, the area defaults to North
East. However, if you click to another area and then click back it shows
the right results.

[image: image.png]

This came from finding data that that the number of these admissions have
risen from 300,000 in 2013 to 700,000 in 2019 (see top left). The second
chart shows that around 2/3 of women are likely to be admitted than men and
then I have a regional breakdown on the right.
They are all really quite straightforward and Altair makes it easy to say
switch the gender chart to the pie chart that has a hole in it.

[image: image.png]

I have one question about what is supposed to be the big visual for the
data geeks (It is an attached in HTML). Some of the regions have a lot of
local authorities and that means can difficult to see trends.
How do do you make every line grey and bring it it up as red if you cross
it or at least one of the points? I've seen it done but for the life of me
can't get it to work. A simple workaround is to increase the sizes of the
circles, I guess, but I don't know how to write the condition to highlight
a line as red.

And I'm guessing this is beyond the scope of the project, but would it be
possible to create a feature to build on the back of the | and &
functionality which would allow the creation of a simple HTML text box
(Chart). I did try looking at the HTML of this project  but suspect I'd
break it if I tried to work it out myself.

Anyway, thank you for keeping the project going. The hardest part of my
project was cleaning the data, rather than creating largely through Altair.

Kind regards.

David Elks

**Comment by mattijn** [comment] 2023-10-03 13:54
I'm loving homophone of Voltaire to Altair!
Your last comment is not entirely visible on Github, this is what we see: https://github.com/altair-viz/altair/issues/3212#issuecomment-1744498219.

Regarding your original question in SO:
To use a `temporal` datatype you will have to cast your integer year column to strings in your DataFrame before pushing it into the Altair chart.
```python
df = pd.DataFrame(
    {
        "year": [2014, 2015, 2016, 2017, 2018, 2019],
        "admissions": [200, 300, 450, 500, 700, 900],
    }
)
df.year = df.year.astype(str)  # <---

alt.Chart(df).mark_line().encode(alt.X("year:T"), alt.Y("admissions:Q"))
```
![image](https://github.com/altair-viz/altair/assets/5186265/839bc96b-b7e2-492d-9851-7a34771c586d)

See also
- First issue with the request to have better support for integer years: https://github.com/altair-viz/altair/issues/1365
- This issue with the request to document this using string casting: https://github.com/altair-viz/altair/issues/3162
- Apparently this is not necessary with VegaFusion activated: https://github.com/hex-inc/vegafusion/issues/402#issuecomment-1740226577

I think this issue is resolved. Closing this issue for now.
Feel free to open a new issue for feature requests or if you see behavior that is potentially a bug.

**Closed by mattijn** 2023-10-03 13:54 UTC
Labels: bug
