### ISSUE TITLE
convert_dtype warning due to latest pandas release

### ISSUE THREAD

**Issue by ogencoglu** [altair-viz/altair#3185] opened 2023-09-06 19:00 UTC
Latest pandas version (v2.1.0) throws this warning due to `convert_dtype` in altair core.
```
python3.9/site-packages/altair/utils/core.py:384: FutureWarning:

the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
```

**Comment by joelostblom** [comment] 2023-09-09 14:48
Closing as duplicate of https://github.com/altair-viz/altair/issues/3181

**Closed by joelostblom** 2023-09-09 14:48 UTC
Labels: bug
