### ISSUE TITLE
Problem in Jupyter Notebook for large datasets

### ISSUE THREAD

**Issue by vcuspinera** [altair-viz/altair#2051] opened 2020-03-29 19:46 UTC
In **Jupyter Notebook**, when I use `alt.data_transformers.enable('json')` to work with larger datasets (to avoid [MaxRowsError](https://altair-viz.github.io/user_guide/faq.html#local-filesystem)), if I save the Altair plot I get an empty plot (only with the axis, but none information).
I use the [Simple Stacked Area Chart](https://altair-viz.github.io/gallery/simple_stacked_area_chart.html) code as an example of the problem, and also use `alt.renderers.enable('default')` as described in [Trouble-shooting Altair with Notebook](https://altair-viz.github.io/user_guide/troubleshooting.html#notebook-vegalite-4-object):
```
import altair as alt
from vega_datasets import data
alt.data_transformers.enable('json')
alt.renderers.enable('default')

source = data.iowa_electricity()

my_plot=alt.Chart(source).mark_area().encode(
    x="year:T",
    y="net_generation:Q",
    color="source:N"
)
my_plot.save('plot.png')
my_plot
```
This is what I am getting back in both, Jupyter Notebook and plot.png:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/53915521/77858741-337e6a80-71ba-11ea-8ed6-eddd35234326.png">

**Is there a solution or an alternative to work with large datasets using Altair 4 in Jupiter Notebook?**

**Comment by jakevdp** [comment] 2020-03-29 19:49
This is a duplicate of #1370.

The solution is to not use the JSON transformer

In the next release of Altair, trying to do this will result in a warning telling you the same.

**Closed by jakevdp** 2020-03-29 19:49 UTC

**Comment by khalido** [comment] 2020-04-04 05:00
When I use the json transformer, I can see that it saves the json data file in the same directory as the jupyter notebook. Is it possible to modify this that for jupyter altair looks for the json file in the same dir? 

Asking as using the data server isn't always possible.

**Comment by jakevdp** [comment] 2020-04-04 05:20
The JSON transformer saves the file to the current working directory in your Python runtime. The frontend looks for the file in the root of the Jupyter server; you can adjust this by passing the ``urlpath`` parameter to the data_transformer. For example
```python
alt.data_transformers.enable('json', urlpath='/path/to/my/dir/')
```
It's up to you to ensure that this path is accessible to the Jupyter server, and corresponds to the current Python working directory where the JSON file will be saved.
