### ISSUE TITLE
Tooltips with `repeat`-ed fields work erratically

### ISSUE THREAD

**Issue by ilyagr** [altair-viz/altair#1116] opened 2018-08-25 06:40 UTC
The following code works on my system (Altair 2.2.1, colab interface). However, *if I uncomment the second part of the tooltip*, I get no output. The corresponding [Vega-Lite](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEBOCmAOsCGAXSAuMoIUgYwHsAbAVwFsA7DMAbUgFkBLI2AZwH1Fp2BxJIogSoAaKAEE8eWC2ipGQyKMgAJAtFYICAd1jRIAXWHgcMbdTqr1mnXqUSpMuQqVMWHLr36Cq+4wF8jXAASVjwAC1gyJGpIMJQUeFZ0AHpkgDdYAHMkADpMxhQwkgAjHPlk0Iio9KykAFoiAth0gCYcgDYcgAYcgCtWZ2NIVkQ8amwTWApCABNGCkzx4xwoAA9xyAAzRmkZjbhEVBjCUkpIAKgUAE9EGIBHEiQKFAK5DPPAlagrje3d-YQyDQmFMWg+lxusHuj2erxe7wCyxMJzUvx2RD2IIA8tBGPkRBDbiCKAQyPN+B8kbgUARiC94OZgFt0ZisDBAUcQdAzBdINciVAHk8Xig3lCLky-hiAYdgVATuQqLz+VCQULYaL4eLfCtEStIFpGDNCtQAIwAVi6n1wUWgAGtjoxoHgWIokbFYHi4mbLdaoDNUNFMBN9SRoEQYnEEklUhlsnkCkVSuU4-UA6KNChWMl00hkngkOo+gMRFSoJs1FE5UyVTF+go-EjGxA9fKhNtFsHIGkdmCu4bjWFqAAWLpWqARL1ygDMY78jb8QA) code seems to work fine.

In addition, I couldn't find out how to achieve this effect in the documentation. Am I doing something wrong, perhaps?

```python
import altair as alt
from vega_datasets import data

alt.Chart(data.cars.url).mark_circle().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='Origin:N',
    tooltip = [alt.Tooltip(alt.repeat("row"), type="quantitative")  
              # , alt.Tooltip(alt.repeat("column"), type="quantitative")
              ]
).properties(
    width=150,
    height=150
).repeat(
    row=['Horsepower', 'Acceleration', 'Miles_per_Gallon'],
    column=['Miles_per_Gallon', 'Acceleration', 'Horsepower']
)
```

**UPDATE**: There is also an error in the Javascript console:
```
Uncaught (in promise) Error: Expression parse error: {"Horsepower": format(datum["Horsepower"], ""), "Horsepower": format(datum["Horsepower"], "")}
    at o (ipyvega.js:1)
    at NA (ipyvega.js:16)
    at SN (ipyvega.js:16)
    at CN (ipyvega.js:16)
    at DN (ipyvega.js:16)
    at FN (ipyvega.js:16)
    at yT (ipyvega.js:16)
    at ipyvega.js:16
    at Array.forEach (<anonymous>)
    at AT (ipyvega.js:16)
```

Something similar seems to happen in Jupyterlab as well.

**Comment by jakevdp** [comment] 2018-08-25 17:08
I can't reproduce this. Does it happen for you in the vega editor as well?

**Comment by ilyagr** [comment] 2018-08-25 19:37
No, the link I gave to the Vega editor has a working chart for me. Perhaps this bug was fixed in vega-lite, but recently enough that both the colab and Jupyterlab are still affected.

**Comment by jakevdp** [comment] 2018-08-26 15:56
Yeah, I think that's probably the case.

**Comment by jakevdp** [comment] 2019-05-30 06:02
Confirmed that this is fixed in Altair 3.

**Closed by jakevdp** 2019-05-30 06:02 UTC
