### ISSUE TITLE
Exporting Jupyter Notebook to HTML gives vega-util script error

### ISSUE THREAD

**Issue by amcadie** [altair-viz/altair#2284] opened 2020-09-08 22:21 UTC
I've got a project where I create an Altair chart in a Jupyter Notebook, use nbconvert to run the notebook and export it to html, and then serve the html as a static webpage.  I've gotten it up and running with the nbconvert call inside a Docker container.  Starting last week, when loading the website, in place of the chart, there is the following error: 

Error loading script: Script error for: vega-util http://requirejs.org/docs/errors.html#scripterror.

I'm not sure how to submit a full reprex given all the moving pieces, but I was able to reproduce with the following minimal code in a Jupyter notebook, and then manually exporting to html from within Jupyter:

``` 
import altair as alt
import pandas as pd

df = pd.DataFrame({'x': [1,2,3,4,5], 'y': [5,6,7,4,6]})

alt.Chart(df).mark_point().encode(x='x', y = 'y').interactive() 
```

Given the extremely minimal example, and the fact that the process was running in a stable Docker environment for a couple of weeks leads me to believe that the problem may have something to do with a vega-lite plug-in on the browser side, although the error occurs on Chrome and Safari.  I have quite a small knowledge of web development, but please let me know if there is any more detail I can provide that might be of help.

I'm attaching screen shots of the example Jupyter Notebook, and the exported html.
<img width="1120" alt="exported_html" src="https://user-images.githubusercontent.com/11549968/92532911-37d99580-f1e6-11ea-89f3-a30fb82c0ab9.png">
<img width="1076" alt="altair_notebook" src="https://user-images.githubusercontent.com/11549968/92532916-39a35900-f1e6-11ea-9782-6017e3e2370e.png">

**Comment by amcadie** [comment] 2020-09-08 23:10
After some more poking around, it looks like at some point in the script there is a failed request for vega-util.js, looking in the same directory as the html file.  I'm attaching a screen shot with this highlighted in Chrome's developer tools.  

<img width="1422" alt="altair_dev_tools" src="https://user-images.githubusercontent.com/11549968/92536138-c43b8680-f1ed-11ea-8014-de0a679848b1.png">


Perphaps there is some issue with the boilerplate code that gets generated during the Jupyter -> html export process?  This is what is in the html:

```
<div class="output_html rendered_html output_subarea output_execute_result">

<div id="altair-viz-3"></div>
<script type="text/javascript">
  (function(spec, embedOpt){
    const outputDiv = document.getElementById("altair-viz-3");
    const paths = {
      "vega": "https://cdn.jsdelivr.net/npm//vega@5?noext",
      "vega-lib": "https://cdn.jsdelivr.net/npm//vega-lib?noext",
      "vega-lite": "https://cdn.jsdelivr.net/npm//vega-lite@4.0.0?noext",
      "vega-embed": "https://cdn.jsdelivr.net/npm//vega-embed@6?noext",
    };

    function loadScript(lib) {
      return new Promise(function(resolve, reject) {
        var s = document.createElement('script');
        s.src = paths[lib];
        s.async = true;
        s.onload = () => resolve(paths[lib]);
        s.onerror = () => reject(`Error loading script: ${paths[lib]}`);
        document.getElementsByTagName("head")[0].appendChild(s);
      });
    }

    function showError(err) {
      outputDiv.innerHTML = `<div class="error" style="color:red;">${err}</div>`;
      throw err;
    }

    function displayChart(vegaEmbed) {
      vegaEmbed(outputDiv, spec, embedOpt)
        .catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));
    }

    if(typeof define === "function" && define.amd) {
      requirejs.config({paths});
      require(["vega-embed"], displayChart, err => showError(`Error loading script: ${err.message}`));
    } else if (typeof vegaEmbed === "function") {
      displayChart(vegaEmbed);
    } else {
      loadScript("vega")
        .then(() => loadScript("vega-lite"))
        .then(() => loadScript("vega-embed"))
        .catch(showError)
        .then(() => displayChart(vegaEmbed));
    }
```

At this point it doesn't exactly seem like an Altair issue, but if you could point me in the right direction, I'd really appreciate it!

**Comment by jakevdp** [comment] 2020-09-08 23:17
Duplicate of #2280. Clear your browser caches; it should be fixed now.

**Closed by jakevdp** 2020-09-08 23:17 UTC

**Comment by amcadie** [comment] 2020-09-09 03:29
Ack I'm sorry for the dup!  I did some keyword searches though the issues for nbconvert, etc, but somehow missed the recent discussion.  That did the trick, thanks so much Jake!
