### ISSUE TITLE
Custom order when faceting fails when aggregating

### ISSUE THREAD

**Issue by cjbraun** [altair-viz/altair#2046] opened 2020-03-28 00:13 UTC
This is an example I've seen for sorting 

```python
from vega_datasets import data
import altair as alt

stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='price',
  color='symbol',
  column=alt.Column('symbol', sort=['GOOG', 'IBM', 'AAPL', 'AMZN', 'MSFT'])
)
```

When we add aggregation to the y variable though, the sorting fails:

```python
alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='sum(price)',
  color='symbol',
  column=alt.Column('symbol', sort=['GOOG', 'IBM', 'AAPL', 'AMZN', 'MSFT'])
)
```

And it's kind of unclear how it is sorting in this case.

**Comment by jakevdp** [comment] 2020-03-28 01:39
Thanks for this report - it looks like a Vega-Lite bug. As a workaround, it appears that if you compute the sum in a transform rather than in an encoding, it works properly:
```python
alt.Chart(stocks).mark_line().transform_aggregate(
  sum_price='sum(price)',
  groupby=['date', 'symbol']
).encode(
  x='date:T',
  y='sum_price:Q',
  color='symbol:N',
  column=alt.Column('symbol:N', sort=['GOOG', 'IBM', 'AAPL', 'AMZN', 'MSFT'])
)
```

**Comment by jakevdp** [comment] 2020-03-28 14:53
Vega-Lite issue is here: https://github.com/vega/vega-lite/issues/5366

I'm going to close this as a duplicate of #1683

**Closed by jakevdp** 2020-03-28 14:53 UTC
