### ISSUE TITLE
Saving via chart.save in conjunction with alt.data_transformers.enable('json') results in empty chart

### ISSUE THREAD

**Issue by kaisengit** [altair-viz/altair#1665] opened 2019-08-19 09:45 UTC
Using the following versions (via `conda list | egrep altair\|vega\|selenium\|jupyter`):
```
altair                    3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                1.0.4                    py37_0    conda-forge
jupyterlab_server         1.0.4                      py_0    conda-forge
selenium                  3.141.0         py37h14c3975_1000    conda-forge
vega                      2.3.2                    py37_0    conda-forge
vega_datasets             0.7.0                      py_0    conda-forge
```
Using `chromedriver 75.0.3770.100-3.fc30` on Fedora 30.

I regularly work with big data sets (> 5000 rows) so I need to enable `alt.data_transformers.enable('json')`. Working in jupyerlab by the way.

Saving the following chart works fine:
```
from vega_datasets import data
df1=data.barley()

base = alt.Chart(df1).mark_bar().encode(
    y=alt.Y('mean(yield)'),
    x=alt.X('variety'),
    tooltip=['mean(yield)']
)

bars = base.encode(
    color=alt.Color('variety', legend=alt.Legend(orient='top')),
)

text = base.mark_text(dx=-15, dy=-5, color='black').encode(
    text=alt.Text('mean(yield)', format='.1f')
)

error = base.mark_errorbar()

(bars+text+error).save('test.png')
```
![test](https://user-images.githubusercontent.com/29574032/63255488-2a1d3f00-c276-11e9-9110-0f5cba699dcc.png)

However, enabling `alt.data_transformers.enable('json')` before saving will result in the following image:
![testb](https://user-images.githubusercontent.com/29574032/63255527-428d5980-c276-11e9-99ed-71b90537dabe.png)

**Comment by jakevdp** [comment] 2019-08-19 15:15
Duplicate of #1370.

The workaround is to disable the data transformer before saving.

**Closed by jakevdp** 2019-08-19 15:15 UTC
