### ISSUE TITLE
HTML output not displaying 

### ISSUE THREAD

**Issue by mr-ubik** [altair-viz/altair#342] opened 2017-06-19 14:27 UTC
I have been trying to display the HTML ouput without any success. I noticed that the generated html differs from the one [present here](https://vega.github.io/vega-lite/tutorials/getting_started.html#embed) both at the beginning and the end. If I copy the said code it works fine.

**Comment by jakevdp** [comment] 2017-06-19 20:34
Hi – I suspect it is an issue with the Vega-Lite Javascript library URLs. The Vega-Lite team recently pushed a non-backward-compatible update to their javascript libraries. This has been fixed in master, but not yet fixed in an Altair release. Try installing from master and then it should work.

**Comment by helgammal** [comment] 2017-06-20 23:26
Hi,

I'm bumping into this too. Looks like the URL's aren't updated on master either? 
For example, [this](https://github.com/altair-viz/altair/blob/master/altair/urls.py#L3) one gives a 404.

**Comment by jakevdp** [comment] 2017-06-21 02:13
Yes, that URL seems to be broken now. It worked when I added it a few weeks ago *grumble grumble*

@kanitw, @domoritz, can you confirm what the stable URLs are going to be for Vega-Lite 1.x?

**Comment by jakevdp** [comment] 2017-06-21 02:15
Regarding embedding in the notebook: I think the issue is that you have to use ``require.js`` to load the libraries in that case. It's slightly different code than what is used in the stand-alone HTML version.

**Comment by javadba** [comment] 2017-06-25 01:41
Where is vega-lite.js defined *today* ? i.e. what workaround do we use given https://vega.github.io/vega-lite/vega-lite.js  is 404?

**Comment by domoritz** [comment] 2017-06-25 06:00
I suggest loading the library from cdnjs. See https://cdnjs.com/libraries/vega-lite

For example, the latest 1.x release is at https://cdnjs.cloudflare.com/ajax/libs/vega-lite/1.3.1/vega-lite.js.

**Comment by jakevdp** [comment] 2017-06-30 17:34
@domoritz – thanks! It may be worth using these stable URLs in the examples on the vega/vega-lite websites. I copied this HTML template from the vega-lite website when I initially created it.

**Comment by domoritz** [comment] 2017-06-30 18:55
@jakevdp Definitely. I just checked. The Vega docs describe how to use CDNJS ( https://vega.github.io/vega/usage/) and the Vega-Lite usage docs also say that you should use CDNJS (https://vega.github.io/vega-lite/usage/embed.html). I made a note for myself to clean up the docs regarding this at https://github.com/vega/vega-lite/issues/2615.

**Comment by eocarragain** [comment] 2017-07-03 15:05
Addressed in https://github.com/altair-viz/altair/commit/834df80b94456710d6a2eb8b9d7f9a3c8b7a13df

**Comment by jakevdp** [comment] 2017-07-03 15:08
Thanks!

**Closed by jakevdp** 2017-07-03 15:08 UTC

**Comment by javadba** [comment] 2017-07-09 01:39
The given url for vega-lite does 403

**Comment by javadba** [comment] 2017-07-09 01:39
specifically:  https://cdnjs.cloudflare.com/ajax/libs/vega-lite/1.3.1/vega-lite.js .
