### ISSUE TITLE
Selection doesn't work with time variables

### ISSUE THREAD

**Issue by sidravi1** [altair-viz/altair#886] opened 2018-05-22 15:51 UTC
Hi,

The selection doesn't seem to work with time variable:

```
cars = data.cars.url

brush = alt.selection(type='interval')

points = alt.Chart().mark_point().encode(
    x='Year:T',  # This is the only thing different from the example
    y='Miles_per_Gallon:Q',
    color=alt.condition(brush, 'Origin:N', alt.value('lightgray'))
).properties(
    selection=brush
)

bars = alt.Chart().mark_bar().encode(
    y='Origin:N',
    color='Origin:N',
    x='count(Origin):Q'
).transform_filter(
    brush.ref()
)

alt.vconcat(points, bars, data=cars)
```
![image](https://user-images.githubusercontent.com/14125957/40374107-63a8b1da-5db6-11e8-8451-0ecb7621835a.png)

Changing x to be "Horsepower:Q" in points works as expected

**Comment by jakevdp** [comment] 2018-05-22 17:26
Closing as a duplicate of #828

**Closed by jakevdp** 2018-05-22 17:26 UTC
Labels: vega-lite-related
