### ISSUE TITLE
custom sorting categorical axis with layers - working in VL3 Editor

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1137] opened 2018-09-18 13:42 UTC
Hi Jake,

Not sure if you've seen the recent[ slack discussion](https://vega-js.slack.com/archives/C4R371X41/p1537207975000100) on this but I wanted to let you know that the following works in the VL3 Editor but not in Altair. I'm referring to the sorting of the Y axis labels. 

```python
df=pd.DataFrame({'Org': ['school','school','school','school', 'board', 'board', 'board', 'board'],
                 'variable': ['rose', 'dropped', 'maintained', 'failed','rose', 'dropped', 'maintained', 'failed'],
                'percent': [25,25,25,25,25,25,25,25], 
                 'position': [12.5, 37.5,62.5, 87.5,12.5, 37.5,62.5, 87.5]})
    
bars=alt.Chart().mark_bar().encode(
    x=alt.X('sum(percent)', title='Percentage of Students'),
    y=alt.Y('Org', sort=['school'], title=None),
    color=alt.Color('variable', title=None),
    order='junk:Q'
)

text=alt.Chart().mark_text(align='center', baseline='middle').encode(
    y=alt.Y('Org', sort=['school'], title=None),
    x='position',
    text='percent')

alt.layer(bars, text, data=df).transform_calculate(
    junk="if(datum.variable === 'maintained', 0, if(datum.variable === 'rose', 1, if(datum.variable === 'dropped', 2, 2)))")
```
![visualization 28](https://user-images.githubusercontent.com/4624246/45691656-019d3a00-bb27-11e8-8802-e2a21cb4496d.png)

The VL folks showed me how to get this working and I thought perhaps it would translate to Altair 2.2. I assume it is simply a VL2 versus VL3 difference but wanted to bring it to your attention in case it is helpful for you to know.

**Comment by afonit** [comment] 2018-09-18 14:20
In the bars chart, for the why put this:
```python
y=alt.Y('Org', sort=alt.EncodingSortField(field='Org', op='sum', order='descending'), title=None),
```

**Comment by afonit** [comment] 2018-09-18 14:51
In the 'bars' chart, for the y put this:
```python
y=alt.Y('Org', sort=alt.EncodingSortField(field='Org', op='sum', order='descending'), title=None),
```
That now sorts 'board' before 'school' on the y-axis.

**Comment by Alcampopiano** [comment] 2018-09-18 14:51
@afonit What I am after is a custom sort, not alphabetical. For example, if I wanted apple in the middle with these data:

```python
df=pd.DataFrame({'Org': ['school','school','school','school', 'board', 'board', 'board', 'board', 
                         'apple','apple','apple','apple'],
                 'variable': ['rose', 'dropped', 'maintained', 'failed','rose', 'dropped', 'maintained', 'failed',
                             'rose', 'dropped', 'maintained', 'failed'],
                'percent': [25,25,25,25,25,25,25,25,25,25,25,25], 
                 'position': [12.5, 37.5,62.5, 87.5,12.5, 37.5,62.5, 87.5,12.5, 37.5,62.5, 87.5]}) 
```

Also, in your example above "board" and "school" do not get reversed when switching ascending/descending options as far as I can see.

**Comment by afonit** [comment] 2018-09-18 15:09
@Alcampopiano, humm, doing this again I am indeed not seeing it switch so I must have been mistaken.

I know that I filed a but in vega-lite for the layered sorting and they closed it as a duplicate of an existing issue: https://github.com/vega/vega-lite/issues/2177
Looking at that it is closed - so you may be right that this is an instance of altair in a later version will point at the newer version of vega-lite - or in my case using a version of jupyterlab that contains that updated renderer.

I think the custom sort you are after could be done with specifying manually the domain rage, I will post something on that if I figure it out.

**Comment by jakevdp** [comment] 2018-09-19 01:05
Altair is based on Vega-Lite 2. Vega-Lite 3 (which has not yet been released) handles these things differently. I'm not certain whether it's possible to get that behavior within Vega-Lite 2.

**Comment by Alcampopiano** [comment] 2018-09-19 01:08
@jakevdp No problem, just wanted to let you know about it. Take care.

**Comment by jakevdp** [comment] 2018-09-19 02:09
Once Vega-Lite 3 is released, we'll be able to update Altair to use it, and then this problem will be addressed.

**Comment by jtbaker** [comment] 2019-01-28 18:02
As of v2.3.0 with VL 3, axes may now be sorted by passing a custom sort array to the channel as such:

```
chart = alt.Chart(df, height=210).mark_rect().encode(
    x=alt.X("hour:N", title='Hour'), 
    y=alt.Y("dayofweek:O", sort=["Sun", "Mon", "Tue", "Wed", "Thurs", "Fri", "Sat"],
            title="Day of Week"),
    color=alt.Color(
        "cnt:Q", 
        scale=alt.Scale( range=['lightyellow','red']), 
        legend=alt.Legend(title='Count')
    ),
    tooltip=[
        alt.Tooltip("cnt:Q", title="Count")
    ]
)
```
![image](https://user-images.githubusercontent.com/25542515/51856071-bda01a00-22fc-11e9-84b5-c4cf0f7531f2.png)

**Closed** 2019-01-28 18:02 UTC

**Comment by DaviFrazao** [comment] 2023-05-10 14:05
The X-axis of my visualization is not in the defined order. It is always inverted.

```python
import altair as alt
import numpy as np
import pandas as pd

x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 + y ** 2

source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

sort4 = alt.Chart(source).mark_rect().encode(
    x=alt.X('x:O', sort=['0','1','-1','2','-2','3','-3','4','-4','-5']),
    y=alt.Y('y:O'),
    color='z:Q',
    tooltip=['x','y','z']
)
sort4
```

![image](https://github.com/altair-viz/altair/assets/6472713/a4ba7b8d-64ad-4156-9867-e8a78d9ccda4)
