### ISSUE TITLE
Tooltip can sometimes break histogram

### ISSUE THREAD

**Issue by ldegreef** [altair-viz/altair#2006] opened 2020-03-07 00:36 UTC
Sometimes, adding a tooltip to a histogram can make the chart display incorrectly.

For example, the following code executes as expected:
```
import numpy as np
import altair as alt
import pandas as pd

data = pd.DataFrame({'Value': np.random.normal(size=500)})

alt.Chart(data).mark_bar().encode(
    x=alt.X('Value', bin=True),
    y='count()',
    tooltip='count()'
)
```
Producing the following chart (with tooltips):
![image](https://user-images.githubusercontent.com/7135000/76132501-1fcf5200-5fc8-11ea-9dd9-3cddb41a7c05.png)

But encoding a different tooltip, as so:
```
alt.Chart(data).mark_bar().encode(
    x=alt.X('Value', bin=True),
    y='count()',
    tooltip='Value'
)
```
results in this unexpected chart:
![image](https://user-images.githubusercontent.com/7135000/76132534-5016f080-5fc8-11ea-8df2-5f390b7803c3.png)

Admittedly, I don't know what should be the exact behavior for tooltips displaying binned values, but I suspect it doesn't involve changing non-tooltip parts of the chart ;)

**Comment by jakevdp** [comment] 2020-03-07 02:47
This is working as intended.

Every chart involving an aggregate like ``count()`` involves a groupby over the unaggregated encodings.

In the first chart, you group by the binned values, and encoded the count in the y encoding and the tooltip encoding.

In the second chart, you group by the value and the binned value, and encode the count in the y encoding.

If you want a tooltip for the binned value, you can specify that directly:
```python
alt.Chart(data).mark_bar().encode(
    x=alt.X('Value', bin=True),
    y='count()',
    tooltip=alt.Tooltip('Value', bin=True)
)
```

**Comment by joelostblom** [comment] 2021-02-23 21:18
@ldegreef I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Closed by joelostblom** 2021-02-23 21:18 UTC
Labels: question
