### ISSUE TITLE
specifying domain/range for color scale puts everything from domain/range in legend even if it's not used

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#2075] opened 2020-04-08 23:57 UTC
```py
import altair as alt
import pandas as pd

domain = [
    "A",
    "B",
    "C",
]
range = [
    "#4daf4a",
    "#984ea3",
    "#ff7f00",
]

df = pd.DataFrame({"x": [1, 2, 3], "y": [3, 2, 1], "label": ["A", "B", "A"]})

alt.Chart(df).mark_point().encode(
    x="x",
    y="y",
    color=alt.Color("label", scale=alt.Scale(domain=domain, range=range)),
    shape="label",
)
```

![visualization](https://user-images.githubusercontent.com/976970/78844021-5fb79980-79b9-11ea-851c-405d244da1f5.png)

If every label is represented:

```py
df = pd.DataFrame({"x": [1, 2, 3], "y": [3, 2, 1], "label": ["A", "B", "C"]})

alt.Chart(df).mark_point().encode(
    x="x",
    y="y",
    color=alt.Color("label", scale=alt.Scale(domain=domain, range=range)),
    shape="label",
)
```

![visualization (1)](https://user-images.githubusercontent.com/976970/78844088-8e357480-79b9-11ea-9d51-4be5cd9d6bff.png)

I would prefer that
- Labels that aren't in the input data don't appear in the legend
- The color and scale legends are combined into one legend (as they would be without an explicit domain/range)

Thanks for lookin'!

**Comment by jakevdp** [comment] 2020-04-09 02:42
The first point is by design: specifying a domain and range is how you make the legend represent points that are not in the data (for example, when dynamically filtering).

The second point is a known issue; see #1785

**Comment by jowens** [comment] 2020-04-09 03:26
OK. Other than filtering the domain and range Scale arrays once I see the data, any other way to make it reflect the actual contents of the data? (Might be potentially interesting to make this an option to Scale, `legendOnlyReflectsDataBool`, that sort of thing.)

(The reason I'm using a domain/range is to get the colors consistent between different plots for the same labels. If there's another way to do this, I'm all ears.)

Thanks.

**Comment by jakevdp** [comment] 2020-04-09 03:37
I don't know of any way to make an explicit domain/range respond to the contents of the data. You might ask on the vega-lite lists.

**Comment by jowens** [comment] 2020-04-10 17:23
@jakevdp, @kanitw has a vega-lite hack (using "signal") that you might want to peek at, https://github.com/vega/vega-lite/issues/6310#issuecomment-612121376

**Comment by joelostblom** [comment] 2023-09-21 02:31
Since this is tracked in https://github.com/vega/vega/issues/2535 and https://github.com/altair-viz/altair/issues/1785, and it needs to be implemented in VL for it to become available in altair I'm closing this issue.

**Closed by joelostblom** 2023-09-21 02:31 UTC
Labels: enhancement, vega-lite-related
