### ISSUE TITLE
tooltip not showing in some compound charts

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#2010] opened 2020-03-11 04:26 UTC
This is not really an issue but a nuance that I came across and think it may be helpful for people who have also faced similar problem. 

*Problem:* for a compound chart, if a sub-chart is "interactive" then the tooltip for the other sub-charts might refuse to show up.
``` python
scatter.interactive() | bar
```
![Screen Shot 2020-03-10 at 9 19 04 PM](https://user-images.githubusercontent.com/10766549/76382110-df980880-6314-11ea-8227-8803f18d7bf5.png)

*Solution:* make all sub-charts "interactive".
``` python
scatter.interactive() | bar.interactive()
```
![Screen Shot 2020-03-10 at 9 23 19 PM](https://user-images.githubusercontent.com/10766549/76382270-664ce580-6315-11ea-93f2-2a1823b0d5de.png)

Colab [demo](https://colab.research.google.com/drive/1oNtX-2eOsqRt1j46mx5Jzrf4ywcOMNyn)

**Comment by jakevdp** [comment] 2020-03-11 04:31
Thanks for the report! This appears to be a duplicate of #2009, the root cause of which is https://github.com/vega/vega-lite/issues/6003

**Closed by jakevdp** 2020-03-11 04:31 UTC
