### ISSUE TITLE
blurry chart rendering in notebook.

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#2114] opened 2020-04-26 12:12 UTC
![image](https://user-images.githubusercontent.com/18221871/80307179-1610e080-87fa-11ea-9289-7969f798613f.png)

The resolution of charts produced by altair appears to be blurry when rendering in notebook. I wonder is there any configuration similar to matplotlib that allows user to set dpi manually.

```
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 300
```

**Comment by jakevdp** [comment] 2020-04-26 12:42
Duplicate of  #1002. There's no ``figure.dpi`` setting for Altair, because Altair always renders directly in display pixels, taking into account ``window.devicePixelRatio``. A couple things you might try:

- change your scaling setting on your OS or browser
- use the SVG renderer (`chart.display(renderer='svg')`)

**Comment by noklam** [comment] 2020-04-26 14:55
I tried with browser scaling setting, it appears blurry no matter how I change the scale (compare to export it as an image).

I find it strange that the same chart (with the same scaling) render in vega-lite editors is a lot sharper.

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUADYBDAJ4EATqQDaGiKAiWorbRW2kc8bQFsCpSDbsBaXgE4ARqwKAOza-sH+0KwArIgAjAoAbL7c-tyJClEATFn+CgAcWfZqZpaQztoGANbumtRu6lYQkATwcKzU6FgWTc0AHg6QFLoADm5YkACONNqiyHZUuA1QKASarO76lZAlvc26g8Nj7tOzVAvIS5BCkKvrtciIBACifSM7pRC7TUPzmuPYT5lCgEPryCYAGUunTAEIQqEM1yBzQYNH853+7ihTzAoLG0DsbV0YGoYAAstodERkGA4r5olkvFl+MFIEDlKVvuYgR5bPZupAnK53J5tD5EohWL5EPlorxEgq+HE0tFfL5WARotF8vl-Il5b4sjtGj8KtVDqMAZADDRMTc4JpYEYJgBiBTuj3XKAMCgGWBVAgsdhcLAKLllVrtTqDA4Co5W05zC5XG53DYTA6qTkaAC6JsgABIGNAOAQKu45BQRgwMAB6WtLVDaAB0qHmHDRzeQsFrxdLFQbBCbXjqIIb3GbvGbWWbACsGAgkc1RQwCBQGA5SrzvH5AiEwhEorEEslUulMqwcnlCvywKZej1euQaKIDLGoBSqcgl3tyHN4K04JQAAgogBjINA9gmk+WzOrS9JZNBPx1E8rzvKGiTTtEiRIVYkAjLA6FgFkvhxME+S8IhyJQKgrAjAACoYkFEUkvjNnEiRyhRWTsrhgJ7MI9Cvu+kCfto1I-k+IhiIB7igeBkGST8sGkHS0TBHxzQoS8byKME068Bp1H4YRig5HEWQFJpNF0YxBjMTwHHNqxFEZGq7m+IkvFAo+PxwC+voiWJEnWX+MmiHJYEQVBxkqVgdKJFRAmQNpaGKPkzbcHEoUESxiX5Pq+ShbRDFMdoRHcFk+m+LwcS8LK+r8E13DeQ+xn+cJ7jBd+oXSfUEUTPJ0VKXhcXwYkRnJalumhmx3AFR5i1qtEOWmVgWXcMEWQMsVtllRV9LNtEcSba5rVNL5eEdYFXWUuJPXtZQ-VAZAQ2KaFY10ltoXTRVcTNsECpNcDwMrcZuU8MEShqpNv4lXZDlYNqE6JV9fjnVYl1lNdb63V+I3Y09AEDSBUXvbFBDbPFvjBLDT6-TwCgAwqS2LTh4NrWA2EhFk6S7aV9nlaQCpMzkSSA15vThtyyU40Fd0hY9-6yYNZMxcln2+IUP2PDpFXRM2iRZazHns8lENYJxlGFGDyXw-twsKDOFEKIa6NS3xWPNHLeP3QT3tEyrpMKerv6a-kdPIbraXrfp3DqatRHkbzwSbfzCNC5bCgG8dUMZK7i0Y5YXuCQFuMTN1-uCcrJOvWrVeQJrho66hM1gNwc1Jb+Fu0vwJ28746cO0jGQGX38dFzLv4+xXCsPbLge129ocwZTcF0jTLd65DmX0onqm8MbarZcZ9uC0RyQzlV2p1SRhcez5j1l-L+O9YvL3Lw3Y3MpRW8x+3Bt+D5BNu5fe8U4iFG4B3W2cM9rn2FpxTKlk4gQMak1OIk9+LTyEjdWer8lbhQ-vXD6a9SA-0jnhBm60MpKCUCDEG3AwG0ndFVQyg9T5wMRmAYIqpnId1IrVdkpQ8xblFOKSU0pZTykVLVFUaoNRah1HqA0RosDGBwO+XgygcwaA5MoIAA

**Comment by noklam** [comment] 2020-04-26 15:06
Issue solved if I use Firefox instead of Chrome. I don't understand what happening but I will leave my version here in case anyone hit the same issue.

Chrome: 81.0.4044.122
Firefox:
altair: 4.0.1

|     |     |
| --- | --- |
| Chrome | Firefox |
| ![image](https://user-images.githubusercontent.com/18221871/80311396-07362800-8812-11ea-916f-6a67a9909a6b.png)| ![image](https://user-images.githubusercontent.com/18221871/80311402-0c937280-8812-11ea-9e97-38adbc2f5ece.png) |

**Comment by pybokeh** [comment] 2020-05-12 12:19
@noklam Same here.  It is definitely blurry for me with Chrome (version 80) and not blurry with Firefox (version 67).  

Laptop display, non-4K, Windows 10, altair version 4.1.0

**Comment by joelostblom** [comment] 2023-01-16 19:16
Closing since this seem to be browser (or maybe VL) related rather than something that can be fixed in Altair.

**Closed by joelostblom** 2023-01-16 19:16 UTC
Labels: question, vega-lite-related
