### ISSUE TITLE
Concatenation distorts interactive legend

### ISSUE THREAD

**Issue by lbittarello** [altair-viz/altair#2583] opened 2022-03-29 08:44 UTC
Sorry if this issue has been reported before!

Consider this example from [the documentation](https://altair-viz.github.io/user_guide/interactions.html#selection-targets-fields-and-encodings):

```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

selection = alt.selection_multi(fields=["Origin"])

color = alt.condition(
    selection, alt.Color("Origin:N", legend=None), alt.value("lightgray")
)

scatter = (
    alt.Chart(cars)
    .mark_point()
    .encode(x="Horsepower:Q", y="Miles_per_Gallon:Q", color=color, tooltip="Name:N")
)

legend = (
    alt.Chart(cars)
    .mark_point()
    .encode(y=alt.Y("Origin:N", axis=alt.Axis(orient="right")), color=color)
    .add_selection(selection)
)

scatter | legend
```
produces

![plot_1](https://user-images.githubusercontent.com/15511539/160570910-a5fd9e6d-b7ef-4ac3-bf2a-d91c8ac9fcad.png)

However, if we change the last line to
```python
alt.vconcat(scatter) | legend
```
we get

![plot_2](https://user-images.githubusercontent.com/15511539/160570968-0173b66d-1c8b-4560-a1c1-b0b23a6cb4fa.png)

This seems to be a regression – both plots look the same with Altair 4.1.0.

**Comment by jakevdp** [comment] 2022-03-29 18:37
Thanks for the report! It seems to be a change in Vega-Lite's default layout. I'm not sure whether it's a bug or intended behavior in the vega-lite renderer

**Comment by joelostblom** [comment] 2022-03-29 23:01
This is working for me as expected when installing Altair directly from the GitHub repos main branch so it must have been fixed in later versions of VL although I did find a few issues that seem related:

- https://github.com/vega/vega-lite/pull/6226
- https://github.com/vega/vega-lite/pull/6095
- https://github.com/vega/vega-lite/issues/6209
- https://github.com/vega/vega-lite/issues/6277 (open)

**Comment by mattijn** [comment] 2022-10-29 19:37
Fine for me too on development version. Closing seems fine then.

**Closed by mattijn** 2022-10-29 19:37 UTC
Labels: bug, vega-lite-related
