### ISSUE TITLE
Chart doesn't appear when using data_transformers to save chart data to local filesystem

### ISSUE THREAD

**Issue by d-gleeson** [altair-viz/altair#2110] opened 2020-04-24 13:40 UTC
I'm running a fresh install of altair v4.1.0 and jupyterlab 2.1.0 in a fresh conda environment. Charting works fine, until I run:

` alt.data_transformers.enable('json') `

At which point only a blank plot appears with axis labels but no data plotted and no error message to diagnose. For example:

```
import altair as alt
import pandas as pd

# some dummy data
df = pd.DataFrame({'Day' : [0, 1, 2, 3],
                   'AvgTemperature' : [22.1, 19.9, 19.8, 20.1]})

alt.Chart(df).mark_point().encode(
    x='Day',
    y='AvgTemperature')
```

Produces the following chart:
![image](https://user-images.githubusercontent.com/7363923/80217652-f5992880-8637-11ea-9714-bca4b228e4b9.png)

But when I run:
```
alt.data_transformers.enable('json')

alt.Chart(df).mark_point().encode(
    x='Day',
    y='AvgTemperature')
```

I get the following:

![image](https://user-images.githubusercontent.com/7363923/80217734-1bbec880-8638-11ea-850c-fdd986626a48.png)

I can see the data being written to the json file in the local folder, and certainly nothing looks amiss in the json file when I inspect it. In the absence of any error messages I'm at a loss as to how to debug. Can anyone advise whether there's an issue or I'm doing something dumb?

**Comment by jakevdp** [comment] 2020-04-24 14:41
This is a duplicate of #1370.

The workaround is to disable the data transformer before saving.

**Closed by jakevdp** 2020-04-24 14:41 UTC

**Comment by d-gleeson** [comment] 2020-04-24 15:08
@jakevdp thanks for the quick reply! I've read the related issue (and those marked as related), it appears that most of the related issues only exhibit the issue when saving the charts, otherwise they display fine in the jupyter notebook. 
My issue is that the chart data doesn't appear either in the jupyter notebook or when saving. The only reason I'm using the data transformer is because my actual dataset is over 5k rows. I guess I should investigate altair_data_server to see if that will work.

**Comment by jakevdp** [comment] 2020-04-24 15:50
Ah, sorry I read your issue too quickly. I think you're probably seeing this issue: #1867 

I think altair_data_server is the right approach; I'm planning on removing the JSON data transformer from the docs for this reason.
