### ISSUE TITLE
save as svg changes fonts and margins

### ISSUE THREAD

**Issue by deisi** [altair-viz/altair#1954] opened 2020-02-07 10:31 UTC
saving a chart as svg with not default fontStyle and fontSize is troublesome. Here some example code:

```python
import pandas as pd
import altair as alt

df = pd.DataFrame([[1,2],[3, 4],[5,6]], columns=['A', "B"] )
c = alt.Chart(df).mark_point().encode(
    alt.X('A'),
    alt.Y('B')
)
c.save('default_works.svg')

# Now change the font size:
c = c.configure_axis(
        labelFontSize=20, labelFontWeight='normal', labelFontStyle='sans-serif', titleFont='sans-serif', titleFontWeight='normal'
)
c.save('buged.svg')
c.save('works.png')
c
```
The result is, that the buged.svg has overlapping text, while all other do not.

The altair version I use is 4.0.1 and selenium is 3.141.0 with firefox 72.0.0 and geckodriver 0.26.0

**Comment by jakevdp** [comment] 2020-02-07 14:42
Thanks for the report – this looks like a bug on the vega side.

**Comment by AAnzel** [comment] 2021-03-30 14:24
Confirmed and still relevant. This is also true for pdf extension. Font style persists only for png.

**Comment by joelostblom** [comment] 2022-03-23 00:47
The provided example is working for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.

**Closed by joelostblom** 2022-03-23 00:47 UTC
Labels: bug, vega-lite-related
