### ISSUE TITLE
TypeError: Object of type 'Timestamp' is not JSON serializable

### ISSUE THREAD

**Issue by scttnlsn** [altair-viz/altair#1355] opened 2019-03-02 15:30 UTC
Trying to make a chart with `pandas.Timestamp` on the X axis and a floating point value on the Y axis.

```python
alt.Chart(data).mark_line().encode(
    x='timestamp:T',
    y='value:Q'
)
```

I get the following error:

```
TypeError: Object of type 'Timestamp' is not JSON serializable
```

Tried various date/time methods described [here](https://altair-viz.github.io/user_guide/times_and_dates.html) but I always get this error.

**Comment by jakevdp** [comment] 2019-03-03 04:39
Can you show an example of code that leads to this error? I tried the following, and it works fine for me:
```python
import altair as alt
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'timestamp': [pd.Timestamp(2017, 1, i) for i in range(1, 31)],
    'value': np.random.randn(30).cumsum()
})

alt.Chart(data).mark_line().encode(
    x='timestamp:T',
    y='value:Q'
)
```

**Comment by scttnlsn** [comment] 2019-03-03 13:30
Hmm, I'm having a hard time reproducing the issue in a small example.  The data is setup more like this:

```python
timestamps = pd.DatetimeIndex(
    pd.Series([pd.Timestamp(2017, 1, i) for i in range(1, 31)], name='timestamp'),
    tz='UTC'
)

data = pd.DataFrame({
    'value': np.random.randn(30).cumsum()
}, index=timestamps)

alt.Chart(data).mark_line().encode(
    x='timestamp:T',
    y='value:Q'
)
```

But in this small case I just get an empty chart.

I've realized I can pull out the timestamp index and values into a separate dataframe for charting.  This works for me:

```python
chart = pd.DataFrame({
    'timestamp': data.index.values,
    'value': data.value.values
})

alt.Chart(chart).mark_line().encode(
    x='timestamp:T',
    y='value:Q'
)
```

(though the y-axis scale is not scaled properly in this case)

I'll keep poking around in my real code and see if I can make a small example that triggers the error.

Thanks!

**Comment by jakevdp** [comment] 2019-03-03 15:04
Regarding the index not being accessible to the chart; see https://altair-viz.github.io/user_guide/data.html#including-index-data

**Comment by jakevdp** [comment] 2019-03-03 15:18
Looking closer, I suspect the issue was that you have data of type "object" that contains timestamps. Here is a way to reproduce the error you report:
```python
import altair as alt
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'timestamp': pd.date_range('2017-01-01', freq='D', periods=30),
    'value': np.random.randn(30).cumsum()
})

alt.Chart(data).mark_line().to_json() # this works

data.timestamp = data.timestamp.astype(object)
alt.Chart(data).mark_line().to_json() # "Object of type 'Timestamp' is not JSON serializable"

data.timestamp = pd.to_datetime(data.timestamp)
alt.Chart(data).mark_line().to_json() # works again
```
Converting your object column to datetime is the way to fix the issue.

As to whether this should be fixed in Altair... I don't think so. Object arrays can contain arbitrary Python objects, the vast majority of which will not be JSON serializable. At some point it's up to the user to make certain the input data is valid.

**Comment by scttnlsn** [comment] 2019-03-03 15:43
I tried resetting the index and then converting the timestamp index series into a new datetime series:

```python

tmp = data.reset_index()
tmp['datetime'] = pd.to_datetime(tmp['index'])

alt.Chart(tmp).mark_line().encode(
    x='datetime:T',
    y='value:Q'
)
```

Getting the same error.

**Comment by scttnlsn** [comment] 2019-03-03 15:46
Here's the full stack trace FWIW:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/altair/vegalite/v2/api.py in to_dict(self, *args, **kwargs)
    400         copy = self.copy()
    401         original_data = getattr(copy, 'data', Undefined)
--> 402         copy.data = _prepare_data(original_data, context)
    403 
    404         if original_data is not Undefined:

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/altair/vegalite/v2/api.py in _prepare_data(data, context)
     90     # consolidate inline data to top-level datasets
     91     if data_transformers.consolidate_datasets:
---> 92         data = _consolidate_data(data, context)
     93 
     94     # if data is still not a recognized type, then return

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/altair/vegalite/v2/api.py in _consolidate_data(data, context)
     57 
     58     if values is not Undefined:
---> 59         name = _dataset_name(values)
     60         data = core.NamedData(name=name, **kwds)
     61         context.setdefault('datasets', {})[name] = values

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/altair/vegalite/v2/api.py in _dataset_name(values)
     33     if isinstance(values, core.InlineDataset):
     34         values = values.to_dict()
---> 35     values_json = json.dumps(values, sort_keys=True)
     36     hsh = hashlib.md5(values_json.encode()).hexdigest()
     37     return 'data-' + hsh

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'Timestamp' is not JSON serializable
```

**Comment by scttnlsn** [comment] 2019-03-03 15:56
Ahh, I had some other columns that were of type `object` and dropping those resolves the error.  I was not aware that unused columns would cause an issue like that.  Thanks for you help!

**Closed** 2019-03-03 15:56 UTC

**Comment by jakevdp** [comment] 2019-03-03 19:38
Yeah, altair will serialize the entire dataset that you build a chart with, because it's difficult to determine from the Python side which columns the renderer will reference.

Glad the problem is fixed!

**Comment by jowens** [comment] 2020-04-27 16:50
For debugging purposes (e.g., a dataframe with a very very large number of columns), is it possible to have that error message print the name of the column as well?

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181
```
