### ISSUE TITLE
Any way to sort two layers together?

### ISSUE THREAD

**Issue by Ram-N** [altair-viz/altair#820] opened 2018-05-06 03:08 UTC
I have a sorted `mark_bar()` and would like to add a layer of `mark_tick` or top of this, *while preserving* the sorted order.

This sorting works:

```
from vega_datasets import data
df = data.movies()
df['WW_Margin'] = (df['Worldwide_Gross'] - df['Production_Budget']) / 1e6
  
lower_box = 'q1(WW_Margin):Q'
upper_box = 'q3(WW_Margin):Q'

bar_plot = alt.Chart(df).mark_bar(size=5.0).encode(
    alt.X('Major_Genre:O',
#          sort=alt.SortField(field='WW_Margin', op='median', 
#                             order='descending')
         ),
    y=lower_box,
    y2=upper_box,
)

median_tick = bar_plot.mark_tick(
    color='white',
    size=5.0
).encode(
    y='median(WW_Margin):Q',
)

bar_plot
```

![image](https://user-images.githubusercontent.com/737241/39669356-6d7b08b8-509e-11e8-8b85-4293c26c6cf7.png)

But when I add a mark_tick layer, the sorting or the bars is gone, and it reverts to alphabetical sorting.

```
from vega_datasets import data
df = data.movies()
df['WW_Margin'] = (df['Worldwide_Gross'] - df['Production_Budget']) / 1e6
  
lower_box = 'q1(WW_Margin):Q'
upper_box = 'q3(WW_Margin):Q'

bar_plot = alt.Chart(df).mark_bar(size=5.0).encode(
    alt.X('Major_Genre:O',
          sort=alt.SortField(field='WW_Margin', op='median', 
                             order='descending')
         ),
    y=lower_box,
    y2=upper_box,
)

median_tick = bar_plot.mark_tick(
    color='white',
    size=5.0
).encode(
    y='median(WW_Margin):Q',
)

bar_plot + median_tick #note below that sorting is gone
```
![image](https://user-images.githubusercontent.com/737241/39669389-43595cdc-509f-11e8-8076-ba2cf149acaf.png)

This is quite possibly related to #698 which in turn refers to a Vega-lite issue(vega/vega-lite#2177). Will this get resolved when a newer version of Vega-lite is incorporated into Altair? Thanks much.

**Comment by jakevdp** [comment] 2018-05-06 05:28
I think this is a bug in vega-lite; I've opened an issue there: https://github.com/vega/vega-lite/issues/3710

**Comment by jakevdp** [comment] 2018-05-06 05:59
Looks like it's still an unfixed bug in Vega. As a workaround, you can set ``resolve/scale/x`` to ``"independent"`` and then turn off the second set of axis labels:

```python
import altair as alt
alt.themes.enable('none')

from vega_datasets import data

sort = alt.SortField(field='WW_Margin', op='median', 
                             order='descending')

bars = alt.Chart().mark_bar(size=5.0).encode(
    alt.X('Major_Genre:N', sort=sort),
    y='q1(WW_Margin):Q',
    y2='q3(WW_Margin):Q'
)

ticks = alt.Chart().mark_tick(
    color='black',
    size=5.0
).encode(
    alt.X('Major_Genre:N', sort=sort, axis=alt.Axis(labels=False, ticks=False)),
    y='median(WW_Margin):Q',
)

alt.layer(bars, ticks, data=data.movies.url).transform_calculate(
    WW_Margin = "(datum.Worldwide_Gross - datum.Production_Budget) / 1e6"
).resolve_scale(x='independent')
```
![visualization 14](https://user-images.githubusercontent.com/781659/39670361-dce6532e-50b7-11e8-85dd-cd5b06391ae3.png)

**Comment by Ram-N** [comment] 2018-05-06 06:03
`.resolve_scale(x='independent')` is a good work-around. Thanks much.

**Comment by Alcampopiano** [comment] 2018-07-23 20:39
Hi all,

Here is a workaround in case it helps. It turns out that if you sort your data values first (`df.sort_values...`), and then specify the usual sort options in Altair (`op...field...order`), the data will be sorted (at least in the example linked below):

https://github.com/vega/vega-lite/issues/4075

**Comment by jakevdp** [comment] 2019-05-27 13:52
This is fixed in Altair 3:
```python
from vega_datasets import data
df = data.movies()
df['WW_Margin'] = (df['Worldwide_Gross'] - df['Production_Budget']) / 1e6
  
lower_box = 'q1(WW_Margin):Q'
upper_box = 'q3(WW_Margin):Q'

bar_plot = alt.Chart(df).mark_bar(size=5.0).encode(
    alt.X('Major_Genre:O',
          sort=alt.EncodingSortField(field='WW_Margin', order='descending')
         ),
    y=lower_box,
    y2=upper_box,
)

median_tick = bar_plot.mark_tick(
    color='white',
    size=5.0
).encode(
    y='median(WW_Margin):Q',
)

bar_plot + median_tick
```
![visualization - 2019-05-27T065145 431](https://user-images.githubusercontent.com/781659/58424257-e686b080-804b-11e9-8516-9f9f40eef21b.png)

**Closed by jakevdp** 2019-05-27 13:52 UTC
Labels: vega-lite-related

**Comment by 77QingLiu** [comment] 2019-10-09 10:22
mixed order when two plots are combined
![image](https://user-images.githubusercontent.com/32193271/66473313-94599f80-eac1-11e9-8735-5f081bf6beb8.png)

the bar plot and line plot order right in the single plot, but mixed when combined

```
alt.layer(
    bar,
    line
).resolve_scale(
    y='independent'
)
```

**Comment by jakevdp** [comment] 2019-10-09 13:00
if you want a solution to your problem please include the full code to reproduce your chart.

**Comment by 77QingLiu** [comment] 2019-10-09 23:01
@jakevdp here is full code
```python
# %%
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.3f}'.format

# %%
df = pd.DataFrame(
{'group': ['a', 'b', 'c'],
 'value1': [3723189706, 511785521, 448873396],
 'value2': [1471506853, 261248709, 226229611],
 'ratio': [0.3952274716265022, 0.5104652220662801, 0.5039942516577337]}
)

# %%
import altair as alt
alt.renderers.enable('nteract')

df_stack = df.melt(id_vars='group', value_vars=['value1', 'value2'])

labels = ['a', 'c', 'b']
bar = alt.Chart(df_stack).mark_bar().encode(
    alt.X('group:O', sort=labels),
    alt.Y('value:Q'),
    alt.Color('variable', legend=alt.Legend(title="类型"))
)

line =  alt.Chart(df).mark_line(color='red').encode(
    alt.X('group:O', sort=labels),
    alt.Y('ratio:Q', axis=alt.Axis(format='%'))
)

alt.layer(
    bar,
    line
).resolve_scale(
    y='independent'
).properties(
width=600
).configure_axisX(
labelAngle=-45
)

```

below is the output, the order is not the same as specified in sort option
![image](https://user-images.githubusercontent.com/32193271/66526574-cb649b00-eb2b-11e9-821d-05b874533679.png)

**Comment by jakevdp** [comment] 2019-10-10 15:41
The order of the axis and the order in which the points are connected are distinct concepts. If you want to change the order in which the points are connected, you can use the ``order`` channel. Details in the docs here: https://altair-viz.github.io/user_guide/encoding.html#ordering-marks

**Comment by jakevdp** [comment] 2019-10-10 15:43
Also, ordering of axis for layered charts based on different datasets is still not supported (open the javascript console and you'll see the relevant warnings output by Vega-Lite). You'll need to source both charts from the same dataset if you want the orders to be propagated to the layered chart.

**Comment by quantoid** [comment] 2024-01-02 07:01
The sorting issue still occurs in Altair 5.2.0 on layered charts where `sort="-x"` is used to sort the y-axis to get highest x-value at the top.
