### ISSUE TITLE
adding radio selector to a layered plot results in error: 'data' is a required property

### ISSUE THREAD

**Issue by mchoi1031** [altair-viz/altair#1604] opened 2019-07-10 22:27 UTC
i'm creating a layered chart which consists of 2 charts.  after adding a radio button selector, the chart throws a "data is a required property" error.  in other threads, a solution was to move where data is specified, but in my situation this didn't work.  my situation doesn't have any facet charts.
i'm using v3.1.0

here are some trials with results:
```
# trial 1

chart_alt = alt.Chart()

month_bars = chart_alt.mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y...., color.....)

month_line = chart_alt.mark_line(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x..., y...)

combo_chart = alt.layer(month_bars, month_line, data=df_something)
# combo_chart comes up properly

chart_radio = alt.binding_radio(options = list_options)
radio_select = alt.selection_single(fields = ['options'],
                                     bind = chart_radio,
                                     name = 'Select')
filter_select = combo_chart.add_selection(radio_select).transform_filter(radio_select)
filter_select

# throws error
# SchemaValidationError: Invalid specification
#        altair.vegalite.v3.api.Chart, validating 'required'
#        'data' is a required property
```

```
# trial 2

# specify df_something only in the base chart
chart_alt = alt.Chart(df_something)

# throws same error
```
```
# trial 3

# specify df_something in properties of each layer and no place else

month_bars = chart_alt.mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y...., color....
).properties(data = df_something)

month_line = chart_alt.mark_line(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y....
).properties(data = df_something)

# throws same error
```

none of these work either:
```
# only use 1 layer
combo_chart = alt.layer(month_bars, data=df_something)
# throws same error

# use vconcat
combo_chart = alt.vconcat(month_bars, month_line, data=df_something)
combo_chart = alt.vconcat(month_bars, data=df_something)
# throws same error
```

this works:
```
month_bars = chart_alt.mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y...., color....
).properties(data = df_something)

filter_select = month_bars.add_selection(radio_select).transform_filter(radio_select)
filter_select

# properly displays single bar chart with radio buttons
```

this also works:
```
chart_alt = alt.Chart(df_something)

# bars OR line both work
month_bars = chart_alt.mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y...., color...)

# bars OR line both work
filter_select = month_bars.add_selection(radio_select).transform_filter(radio_select)
filter_select

# properly displays single line OR bar chart with radio buttons
```

does anyone know what's wrong?

i'm really new to altair, so it's completely possible that i'm missing something basic.

my goal is to have a combo bar + line chart with a radio selector which will update both bar+line at the same time.

thanks in advance for any help.

**Comment by jakevdp** [comment] 2019-07-10 23:14
I think the issue is that you cannot add a selection to a layered chart; the selection must be added to one of the component charts:
```python
chart = alt.layer(
    alt.Chart().mark_point(),
    alt.Chart().mark_point(),
    data='data.csv'
)
spec = chart.to_dict() # no issue

#---

chart = chart.add_selection(
    alt.selection_single()
)
spec = chart.to_dict() # SchemaValidationError: data is a required property

#---

chart = alt.layer(
    alt.Chart().mark_point().add_selection(alt.selection_single()),
    alt.Chart().mark_point(),
    data='data.csv'
)
spec = chart.to_dict() # no issue
```

Add the selection to one of the component charts, and your problem should be resolved.

The error would be much more clear if we were to remove the ``add_selection`` method from the ``LayerChart`` object. I'm going to mark this as a bug.

**Comment by jakevdp** [comment] 2019-07-10 23:45
This is one of several methods that should be removed from the API; see #1605

**Comment by mchoi1031** [comment] 2019-07-11 21:39
Thanks so much for the help, @jakevdp 

The chart properly comes up as a combo with selections.

In order to get the selections to apply to both charts, I had to modify the code a bit.

Here's what it looks like:
```
month_bars = alt.Chart().mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x...., y...., color.....)

month_line = alt.Chart().mark_line(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x..., y...)

chart_radio = alt.binding_radio(options = list_options)
radio_select = alt.selection_single(fields = ['options'],
                                     bind = chart_radio,
                                     name = 'Select')
filter_select = month_bars.add_selection(radio_select).transform_filter(radio_select)
filter_select2 = month_line.transform_filter(radio_select)
#####
# it'll work regardless of which chart the ".add_selection" is linked to...
# ...in my case i coded it to the bar chart
#####

combo_chart = alt.layer(filter_select, filter_select2, data=df_something).resolve_scale(y='independent')
combo_chart
# success
# combo chart, bar & line charts, independent y axis for each 
# with radio button selectors which updates both charts.
```

shall i mark as closed?

**Comment by mchoi1031** [comment] 2019-07-12 02:59
Not sure if this should be a new topic:
I've added a brush interval selector which ends up not doing anything.

```
# add interval selector
brush = alt.selection(type = 'interval', encodings = ['x'])

# for each chart in the combo, change scale to domain = brush
month_bars = alt.Chart().mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x = alt.X(........ scale = alt.Scale(domain = brush),
 y...., color.....)
month_line = alt.Chart().mark_line(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x = alt.X(........ scale = alt.Scale(domain = brush)
, y...)

# still have same radio button selector as before, not gonna copy all code
# brush is added to the line chart
filter_select = month_bars.....
filter_select2 = month_line.add_selection(brush, radio_select
).transform_filter(radio_select)

combo_chart = alt.layer(filter_select, filter_select2, data=df_something
).resolve_scale(y='independent')

# create the smaller lower chart which contains the interval brush selector
lower = combo_chart.properties(height = 60)

combo_chart_all = alt. vconcat(combo_chart, lower)

combo_chart_all
# allows brush interval selection, but doesn't update anything
```

i'm not sure why the interval brush doesn't do anything.

is it because i have a transform_filter applied for the radio selector only?  as in....do i need to code another transform filter to handle the interval brush?

**Comment by jakevdp** [comment] 2019-07-12 03:06
It's quite difficult to guess what you're seeing without a complete code snippet. Could you include a full example?

**Comment by mchoi1031** [comment] 2019-07-12 19:06
@jakevdp sure thing

```
# create the brush interval selector
brush = alt.selection(type = 'interval', encodings = ['x'])

# for each chart in the combo, change scale to domain = brush
month_bars = alt.Chart().mark_bar(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x = alt.X(........ scale = alt.Scale(domain = brush),
 y...., color.....)
month_line = alt.Chart().mark_line(
).transform_filter(alt.FieldOneOfPredicate(field = 'options', oneOf = list_options)
).encode(x = alt.X(........ scale = alt.Scale(domain = brush)
, y...)
# kinda a bummer because i wanted the domain to stay the same
# between radio button filter selections
# not sure if i'm going to delve deeper into a customization for that or not

# create the radio button selection
chart_radio = alt.binding_radio(options = list_options)
radio_select = alt.selection_single(fields = ['options'],
                                     bind = chart_radio,
                                     name = 'Select')
# brush is added to the bar chart
# should also work if they're added to line chart i think
filter_select = month_bars.add_selection(brush, radio_select).transform_filter(radio_select)
filter_select2 = month_line.transform_filter(radio_select)

# create a combo chart which is a layered chart consisting of the bar and line chart
# with independent y axis
combo_chart = alt.layer(filter_select, filter_select2, data=df_something
).resolve_scale(y='independent')

# create the smaller lower chart which contains the interval brush selector
lower = combo_chart.properties(height = 60)

# create a vconcat of the combo chart and the smaller lower chart
combo_chart_all = alt. vconcat(combo_chart, lower)

combo_chart_all
# charts come up. and a brush interval selection comes up too.....
#  ..., but the interval doesn't update anything in the combo_chart
```

i've attached a snip of the output below.  as you can see, i can use the brush interval selection, but it's not updating the upper chart (you can tell b/c the scales are completely the same).
on the bright side, it didn't break the radio button selector; it still works fine.
![combo chart pic](https://user-images.githubusercontent.com/21087019/61152437-7080c080-a4b6-11e9-9893-53759ca23008.PNG)


do you think others would be interested in this type of chart?  if so, i'm willing to help write a tutorial for what i accomplish/accomplished

**Comment by jakevdp** [comment] 2019-07-12 20:26
I meant a full example that I could execute (i.e. replace all the `......` with the actual code)

**Comment by jakevdp** [comment] 2019-07-12 20:28
In other words, please include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by mchoi1031** [comment] 2019-07-13 00:09
updated above as requested.

**Comment by mchoi1031** [comment] 2019-07-16 17:36
sorry to bump, @jakevdp have you had a chance to look at this?

if this isn't an available feature, i can just forgo the brush interval selector.

**Comment by jakevdp** [comment] 2019-07-16 17:49
Your code does not execute for me: ``list_options`` and ``df_something`` are undefined.

**Comment by jakevdp** [comment] 2019-07-16 17:50
I tried to guess reasonable values for them, but it's not clear what your intent is for the data.

**Comment by mchoi1031** [comment] 2019-07-16 21:07
here are some random values for the dataframe and list_options
sorry, i can't provide the actual data.

```
data = { 'test_date': ['2017-02-01', '2017-02-01', '2017-02-01','2017-03-10', '2017-03-10', '2017-03-10'],
         'options': ['firstplace', 'firstplace', 'secondplace', 'secondplace', 'firstplace', 'firstplace'],
         'categories': ['good', 'bad', 'bad', 'bad', 'good', 'good'],
         'number': [2,4,5,3,4,1]}
df_something = pd.from_dict(data)
df_something['test_date'] = pd.to_datetime(df_something['test_date'])

list_options = ['firstplace', 'secondplace']
```

**Comment by jakevdp** [comment] 2019-07-16 21:54
When I run the script with those inputs, I get the following:
```
JavaScript Error: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```
JavaScript Error: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

---


If you want a chance of getting a useful answer to your question, I'd suggest you create a self-contained example script, including all imports, data, and function arguments, and test it by pasting the script in a new notebook and making certain it demonstrates the behavior you're asking about. The more I have to guess about what you're seeing, the less likely I will be able to help you with your problem.

**Comment by jakevdp** [comment] 2019-07-16 21:59
It also is helpful to spend a bit of effort to minimize your code. For example, can you still reproduce this issue if you use a smaller dataset and remove the filter statements? I suspect you can.

**Comment by jakevdp** [comment] 2019-07-16 22:00
There's a lot of good info on how to ask questions in a way that makes them more likely to get an answer here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mchoi1031** [comment] 2019-07-17 03:17
my bad.  I'm new to this.  I'm not trying to waste your time.
I swear the below works.  I put it in a new notebook and ran it to be sure.

It turns out that the reason for the 'set attribute' error is that 'field' cannot be "options".  Dunno why, but if I change the name of the column from "options", it works.  Maybe this is another bug.

```
import pandas as pd
import numpy as np
import altair as alt
import datetime

data = { 'test_date': ['2017-02-01', '2017-02-01', '2017-02-01','2017-03-10', '2017-03-10', '2017-03-10'],
         'place': ['firstplace', 'firstplace', 'secondplace', 'secondplace', 'firstplace', 'firstplace'],
         # this column is now called "place", but used to be called "options"
         # the column name "options" caused a setattribute error.  see below.
         'categories': ['good', 'bad', 'bad', 'bad', 'good', 'good'],
         'number': [2,4,5,3,4,1]}
df_something = pd.DataFrame.from_dict(data)
df_something['test_date'] = pd.to_datetime(df_something['test_date'])

place_options = ['firstplace', 'secondplace']

# create the brush interval selector
brush = alt.selection(type = 'interval', encodings = ['x'])

# for each chart in the combo, change scale to domain = brush
month_bars = alt.Chart().mark_bar(
    ).transform_filter(alt.FieldOneOfPredicate(field = 'place', oneOf = place_options)
                       # using field = 'options' if the column name is 'options',
                       # this will result the following error:
                       # 'setAttribute' on 'Element': '0' is not a valid attribute name
                       # maybe this is a bug???
    ).encode(x = alt.X('yearmonth(test_date):T',
                       scale = alt.Scale(domain=brush)),
             y = alt.Y('sum(number):Q'),
             color = alt.Color('categories', type = 'ordinal')
    ).add_selection(brush)
month_line = alt.Chart().mark_line(
    ).transform_filter(alt.FieldOneOfPredicate(field = 'place', oneOf = place_options)
                       # using field = 'options' if the column name is 'options',
                       # this will result the following error:
                       # 'setAttribute' on 'Element': '0' is not a valid attribute name
                       # maybe this is a bug???
    ).encode(x = alt.X('yearmonth(test_date):T',
                       scale = alt.Scale(domain=brush)),
                   y = alt.Y('sum(number):Q')
    )
# kinda a bummer because i wanted the domain to stay the same
# between radio button filter selections
# not sure if i'm going to delve deeper into a customization for that or not

# create the radio button selection
chart_radio = alt.binding_radio(options = place_options)
radio_select = alt.selection_single(fields = ['place'],
                                    bind = chart_radio,
                                    name = 'select')

# brush is added to the bar chart
# should also work if they're added to line chart i think
filter_select = month_bars.add_selection(brush, radio_select).transform_filter(radio_select)
filter_select2 = month_line.transform_filter(radio_select)

# create a combo chart which is a layered chart consisting of the bar and line chart
combo_chart = alt.layer(filter_select, filter_select2, data=df_something)

# create the smaller lower chart which contains the interval brush selector
lower = combo_chart.properties(height = 60)
# using .add_selection(brush) here results in error: 'data' is a required property

# create a vconcat of the combo chart and the smaller lower chart
combo_chart_all = alt.vconcat(combo_chart, lower)

combo_chart_all
# charts come up. and a brush interval selection comes up too.....
#  ..., but the interval doesn't update anything in the combo_chart
```


screenshot of result:
![Capture2](https://user-images.githubusercontent.com/21087019/61344546-9cd26f00-a81f-11e9-909d-2deea7c212a0.PNG)

summary of result:
-  this produces 2 charts (a combo bar + line chart) and a smaller chart (the brush interval selector chart).
-  brush highlighting and selecting will produce a gray box, but will not update either chart.  the interval selection is coded as an x-axis selection.
-  this also produces a radio button selector which correctly updates the charts if a "place" is selected.

the goal:
-  2 charts (a combo bar + line chart) and a smaller chart (the brush interval selector chart)
-  brush interval selecting the smaller chart will update the combo chart as you select an interval.  the update will be zooming/panning along the temporal x-axis.
-  also, a radio button selector is needed to update the charts if a "place" is selected (this works correctly).

**Comment by jakevdp** [comment] 2019-07-17 05:14
I think the problem is that you stacked two copies of the filter chart on top of each other: you can't use a selection on a chart to resize the chart on which you're selecting. If you change ``alt.vconcat(combo_chart, lower)`` to ``alt.vconcate(month_bars + month_lines, lower, data=df_something)``, you'll get something closer to what you're looking for.

**Comment by jakevdp** [comment] 2019-07-17 05:15
Also, this:
```
# using .add_selection(brush) here results in error: 'data' is a required property
```
is a bug that was fixed by #1607

**Comment by mchoi1031** [comment] 2019-07-17 19:41
Thanks for the help @jakevdp 

I got it working (code below).

I moved the radio button selectors to the base chart code for both bar and line charts.

I then added the brush interval selector to a single chart and called it once during creation.  As you said, my mistake earlier was calling it twice and stacking it.


```
import pandas as pd
import numpy as np
import altair as alt
import datetime

data = { 'test_date': ['2017-02-01', '2017-02-01', '2017-02-01','2017-03-10', '2017-03-10', '2017-03-10'],
         'place': ['firstplace', 'firstplace', 'secondplace', 'secondplace', 'firstplace', 'firstplace'],
         # this column is now called "place", but used to be called "options"
         # the column name "options" caused a setattribute error.  see below.
         'categories': ['good', 'bad', 'bad', 'bad', 'good', 'good'],
         'number': [2,4,5,3,4,1]}
df_something = pd.DataFrame.from_dict(data)
df_something['test_date'] = pd.to_datetime(df_something['test_date'])

place_options = ['firstplace', 'secondplace']



# create the brush interval selector
brush = alt.selection(type = 'interval', encodings = ['x'])

# for each chart in the combo, change scale to domain = brush
month_bars = alt.Chart().mark_bar(
    ).transform_filter(alt.FieldOneOfPredicate(field = 'place', oneOf = place_options)
                       # using field = 'options' if the column name is 'options',
                       # this will result the following error:
                       # 'setAttribute' on 'Element': '0' is not a valid attribute name
                       # maybe this is a bug???
    ).encode(x = alt.X('yearmonth(test_date):T',
                       scale = alt.Scale(domain=brush)),
             y = alt.Y('sum(number):Q'),
             color = alt.Color('categories', type = 'ordinal')
    ).add_selection(radio_select).transform_filter(radio_select)
    # added selection and transform filter for the radio buttons here
    
month_line = alt.Chart().mark_line(
    ).transform_filter(alt.FieldOneOfPredicate(field = 'place', oneOf = place_options)
                       # using field = 'options' if the column name is 'options',
                       # this will result the following error:
                       # 'setAttribute' on 'Element': '0' is not a valid attribute name
                       # maybe this is a bug???
    ).encode(x = alt.X('yearmonth(test_date):T',
                       scale = alt.Scale(domain=brush)),
                   y = alt.Y('sum(number):Q')
    ).transform_filter(radio_select)
    # added transform filter for the radio buttons here too
    # can also put the add selection here....either chart, but not both at the same time

# kinda a bummer because i wanted the domain to stay the same
# between radio button filter selections
# not sure if i'm going to delve deeper into a customization for that or not

# create the radio button selection
chart_radio = alt.binding_radio(options = place_options)
radio_select = alt.selection_single(fields = ['place'],
                                    bind = chart_radio,
                                    name = 'select')

# brush is added to the bar chart
# it'll also work if it's added to line chart...either chart, but not both at the same time
filter_select = month_bars.add_selection(brush)

# create a combo chart which is a layered chart consisting of the bar and line chart
# the charts called are the base charts with radio selectors only
combo_chart = alt.layer(month_bars, month_line)

# create the smaller lower chart which contains the interval brush selector
# instead of calling the base chart, call the chart with the brush selector
# then add the other chart
lower = alt.layer(filter_select, month_line).properties(height = 60)

# create a vconcat of the combo chart and the smaller lower chart
combo_chart_all = alt.vconcat(combo_chart, lower, data = df_something)

combo_chart_all
# successfully creates a combo bar+line chart that updates based on a brush interval selector
#     selected in the lower, smaller chart.
# also, both charts update through radio button selectors
```

Jake - I greatly appreciate you helping me with this.  To give you an idea of what you're helping with (...if you're at all interested) we can probably chat elsewhere about this viz project.

**Comment by jakevdp** [comment] 2019-07-17 20:05
Great! Glad you got it working. Sorry for all the back-and-forth.

**Closed by jakevdp** 2019-07-17 20:05 UTC
Labels: question
