### ISSUE TITLE
oneOf on selection

### ISSUE THREAD

**Issue by EntilZha** [altair-viz/altair#2366] opened 2020-12-08 23:05 UTC
Hi, I'm trying to adapt the parallel coordinates plot with some interaction. I've been working at a minimal example here https://colab.research.google.com/drive/1qMMX5VfFpG0zxBvtHVvxhIS57LHZH_nt?usp=sharing

My goal is to be able to draw a selection box around some of the points and have all the lines/points with the same index be colored and everything else be grayed out. The image below shows that this sort of works, but only because the line is considered selected if its starting point is selected (and subsequent points with same index aren't selected). It breaks down when you select points in the middle.

![image](https://user-images.githubusercontent.com/1382460/101551754-921dfa00-397f-11eb-980e-8d2fc0f91971.png)
![image](https://user-images.githubusercontent.com/1382460/101551776-9cd88f00-397f-11eb-9023-8fc8d55ca370.png)

The thing I can't seem to figure out is how to do this: create a brush selection based on the key/value axes -> create a set of index numbers -> set the color condition on these. Any suggestions on how to do this?

I tried using oneOf with something like `FieldOneOfPredicate('index', brush.index)`, but get the feeling this isn't valid and its expected that the list of options is a static list. The only approach I can think of so far that might work is having a shadow set of points + transform_filters that create colored/non-colored sets of points/lines, which seems a bit messy. Thanks!

**Comment by jakevdp** [comment] 2020-12-08 23:49
There's not a great way to do this, unfortunately. You may be able to get something to work with a **very** complicated condition defined as a vega expression, but I'm not sure how I would do that.

The issue is that interval selections can only trigger on x and y encodings. And so the only information you have about an interval selection is [min_x, max_x, min_y, max_y]. This means you'd have to write an expression that takes that information and detects whether any row of the data with the same index contains an (x, y) in that interval, and condition its color accordingly.

**Comment by jakevdp** [comment] 2020-12-09 00:46
OK, I thought about it some more, and I think this is probably the most straightforward way to accomplish this currently:
```python
import altair as alt
from vega_datasets import data

brush = alt.selection_interval(name='brush')

base = alt.Chart(data.iris()).transform_window(
    index='count()'
).transform_fold(
    ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth']
).transform_calculate(
    selected=("(indexof(brush.key || [], datum.key) >= 0) &&"
              "(brush.value && brush.value[0] <= datum.value) &&"
              "(datum.value <= brush.value[1])")
).transform_joinaggregate(
    selected="sum(selected)", groupby=["index"]
).encode(
    x='key:N',
    y='value:Q',
    color=alt.condition("datum.selected > 0", 'species:N', alt.value('lightgray')),
    detail='index:N',
).properties(width=500)

alt.layer(
  base.mark_line(opacity=0.5),
  base.mark_point().add_selection(brush)
)
```

**Comment by EntilZha** [comment] 2020-12-09 15:46
Thanks for the explanation and working code! There are a few other plots I've done where I've wanted to synchronize selections based on attributes not in the selection, so this should help in those cases too.

On a meta note, do you have suggestions for a tutorial on expressions (I've looked through API references, but its more of a... reference than a guide)? I wasn't aware thats how selections worked and knowing about available functions/syntax/semantics would be helpful.

**Comment by jakevdp** [comment] 2020-12-09 17:01
No, I don't know of any really good guide unfortunately. The API reference here is probably the most helpful thing: https://vega.github.io/vega/docs/expressions/

**Comment by joelostblom** [comment] 2021-02-22 22:27
@EntilZha I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by jbloom** [comment] 2021-04-02 17:02
@jakevdp, I'm wondering if you can generalize your explanation to the case where we aren't trying to select a windowed case?

In particular, I have a `selection_multi` object, say called `sel`. And I want to see if the data is in the selection and then act accordingly. So if I just know there is one item in the selection, I can use a `transform_calculate` string like this:
```
if(datum.site == sel.site[0], 1, 0)
```
But now what if there are actually **two** sites selected in the `sel.site`? I guess I could do something like
```
if(datum.site == sel.site[0] | datum.site == sel.site[1], 1, 0)
``` 

But I'd like to generate this to the arbitrary case:
```
if(datum.site in sel.site, 1, 0)
```
Except this doesn't work, presumably because `in` is not a valid operation here.

Importantly, I can't just do a `transform_filter` because I want to calculate a different value depending on whether or not the site is selected.

**Comment by jakevdp** [comment] 2021-04-02 17:08
You can do this using the [`indexOf`](https://vega.github.io/vega/docs/expressions/#indexof) vega expression, which I believe returns `-1` if the value is not in the array.

**Comment by jbloom** [comment] 2021-04-02 17:28
That works great, thanks so much for the quick response!

**Comment by joelostblom** [comment] 2022-03-23 01:27
Closing for now, please reopen if there is anything that wasn't resolved solutions provided above.

**Closed by joelostblom** 2022-03-23 01:27 UTC
Labels: question
