### ISSUE TITLE
Stacked bar chart rendering bug in the presence of negative values

### ISSUE THREAD

**Issue by drkjam** [altair-viz/altair#297] opened 2017-02-08 17:22 UTC
Hi,

Really enjoying Altair but I've run into a bug when attempt to display stacked bars, some of which contain negative values.

Here is a minimal test case that demonstrates the problem.

```
import pandas as pd
from altair import Chart

data = pd.DataFrame({'amount': [-2000, 3000, 2000, 4000, 3000, 5000, 1000, 2000],
 'quarter': ['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q1', 'Q1'],
 'type': ['N', 'C', 'N', 'C', 'N', 'C', 'N', 'C'],
 'year': [2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017]})

Chart(data).mark_bar().encode(
    color='type:N',
    column='quarter:O',
    x='year:N',
    y='sum(amount):Q',
)
```
Which produces this view:

![altair_stacked_bar1](https://cloud.githubusercontent.com/assets/93508/22748495/2a0d1e16-ee22-11e6-9073-1f1d6bafa756.png)

If you remove the `sum()` aggregation from the `y` axis, the negative values are displayed but you lose the stacking.

```
Chart(data).mark_bar().encode(
    color='type:N',
    column='quarter:O',
    x='year:N',
    y='amount:Q',
)
```

Which looks like this:

![altair_stacked_bar2](https://cloud.githubusercontent.com/assets/93508/22748591/755c3a14-ee22-11e6-9010-f145d0ba1fa8.png)

Anyone else run into this issue?

**Comment by kanitw** [comment] 2017-02-08 18:18
Hi, 

Thanks for reporting. However, this is not a bug.

Semantically, stack bar chart shows the "sum" of non-negative values, so it should only work if you use summable aggregation (sum, count, distinct, ...).

If you have negative values, you cannot use stack bar chart without running into problems.  
(For example, if you have 1D stacked bar with two values, -20 and 20 and thus the sum is zero. 
It's impossible to show that there are two subgroups that adds up to zero overall.)

**Comment by kanitw** [comment] 2017-02-08 18:20
Btw, in the future, we might add better warning about this to help users understand encoding limitations for data with negative values better https://github.com/vega/vega-lite/issues/1833

**Comment by drkjam** [comment] 2017-02-09 09:44
Are you sure this is not a bug? Here is the expected view generated correctly in Tableau using the same data.

![tableau_stacked_bar2](https://cloud.githubusercontent.com/assets/93508/22777618/b15c90fc-eeab-11e6-98cf-581c3c793cf0.png)

**Comment by jheer** [comment] 2017-03-16 18:54
The latest version of Vega (3.0.0-beta.26) has an updated stack transform that can properly handle negative numbers. As a result, Vega-Lite 2.0 will ultimately "do the right thing" here.

**Comment by ellisonbg** [comment] 2017-04-19 15:00
Thanks @jheer and @kanitw for the clarification. Closing as question/vega-lite

**Closed by ellisonbg** 2017-04-19 15:00 UTC
