### ISSUE TITLE
Interactive charts don't show correct result on load (but refresh after interaction)

### ISSUE THREAD

**Issue by stsievert** [altair-viz/altair#599] opened 2018-03-17 18:37 UTC
I've noticed that various interactive elements don't render on load. This is best explained by an example ([US Population over time], copy/pasted from docs):

[US Population over time]:https://altair-viz.github.io/gallery/us_population_over_time.html

<img src="https://user-images.githubusercontent.com/1320475/37558785-66132582-2a11-11e8-92e8-d7ba84e0c8d8.gif" width="500">

Here's screenshots of before and after I move the slider around (and leaving it in the same place it started):

| Before | After |
| :--:|:--:|
|  <img width="773" alt="screen shot 2018-03-17 at 12 27 13 pm" src="https://user-images.githubusercontent.com/1320475/37558233-a56db462-2a08-11e8-9444-4c9ac07698b9.png"> | <img width="773" alt="screen shot 2018-03-17 at 12 27 26 pm" src="https://user-images.githubusercontent.com/1320475/37558236-a94a4ba4-2a08-11e8-986d-1c159d3b4983.png"> |

I'm on Altair 2.0.0rc1

**Comment by jakevdp** [comment] 2018-03-17 19:45
Yes, I've noticed this too. It has to do with the fact that in Vega-Lite selections start out empty, and so the slider doesn't take effect until you move it. The only options for an empty selection are "none" or "all", neither of which really fixes this issue.

Maybe @domoritz or @kanitw have ideas... when selections have bindings like the slider here, is there a way to initialize them such that they're consistent with the default state of the binding?

**Comment by jheer** [comment] 2018-03-17 20:17
Paging @arvind who implemented the selections framework.

**Comment by jakevdp** [comment] 2018-08-20 01:49
This is still an issue... and major enough that each time I try to start writing docs for bindings in altair I give up because they're essentially unusable in their current state.

Would it be worth opening a bug in Vega-Lite to track this more effectively?

**Comment by arvind** [comment] 2018-08-20 01:52
Hi @jakevdp, we're tracking this issue as vega/vega-lite#3409 and vega/vega-lite#3431. I'll prioritize it and aim to have something land soon. Sorry about the frustration.

**Comment by jakevdp** [comment] 2018-08-20 02:03
Thanks!

**Comment by joelostblom** [comment] 2021-02-23 23:32
This is working as intended in the latest version of Altair so closing this issue.

**Closed by joelostblom** 2021-02-23 23:32 UTC
Labels: bug, vega-lite-related
