### ISSUE TITLE
Cursor='pointer' does not work in JupyterLab

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#535] opened 2018-02-28 19:22 UTC
In this plot, the cursor should change to a pointer when you hover over the points, but in JupyterLab it does not.

However, if you visualize the spec elsewhere (e.g. click "Open In Vega Editor" under the plot) it works properly:

```python
import pandas as pd
import numpy as np
import altair as alt

df = pd.DataFrame({'x': np.random.randn(50),
                   'y': np.random.randn(50)})

alt.Chart(df).mark_circle(
    size=200,
    cursor='pointer'
).encode(
    x='x',
    y='y',
)
```

**Comment by jakevdp** [comment] 2019-05-26 13:58
I just checked – this is still an issue in the current version of JupyterLab. It works in Colab, so I suspect it's an issue with the jupyterlab extension.

**Comment by ian-r-rose** [comment] 2019-05-26 15:56
I just took a look at this. It looks like `vega` is setting the `cursor` CSS property on the document body:
https://github.com/vega/vega/blob/b0dbd40da64fda541cfe2c848c0965457009c766/packages/vega-view/src/cursor.js#L41-L47

This means that if there are any superseding CSS rules on the page (as there are in JupyterLab, and probably other contexts), this cursor override is not seen.

I would consider this to be a bug in vega, or at least fragile, since it's not really reliable to assume that the vega view owns the document body.

**Comment by joelostblom** [comment] 2021-02-23 23:34
This works as intended in JL 2.2.8 so closing this issue.

**Closed by joelostblom** 2021-02-23 23:34 UTC
Labels: vega-lite-related
