### ISSUE TITLE
Support Vega-Lite v5

### ISSUE THREAD

**Issue by korakot** [altair-viz/altair#2477] opened 2021-07-17 14:29 UTC
Vega-Lite v5 is out for half a year now. Can you please add its support in Altair?

---

Please follow these steps to make it more efficient to respond to your feature request.

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [ ] Search for duplicate issues.
- [ ] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by joelostblom** [comment] 2021-07-19 20:41
Duplicate of https://github.com/altair-viz/altair/issues/2425

**Closed by joelostblom** 2021-07-19 20:41 UTC
Labels: enhancement
