### ISSUE TITLE
Columns in layer ignored

### ISSUE THREAD

**Issue by XaviFar** [altair-viz/altair#2290] opened 2020-09-16 09:45 UTC
I'll take an example I saw online to show what I mean.

```
import altair as alt
import pandas as pd
import io

df = pd.read_csv(io.StringIO("""
,Year,Profile,Saison,Pos
0,2017,6.0,Sommer,VL
1,2017,6.0,Winter,VL
13,2017,6.0,Winter,HL
12,2017,6.0,Sommer,HL
18,2017,6.0,Sommer,HR
6,2017,6.0,Sommer,VR
7,2017,6.0,Winter,VR
19,2017,6.0,Winter,HR
14,2018,5.5,Winter,HL
8,2018,5.5,Winter,VR
15,2018,5.5,Sommer,HL
20,2018,4.3,Winter,HR
21,2018,5.0,Sommer,HR
3,2018,5.5,Sommer,VL
2,2018,6.2,Winter,VL
9,2018,4.5,Sommer,VR
17,2019,4.5,Sommer,HL
11,2019,4.2,Sommer,VR
22,2019,3.5,Winter,HR
10,2019,5.28,Winter,VR
5,2019,4.6,Sommer,VL
4,2019,4.9,Winter,VL
16,2019,4.0,Winter,HL
23,2019,4.5,Sommer,HR
"""))

bars = alt.Chart().mark_bar().encode(
    x='Year:O',
    y='Profile:Q',
)

limits = alt.Chart(
  pd.DataFrame({'Profil': [3, 1.5]})
).mark_rule(
  color='red'
).encode(y='Profil')

alt.layer(
    bars,
    limits,
    data=df[df.Saison=='Winter']
).facet(
    column='Pos:N', columns=2
)
```
For some reason this is ignoring the columns in the facet and plots everything in a single row. Is there some way to solve this issue? thanks!!

![visualization(13)](https://user-images.githubusercontent.com/7207214/93321072-18f48800-f812-11ea-8bbe-0d55e7243d9e.png)

**Comment by jakevdp** [comment] 2020-09-16 21:54
Hi – I believe this is working as intended. The column faceting is what causes the chart to be broken into four panels (one per column).

What is it you were expecting to see?

**Comment by XaviFar** [comment] 2020-09-17 14:35
Sorry for the bad explanation, I was referring to the columns=2, part. column='Pos:N', columns=2
Shouldn't it adapt the plot, creating a new row so that we see only two columns?

**Comment by jakevdp** [comment] 2020-09-17 14:56
If you want general facets rather than columns, you can use

```
.facet(
    'Pos:N', columns=2
)
```
This is different than `column='Pos:N'` or `row='Pos:N'`, which always result in faceting along only columns or rows, respectively.

**Comment by joelostblom** [comment] 2021-02-23 19:29
@XaviFar I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Closed by joelostblom** 2021-02-23 19:29 UTC
