### ISSUE TITLE
Providing non-existing data columns fails silently

### ISSUE THREAD

**Issue by miroli** [altair-viz/altair#266] opened 2016-11-10 10:25 UTC
Example with dataframe with columns "country" and "population".

The following code produces an empty chart, because of the misspelled y argument.

    bar = Chart(df).mark_bar()
    bar.encode(x='country', y='pop')

I could fix this, if you agree that this should throw an error instead of failing silently.

**Comment by jakevdp** [comment] 2016-11-10 15:19
Hi – thanks for the report. It turns out this is not as easy to fix as one might think, though we're hoping to push on this once Vega-Lite 2.0 comes out. See the discussion at #247 for details.

**Comment by jakevdp** [comment] 2016-11-10 15:19
I'm going to close this as a duplicate of #247

**Closed by jakevdp** 2016-11-10 15:19 UTC
