### ISSUE TITLE
Greek character µ resulting in corrupted characters in SVG produced using chart.save()

### ISSUE THREAD

**Issue by LeCyberDucky** [altair-viz/altair#2200] opened 2020-06-09 09:36 UTC
Hi, 

I'm running into an issue that I believe looks similar to this one https://github.com/altair-viz/altair/issues/1870, but that one wasn't resolved. I'm trying to use µ as an axis-label. See the following code for an example: 

```
import altair as alt
import pandas as pd

alt.renderers.enable("svg") # Only non-blurry way to show plots in hydrogen

data = {"x": [1, 2, 3], "y": [1, 2, 3]}
data = pd.DataFrame(data)

test = alt.Chart(data).mark_point().encode(
    x = alt.X("x", title = "µ"),
    y = "y"
)

test.save("test.svg")
```

The example renders fine inside my editor: 

![image](https://user-images.githubusercontent.com/19520383/84130967-39a78780-aa44-11ea-99f4-8822edf78c7f.png)

But the produced svg file gives me the following when opening it in Inkscape. Notice what's going on on the x-axis: 

![image](https://user-images.githubusercontent.com/19520383/84131091-66f43580-aa44-11ea-94e4-25ea66030449.png)

Opening the file in a browser gives me this: 

![image](https://user-images.githubusercontent.com/19520383/84131266-9efb7880-aa44-11ea-8e8c-a09bc827ffd4.png)

Note that I type the µ character by using a button for that on my keyboard. I thought that this might result in a weird character, so I tried copying the character from the web (e.g. from here: http://kestrel.nmt.edu/~raymond/software/howtos/greekscape.xhtml). When I use that letter instead and try to save the chart, I get the following error: 

```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-19-a102ef11db3f> in <module>
----> 1 test.save("test.svg")

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\altair\vegalite\v4\api.py in save(self, fp, format, override_data_transformer, scale_factor, vegalite_version, vega_version, vegaembed_version, **kwargs)
    445         if override_data_transformer:
    446             with data_transformers.disable_max_rows():
--> 447                 result = save(**kwds)
    448         else:
    449             result = save(**kwds)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\altair\utils\save.py in save(chart, fp, vega_version, vegaembed_version, format, mode, vegalite_version, embed_options, json_kwds, webdriver, scale_factor, **kwargs)
    104             write_file_or_filename(fp, mimebundle['image/png'], mode='wb')
    105         else:
--> 106             write_file_or_filename(fp, mimebundle['image/svg+xml'], mode='w')
    107     else:
    108         raise ValueError("unrecognized format: '{}'".format(format))

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\altair\utils\save.py in write_file_or_filename(fp, content, mode)
      8     if isinstance(fp, str):
      9         with open(fp, mode) as f:
---> 10             f.write(content)
     11     else:
     12         fp.write(content)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode character '\u03bc' in position 3867: character maps to <undefined>
```

Using the following results in the same error: 

```
test = alt.Chart(data).mark_point().encode(
    x = alt.X("x", title = "\u03bc"),
    y = "y"
)

test.save("test.svg")
```

**Comment by joelostblom** [comment] 2022-03-23 00:07
Closing as duplicate of https://github.com/altair-viz/altair/issues/1870. Please see my latest comment there and let us know if you are still experiencing this issue.

**Closed by joelostblom** 2022-03-23 00:07 UTC
Labels: bug
