### ISSUE TITLE
Wheat wages example is broken

### ISSUE THREAD

**Issue by jonmmease** [altair-viz/altair#3080] opened 2023-06-08 14:26 UTC
The wheat wages example from https://altair-viz.github.io/gallery/wheat_wages.html is a bit broken:

![visualization (1)](https://github.com/altair-viz/altair/assets/15064365/4298e2e7-1f10-467d-8bfd-12904de041f9)

I think the only issue is that the x-axis scale domain is too large.

**Comment by joelostblom** [comment] 2023-06-09 05:00
I'll close this as a duplicate of #2966, I think there might be something else wrong too as I mentioned in that other issue, but I didn't investigate too closely at the time

**Closed by joelostblom** 2023-06-09 05:00 UTC
Labels: bug
