### ISSUE TITLE
three-dots options menu in Altair.Chart, for JupyterLab

### ISSUE THREAD

**Issue by dorin317** [altair-viz/altair#2123] opened 2020-04-30 00:14 UTC
Hello!
In order to see what altair.sphere does, I manually installed today Altair 4.1. (I am using JupyterLab, with Anaconda, on a Windows machine, with Firefox as browser. I think that my previous version of Altair was 2.6 (?). The graphs generated before this upgrade show correctly.) The graphs generated with Altair.Chart after the new install show up with the three-dots menu for save options popping up over the entire graph, activated immediately as the mouse is hovered over the graph. See this screen shot:

![image](https://user-images.githubusercontent.com/62956644/80658866-54560c00-8a55-11ea-9378-f2d8b05c3f3a.png)

Any idea why this is happening?

**Comment by jakevdp** [comment] 2020-04-30 01:27
This is due to overzealous CSS elsewhere in your JupyterLab window, either in a front end extension or in the output cell of a notebook (not necessarily the current notebook).

Try closing all your notebook tabs in Jupyterlab, then reloading the browser window. If that doesn't work, disable frontend extensions that may be affecting CSS styles and re-launch JupyterLab.

More details: #1845, #1916, #1923, #1938 

I have not been able to reproduce this myself, so I'm unsure of the exact cause. If you're able to diagnose it, please let me know.

**Closed by jakevdp** 2020-04-30 01:27 UTC

**Comment by dorin317** [comment] 2020-04-30 03:03
Jake, I really appreciate your answer. Closing all the tabs/open notebooks
and relaunching JupyterLab fixed the problem for me. (I had no problems
with Jupyter Notebook from the beginning. From difficulties with installing
@jupyter-widgets, it seems like the Notebook is more robust than the Lab.)

Cheers!
Dorin

**Comment by dorin317** [comment] 2020-04-30 03:14
In the answer to #1916 you asked about the installed extensions. Here are the ones on my machine (JupyterLab v1.2.3):

![image](https://user-images.githubusercontent.com/62956644/80668134-0a7a1f80-8a6f-11ea-82d8-3472d04368b0.png)
