### ISSUE TITLE
mark_line() could not render line properly.

### ISSUE THREAD

**Issue by yoonghm** [altair-viz/altair#1531] opened 2019-05-24 01:12 UTC
Using matplotlib, I have the following plot:
![power_curve](https://user-images.githubusercontent.com/4215991/58295849-aa610f00-7e03-11e9-8a9a-f688d17c11d1.jpg)

However if I use altair, I could not make it to draw properly. 
![power_curve2](https://user-images.githubusercontent.com/4215991/58295928-04fa6b00-7e04-11e9-89cf-051a0073fbfe.jpg)

Below is the code that I used:

    import altair as alt

    pc_csv = 'https://raw.githubusercontent.com/yoonghm/data/master/power_curve.csv'

    alt.Chart(pc_csv, title="Power Curve") \
            .mark_line(point=True) \
            .encode(
                x=alt.X('Wind speed (m/s):Q'),
                y=alt.Y('Output power (kW):Q'),
            )

`mark_point()` show the following plot:
![power_curve3](https://user-images.githubusercontent.com/4215991/58295989-51de4180-7e04-11e9-8641-d10d8c08b596.jpg)

Do you solution for this?

**Comment by jakevdp** [comment] 2019-05-24 02:34
The issue is that all CSV columns are parsed as strings by default, and so the sorted order is lexographical (i.e. "0", "1", "10", "11", "12"...). You can specify that the columns should be parsed as numbers using the ``format`` argument; for example:
```python
import altair as alt

pc_csv = 'https://raw.githubusercontent.com/yoonghm/data/master/power_curve.csv'
data = alt.UrlData(pc_csv, format={'type': 'csv', 'parse': {'Wind speed (m/s)': 'number'}})

alt.Chart(data, title="Power Curve") \
        .mark_line(point=True) \
        .encode(
            x=alt.X('Wind speed (m/s):Q'),
            y=alt.Y('Output power (kW):Q'),
        )
```
![visualization (93)](https://user-images.githubusercontent.com/781659/58298792-aac0c200-7d91-11e9-93e5-868f75676751.png)

I had thought that the parse argument was automatically filled-in based on the encoding type, however. I think this is a regression – I'm going to file a bug report in Vega-Lite.

**Comment by joelostblom** [comment] 2021-02-23 21:54
This now works as expected without setting `format` explicitly so closing this.

**Closed by joelostblom** 2021-02-23 21:54 UTC
Labels: bug, vega-lite-related
