### ISSUE TITLE
JupyterLab freezes when passing in wrong column name

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1323] opened 2019-02-07 02:04 UTC
The following snippet reproduce the behavior. All other columns other than `Q` will deal with the misspell gracefully, but `bw` column is serious when spelled wrong - the whole session just hang indefinitely.

```
import pandas as pd
import altair as alt

df = pd.DataFrame([['random', 'read', 23.988], ['random', 'write', 43.988],['seq', 'write', 30.22]], columns=['pattern', 'mode', 'bw'])

alt.Chart(df).mark_bar().encode(
    x = 'bwX:Q',
    y = 'mode:O',
    row="pattern:O",
    color="mode:O"
)
```

**Comment by jakevdp** [comment] 2019-02-07 03:50
I can reproduce this in JupyterLab, but not in Colab or Jupyter notebook.

It seems to be some issue with the JupyterLab vega extension. @ellisonbg, any thoughts on this?

**Comment by jakevdp** [comment] 2019-02-07 04:02
Here is a more minimal example of a chart that freezes the JupyterLab frontend:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({'val': [1]})
alt.Chart(data).mark_bar().encode(
    x = 'x:Q',
    row='y:O'
)
```
If you leave out either the x encoding or the row encoding, it no longer freezes.

**Comment by jakevdp** [comment] 2019-02-07 04:16
Just to convince myself that this has nothing to do with Altair... here's how you can reproduce it without any third party libraries in JupyterLab:
```python
class VegaLite:
    def __init__(self, spec):
        self.spec = spec
    def _repr_mimebundle_(self, include, exclude):
        return {'application/vnd.vegalite.v2+json': spec}, {}
  
VegaLite({
 'data': {'name': 'no-data'},
 'mark': 'bar',
 'encoding': {
   'row': {'field': 'y', 'type': 'ordinal'},
   'x': {'field': 'x', 'type': 'quantitative'}
 },
})
```

**Comment by joelostblom** [comment] 2021-02-23 22:45
I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Closed by joelostblom** 2021-02-23 22:45 UTC
Labels: bug
