### ISSUE TITLE
Some bugs about datatype "datetime64"

### ISSUE THREAD

**Issue by Meng-Ziwei** [altair-viz/altair#2408] opened 2021-02-17 12:43 UTC
<img width="427" alt="截屏2021-02-17 17 14 41" src="https://user-images.githubusercontent.com/78152357/108204865-46e24d80-715f-11eb-95bd-c8d90a7c9e64.png">
<img width="329" alt="截屏2021-02-17 17 14 20" src="https://user-images.githubusercontent.com/78152357/108204881-4cd82e80-715f-11eb-94ac-13ecc0aa6664.png">

In these two pictures, you can see the data "Date", and when I want to use Altair to get the chart, Altair fills in days automatically. However, when it comes to Sunday, there are some bugs, and Sunday are changed to Feb!! Interestingly, when I save the code as json, it is right and appears Sunday. 

Here are the outputs. 
<img width="840" alt="截屏2021-02-17 20 46 12" src="https://user-images.githubusercontent.com/78152357/108206568-86aa3480-7161-11eb-9be2-280b78bac705.png">
<img width="1025" alt="截屏2021-02-17 20 46 00" src="https://user-images.githubusercontent.com/78152357/108206600-90339c80-7161-11eb-9dc0-a4d18c248a35.png">

Chart=alt.Chart(df_Singapore).mark_line().encode(
    alt.Y('temperature'),
    alt.X('Date:T'),
    alt.Color('type'),
    alt.StrokeDash('type'),
).properties(
    width=700,
    height=300
)

**Comment by Meng-Ziwei** [comment] 2021-02-17 12:47
I omit the output, here are the output.

<img width="825" alt="截屏2021-02-17 01 10 37" src="https://user-images.githubusercontent.com/78152357/108206376-4a76d400-7161-11eb-886f-2d281d6678ea.png">
<img width="962" alt="截屏2021-02-17 01 10 50" src="https://user-images.githubusercontent.com/78152357/108206383-4ba80100-7161-11eb-8d2d-70c0fcde0c5d.png">

**Comment by jakevdp** [comment] 2021-02-17 13:46
This is the intended behavior. Vega-Lite uses a set of rubrics to decide how to label temporal axes based on the extent and the number of pixels available. If you want to change the labeling scheme, you can specify the `axis.format` argument. See [Adjusting Axis Labels](https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-labels) for some examples.

**Comment by Meng-Ziwei** [comment] 2021-02-17 14:21
Thank you very much to reply me! However, the key point is, Altair fills in Monday, Tuesday, etc. and it cannot fill in Sunday automatically. Besides, as for examples, I cannot find the solution to make the date right, would you please give me more suggestions?
Here are the codes.

 `Chart=alt.Chart(df_Singapore).mark_line().encode(
alt.Y('temperature'),
alt.X('Date:T'),
alt.Color('type'),
alt.StrokeDash('type'),
).properties(
width=700,
height=300
)

**Comment by jakevdp** [comment] 2021-02-17 14:35
If you can include a minimal reproducible example (rather than a screenshot of data), then I'd be happy to show you how to use `format` to change the format.

**Comment by Meng-Ziwei** [comment] 2021-02-17 14:56
Thank you, here is the code.
```python
Chart=alt.Chart(df_Singapore).mark_line().encode(
    alt.Y('temperature',axis=alt.Axis(format='')),
    alt.X('Date'),
    alt.Color('type'),
    alt.StrokeDash('type'),
).properties(
    width=700,
    height=300
)
```

**Comment by jakevdp** [comment] 2021-02-17 14:57
What is `df_Singapore`?

**Comment by jakevdp** [comment] 2021-02-17 14:59
Please provide **complete** code to reproduce the chart.

**Comment by Meng-Ziwei** [comment] 2021-02-17 15:15
Thank you so much for your friendly help and sorry for the inconvenience. I am fresh on github and not very family with the functions. 
Here is the complete code and I upload the data by xlsx.
```python
import pandas as pd
import altair as alt
from vega_datasets import data
df_Singapore=pd.read_excel('df_Singapore.xlsx')Chart=alt.Chart(df_Singapore).mark_line().encode(
    alt.Y('temperature'),
    alt.X('Date:T'),
    alt.Color('type'),
    alt.StrokeDash('type'),
).properties(
    width=700,
    height=300
)
```
[df_Singapore.xlsx](https://github.com/altair-viz/altair/files/5996597/df_Singapore.xlsx)

**Comment by jakevdp** [comment] 2021-02-17 16:06
Thanks. I'm unable to read xlsx files because they are not supported by the current version of Pandas. In the future, please avoid providing data in a separate file, particularly one that has a proprietary format.

When I ask for a complete reproduction of a chart, I mean something like the following: it's entirely self-contained (no need to figure out how to read xlsx files in pandas) and contains sufficient information to reproduce the problem:

```python
import pandas as pd
import numpy as np
import altair as alt

df = pd.DataFrame({
    'Date': pd.date_range('2021-02-05', periods=10, freq='D'),
    'temperature': 31 + np.random.randn(10),
})

alt.Chart(df).mark_line().encode(
    alt.Y('temperature'),
    alt.X('Date:T', axis=alt.Axis(format="%a %d")),
).properties(
    width=700,
    height=300
)
```
![visualization - 2021-02-17T080534 187](https://user-images.githubusercontent.com/781659/108231738-eb7c7500-70f6-11eb-9bbf-88c20b36a627.png)

Note that I've added an axis format statement to format dates as `"%a"` (weekday abbreviation) followed by `"%d"` (day of month). You can read more about date/time format codes used by Altair at https://github.com/d3/d3-time-format

**Comment by Meng-Ziwei** [comment] 2021-02-17 16:15
I really appreciate your kind help! Sorry for any inconvenience I have caused! Hope to communicate with you in the future!

**Comment by joelostblom** [comment] 2021-02-24 00:37
I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Closed by joelostblom** 2021-02-24 00:37 UTC
