### ISSUE TITLE
JupyterLab container - width

### ISSUE THREAD

**Issue by tzipperle** [altair-viz/altair#2057] opened 2020-04-01 07:14 UTC
Hi, I have a problem with the "container" property for the responsive width

I use altair=4.0.1 and jupyterlab=2.0.1 with the following code example:

```python
import altair as alt
from vega_datasets import data

alt.renderers.set_embed_options(actions=False)
source = data.stocks()

highlight = alt.selection(type='single', on='mouseover',
                          fields=['symbol'], nearest=True)

base = alt.Chart(source).encode(
    x='date:T',
    y='price:Q',
    color='symbol:N'
)

points = base.mark_circle().encode(
    opacity=alt.value(0)
).add_selection(
    highlight
).properties(
    width='container',
    height=200
)

lines = base.mark_line().encode(
    size=alt.condition(~highlight, alt.value(1), alt.value(3))
)

points + lines
```

This results in:

![image](https://user-images.githubusercontent.com/6015123/78109141-f6ec8200-73f8-11ea-90df-829039ac782a.png)

Why does the dynamic width does not working?

And is it possible e.g. set 'container50%'?

**Comment by jakevdp** [comment] 2020-04-01 13:19
I think the issue is that JupyterLab does not have a fixed-width container for the output. Does it work if you manually put the chart in a fixed-width div?
```python
from IPython.display import HTML
html = chart._repr_mimebundle_(None, None)['text/html']
HTML(f'<div width="800px">{html}</div>')
```

**Comment by tzipperle** [comment] 2020-04-02 06:51
Thank you for your answer. For the html export I could fix it with:

``` python
HTML("""<style>canvas.marks {max-width: 80%!important;
    height: auto!important;text-align:center}</style>""")
```

**Comment by joelostblom** [comment] 2021-02-23 21:01
@tzipperle I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Closed by joelostblom** 2021-02-23 21:01 UTC
