### ISSUE TITLE
Using empty dataframe creates chart with nonsense height

### ISSUE THREAD

**Issue by BielStela** [altair-viz/altair#1933] opened 2020-01-28 09:41 UTC
Hello, 
The following chart definition when using an empty data frame creates an svg element with `height="1.7976931348623157e+308"`. That's around 10^300 m long chart. Given that the observable universe is about 10^26 m I bet that's a bug. 
```python
base_chart = alt.Chart(df).mark_circle().properties(width='container', height=100)
chart = (base_chart
             .encode(x=alt.X('day_sameyear', axis=alt.Axis(title='', grid=False),
                             scale=alt.Scale(padding=10)), 
                     y=alt.Y('season',
                             sort=alt.EncodingSortField('season', order='ascending'),
                             axis=alt.Axis(grid=True)),
                     color=alt.Color('activity', scale=alt.Scale(domain=list(df['activity'].unique()),
                                                                 range=base_colours)),
                     )
            )
```
If I remove the color `scale` property it works well and shows an empty chart so the problem is in `color`. With an empty data frame, domain is `[]` but range is a list of 6 colors.

I'm using `chart.to_json()` to render the plot in a html with vega-embed 
I'm using altair 4.0.1, vega-lite 4.0.2 and vega-embed 4.2.1

**Comment by jakevdp** [comment] 2020-01-28 13:18
What is base_colours in your example? I suspect the issue is related to specifying a scale with an empty domain, which is nonsense.

**Comment by BielStela** [comment] 2020-01-28 13:49
It is a list with 15 rgba colors like this:
`['rgba(83,90,160,0.7)', (151,216,138,0.7)', (255,184,56,0.7)', ...]`

**Comment by jakevdp** [comment] 2020-01-29 01:09
> I'm using altair 4.0.1, vega-lite 4.0.2 and vega-embed 4.2.1

I am unable to reproduce this with the most recent version of vega-embed (6.2.2).

I suspect this is a vega-embed bug that was fixed in more recent releases.

**Closed by jakevdp** 2020-01-29 01:09 UTC
