### ISSUE TITLE
Adding a bin shorthand

### ISSUE THREAD

**Issue by JarnoRFB** [altair-viz/altair#1567] opened 2019-06-18 09:54 UTC
Would it be possible to add a shorthand syntax for binning? The exact proposal would be to to allow to replace
```python
alt.Chart(cars).mark_bar().encode(
    x=alt.X("Horsepower", bin=True), 
    y="count()"
)
```
by

```python
alt.Chart(cars).mark_bar().encode(
    x="bin(Horsepower)", 
    y="count()"
)
```

After reading through #763 I understand that changes in this direction are not trivial, but I would suppose that just allowing this simple substitution would not break the conceptual model, as one would still have to use `alt.X` to customize the binning. However, for the default case this substitution should correspond to what is already being done for aggregations.

**Comment by jakevdp** [comment] 2019-06-18 20:52
It's an interesting idea, and I've thought about adding something like this in the past... 

One alternative I've thought about is to use an approach similar to the [vega-lite Javascript API](https://github.com/vega/vega-lite-api) and allows things like
```
alt.Chart().encode(
   alt.X('column').bin()
)
```
to make it more natural to transition from a default binning to a configured binning... Also remove the ``bin=alt.Bin`` boilerplate. We could do similar things with ``scale``, ``axis``, etc.

The problem is that currently ``alt.X.bin`` is a class attribute that is either ``Undefined``, ``True``, or an ``alt.Bin()`` object. Tuirning it into a callable method could break existing code. But it may be worth the breaking change to make encoding attributes more expressive.

**Comment by JarnoRFB** [comment] 2019-06-27 08:01
I think the JS API looks very fluent. It is also nice that it takes the builder pattern that is already present at the `Chart` level, to the more lower levels of the API. I believe adding this kind of API to altair would greatly enhance the user experience.

> The problem with that idea is that currently alt.X.bin is a class attribute that is either Undefined, True, or an alt.Bin() object. Turning it into a callable method could break existing code.

What about sticking even closer to the JS API and offering lower-case alternatives for the channel builders? So one could write

```python
alt.Chart().encode(
   alt.x('column').bin(...).scale(...)
)
```
The, let's call them channel functions, and their methods would then always return a channel builder object. 
Then just before the chart is rendered one would have to traverse the chart object and call `build()` on every builder, so the user does not really have to care about it. 
This way one could put the new fluent channel API next to the existing one, without having to worry to much about breaking existing code.

**Comment by jakevdp** [comment] 2019-06-28 16:23
I've been playing with this a bit... we might be able to fit this kind of new approach on top of the old one. Something like this (we'd need to adjust method signatures & docs, but that won't be too hard):
```python
def propertysetter(name, cls):
  def setter(self, *args, **kwargs):
    if len(args) == 1 and len(kwargs) == 0:
      setattr(self, name, args[0])
    else:
      setattr(self, name, cls(*args, **kwargs))
    return self
  return setter

class X(alt.X):
  bin = propertysetter('bin', alt.Bin)
  axis = propertysetter('axis', alt.Axis)
  scale = propertysetter('scale', alt.Scale)
```
Then you could define a chart like this:
```python
chart = alt.Chart('data.csv').mark_point().encode(
  x = X('name:Q').bin(maxbins=100).axis(title=None).scale(None)
)

chart.to_dict()
# {'$schema': 'https://vega.github.io/schema/vega-lite/v3.3.0.json',
#  'config': {'mark': {'tooltip': None}, 'view': {'height': 300, 'width': 400}},
#  'data': {'url': 'data.csv'},
#  'encoding': {'x': {'axis': {'title': None},
#    'bin': {'maxbins': 100},
#    'field': 'name',
#    'scale': None,
#    'type': 'quantitative'}},
#  'mark': 'point'}
```
The main backward incompatibility here is that you could no longer access attribues by their name; i.e. ``chart.encoding.x.bin`` would reference the setter function, not the bin value.

**Comment by domoritz** [comment] 2019-06-28 16:50
> The main backward incompatibility here is that you could no longer access attribues by their name; i.e. chart.encoding.x.bin would reference the setter function, not the bin value.

How often do people use this? In JavaScript, we often solve this problem by using a function that is an accessor when you don't pass any arguments and a setter when you pass arguments. I don't know how pythonic this would be, though, and it also doesn't solve the backwards compatibility issue.

**Comment by jakevdp** [comment] 2019-06-28 16:58
> How often do people use this? 

Not much, if at all. We don't do any direct property access in Altair's docs or examples, so I think it's a pretty minor incompatibility all told. And my take is it's well worth the benefit of being able to do this:
```python
chart.encode(
  x = alt.X('name:Q').bin(maxbins=100).axis(title=None).scale(None)
)
)
```
instead of this:
```python
chart.encode(
  x = alt.X('name:Q',
    bin=alt.Bin(maxbins=100),
    axis=alt.Axis(title=None),
    scale=None
  )
)
```

**Comment by domoritz** [comment] 2019-06-28 17:00
Just to make sure, autocomplete (in e.g. VSCode or JupyterLab) would work as expected here?

**Comment by jakevdp** [comment] 2019-06-28 17:08
Autocomplete would work for systems based on Jedi or similar (i.e. ones that can infer the return type of ``alt.X()`` in order to populate autocomplete for its methods.

**Comment by kanitw** [comment] 2019-06-28 21:48
> The main backward incompatibility here is that you could no longer access attribues by their name; i.e. chart.encoding.x.bin would reference the setter function, not the bin value.

We can at least make `chart.encoding.x.bin()` return current bin value when there is no parameter specified?  (This is what VL-API currently does.)

**Comment by jakevdp** [comment] 2019-06-28 22:16
> We can at least make chart.encoding.x.bin() return current bin value when there is no parameter specified?

Yes, that should work. Although that might mess with the type inference engines behind autocomplete in the case of chained statements, because it means there's more logic required to infer the correct return type.

**Comment by kanitw** [comment] 2019-06-30 15:20
>  Although that might mess with the type inference engines behind autocomplete in the case of chained statements, because it means there's more logic required to infer the correct return type.

I see. I think good autocompletion is probably more important.  I guess people can always do .to_dict()["bin"] to get the values or we can introduce `.get_bin()` or something.

**Comment by kanitw** [comment] 2019-07-01 16:32
@jakevdp  

Would this mean that `sort`, which has two class types (SortByEncoding and EncodingSortField), would support either `.sort(encoding="x", order="ascending")` or `.sort(op=..., field=..., order=...)` ?

**Comment by jakevdp** [comment] 2019-07-01 16:36
> Would this mean that sort, which has two class types

Hmm... that's an interesting question. From the user's perspective, I think it would make the most sense to have a single method, with the return type chosen based on the content of the arguments.

Do you know offhand how the JS API handles this?

**Comment by kanitw** [comment] 2019-07-01 16:53
Since JS doesn't support keyword arguments and but support dict args, the JS API simply takes either `.sort({encoding: 'x', order: 'ascending'})` or `.sort({op: ..., field: ..., order: ...})`. 


Note that we're considering if sort should support channel name (https://github.com/vega/vega-lite/pull/5134), which is a bit relevant to this question about sort.

**Comment by jakevdp** [comment] 2019-07-01 17:18
Ah, I see.

Huge +1 on supporting channel name as well; we can make it all work from the Altair side.

**Comment by jakevdp** [comment] 2019-11-23 21:11
Prototype & more discussion in #1629

**Comment by binste** [comment] 2023-05-26 20:12
The method-based syntax was added in Altair 5 🥳 See https://altair-viz.github.io/user_guide/encodings/index.html#method-based-syntax. Closing this issue

**Closed by binste** 2023-05-26 20:12 UTC
Labels: enhancement
