### ISSUE TITLE
Regression line for only the samples selected from a cross plot

### ISSUE THREAD

**Issue by Philliec459** [altair-viz/altair#2679] opened 2022-09-09 14:32 UTC
I have been using Altair for about a year and love this library.  Altair provides some of the best interactivity of any python software. Thank you. 

Now I would like to create a regression line for:
- All samples from a cross plot (this is currently available in Altair).
-  Just the selected samples from the cross plot. Normally I would select a larger number of samples that what is shown in this example, but I just wanted to give you and idea of what I am doing. For the selected box of samples from the cross plot I would like to be able to generate a real time regression line for the selected samples. 

I can make the regression line for all samples, but once I add **selection-interval** under properties I get the following error message:

Javascript Error: Duplicate signal name: "selector007_x_1"

![k-phi_with_Pc](https://user-images.githubusercontent.com/56929340/189373108-bfc0591f-c4f8-4756-8279-b7cc93db0197.gif)

**Comment by joelostblom** [comment] 2022-09-09 19:35
Hello @Philliec459, could you include the code you are currently trying? Preferably a simplified example that is easy to understand right away using some sample data.

**Comment by Philliec459** [comment] 2022-09-09 21:28
This is the code used for selection and regression by Rock Type. Chart1 is used for the selection of data points, and chart2 is used to show the regression line. At the moment the regression line will not show until I select samples from chart1. What I would like is to show the regression line just for the selected samples.



#read the file
file = r'./data/Pc_Results.xlsx'
df_core = pd.read_excel(file,index_col=False)

x=df_core['Porosity']
y=df_core['Permeability']
group = df_core['ROCK_INDEX']
interval = alt.selection_interval()

df = pd.DataFrame({'x': x, 'y': y, 'group': group})  # this is following the example that was given

chart1 = alt.Chart(df).mark_point(filled=True, size=100).encode(
    x='x',
    y= alt.Y('y',scale = alt.Scale(type= 'log')),
    color=alt.condition(interval, 'group:O', alt.value('lightgray'),
                        scale=alt.Scale(
                        domain=[ 1,         2,         3,      4,      5,        6   ],
                        range =['cyan', 'dodgerblue','blue','yellow','orange','brown']))
).properties(
    title="Rock Type as Color Axis",
    selection=interval,
)

chart2 = alt.Chart(df).mark_point(filled=True, size=100).encode(
    x='x',
    y= alt.Y('y',scale = alt.Scale(type= 'log')),
    color=alt.condition(interval, 'group:O', alt.value('lightgray'),
                        scale=alt.Scale(
                        domain=[ 1,         2,         3,      4,      5,        6   ],
                        range =['cyan', 'dodgerblue','blue','yellow','orange','brown'])) 
).properties(
    title="Rock Type as Color Axis",
    #selection=interval,
)

Reg_Line = chart.transform_regression('x', 'y',
                                      method="pow"  ,
                                      #groupby = ['group']                            
).mark_line()

chart1  |  chart2   +  Reg_Line


![select_poro_perm_regress](https://user-images.githubusercontent.com/56929340/189448370-15b0776b-042a-47a3-9ef7-51c8faee42b8.gif)

**Comment by joelostblom** [comment] 2022-09-09 22:24
I can't easily run that code because it references a specific data file that I don't have access too. But if I understand correctly I think you should be able to use a `transform_filter` with the selection on the regression chart, to only include the selected points in that chart. [Similar to this example from the docs.](https://altair-viz.github.io/gallery/selection_histogram.html)

**Comment by Philliec459** [comment] 2022-09-10 04:03
Hi Joel,

I will put it all in a github repo

**Comment by Philliec459** [comment] 2022-09-10 12:38
That was a brilliant suggestion using brush. It works great. I will put this out on GitHub as a repository for others and send you the link. Thank you very much.

**Comment by Philliec459** [comment] 2022-09-10 13:39
This is the GitHub link for the example that you helped me create. Thanks again for all of your help.

https://github.com/Philliec459/Regression-Line-from-Points-Selected-off-of-Cross-Plot-using-Altair

**Comment by joelostblom** [comment] 2022-09-10 14:30
Thanks for sharing your full solution! That will be helpful for others coming across the same problem. I will close this issue as resolved.

**Closed by joelostblom** 2022-09-10 14:30 UTC
Labels: enhancement

**Comment by ChristopherDavisUCI** [comment] 2022-09-15 02:27
@joelostblom Do you think a version of this would be a good addition to the Examples gallery?  I don't think there is anything similar.

If Joel thinks it's a good idea, is that something you'd like to add, @Philliec459?  [Here](https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md#adding-examples) is some info about adding examples.  No worries if you don't have time.

**Comment by joelostblom** [comment] 2022-09-15 22:20
Yes, I think we could add an example of this to the docs. The doc page I linked has something similar but I believe there is nothing in the gallery so we could add one there. We might do a bigger cleanup at some point later and make sure there isn't too much in the gallery, but for now it could be good to have this recorded somewhere.

**Comment by Philliec459** [comment] 2022-09-16 17:24
Hi All,


I am not sure if I am supposed to do anything on this or not. I believe that you are referring to the example where Joel helped us create a regression line for only the selected samples from a cross plot. If so, then I would love to see this as an example.  Joel’s suggestions were very helpful and introduces a new aspect of Altair that many are not that familiar with.  Per my post on LinkedIn, this application of Altair has had a lot of positive response from the Oil Industry sector. 



Best Regards, 
 
_______________________________
 
E. Craig Phillips
CEO and Chief Petrophysicist
Crested Butte Petrophysical Consultants
 










459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
email: ***@***.***
Website: www.cbpetro.com
GitHub: https://github.com/Philliec459




On Sep 15, 2022, at 6:20 PM, Joel Ostblom ***@***.***> wrote:


Yes, I think we could add an example of this to the docs. The doc page I linked has something similar but I believe there is nothing in the gallery so we could add one there. We might do a bigger cleanup at some point later and make sure there isn't too much in the gallery, but for now it could be good to have this recorded somewhere.

**Comment by ChristopherDavisUCI** [comment] 2022-09-19 01:46
@Philliec459 From my perspective, it's totally up to you.  If you want to add the example, that's great.  Otherwise I'm happy to adapt your example.  (I think none of the Altair documentation examples use external datasets, so at least that part would be changed.)  @joelostblom can correct me if I have things wrong.

**Comment by Philliec459** [comment] 2022-09-19 14:04
I think I would rather have you add the example since I am not familiar with the process. The data for this regression sample is created within the code and not external data. What makes this example unique is the use of transform_filter as suggested by Joel that allows us to work only on the selected data.

Best Regards, 
 
_______________________________
 
E. Craig Phillips
CEO and Chief Petrophysicist
Crested Butte Petrophysical Consultants
 










459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
email: ***@***.***
Website: www.cbpetro.com
GitHub: https://github.com/Philliec459




On Sep 18, 2022, at 9:46 PM, Christopher Davis ***@***.***> wrote:


@Philliec459 <https://github.com/Philliec459> From my perspective, it's totally up to you. If you want to add the example, that's great. Otherwise I'm happy to adapt your example. (I think none of the Altair documentation examples use external datasets, so at least that part would be changed.) @joelostblom <https://github.com/joelostblom> can correct me if I have things wrong.
