### ISSUE TITLE
Installation with conda - Altair in the wrong directory

### ISSUE THREAD

**Issue by gchevrot** [altair-viz/altair#427] opened 2017-10-24 14:01 UTC
I used conda to install Altair (conda install altair --channel conda-forge) but when I tried to import altair, Python could not find the package.

Then I noticed that Altair was installed in this directory:
anaconda3/envs/py36/site-packages/altair
Instead of this one (where all my packages are installed):
anaconda3/envs/py36/lib/python3.6/site-packages/altair

So I just copied altair in the second directory (anaconda3/envs/py36/lib/python3.6/site-packages/altair) and now it works. 

But is there a reason to install altair in the first directory instead of the second one?

**Comment by jakevdp** [comment] 2017-10-30 14:22
That sounds like it might be a conda issue. ``conda install`` puts things in the correct place for me. What operating system are you on?

**Comment by jakevdp** [comment] 2017-10-30 14:23
Can you paste the output of ``conda info -a``?

**Comment by jakevdp** [comment] 2017-10-30 14:24
Also, does ``$HOME/.pydistutils.cfg`` by chance exist on your system? That can override install paths, though I'm not certain if it would affect conda.

**Comment by gchevrot** [comment] 2017-10-30 14:37
Nope, I don't have this file $HOME/.pydistutils.cfg

Here is the output of conda info -a:

/Users/guillaume/anaconda3/lib/python3.5/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.18) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.21.3
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : /Users/guillaume/anaconda3  (writable)
    default environment : /Users/guillaume/anaconda3/envs/py36
       envs directories : /Users/guillaume/anaconda3/envs
                          /Users/guillaume/.conda/envs
          package cache : /Users/guillaume/anaconda3/pkgs
                          /Users/guillaume/.conda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/intel/osx-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/guillaume/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.5.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
# conda environments:
#
R                        /Users/guillaume/anaconda3/envs/R
py2                      /Users/guillaume/anaconda3/envs/py2
py36                  *  /Users/guillaume/anaconda3/envs/py36
root                     /Users/guillaume/anaconda3

sys.version: 3.5.4 |Anaconda, Inc.| (default, Oct  5 ...
sys.prefix: /Users/guillaume/anaconda3
sys.executable: /Users/guillaume/anaconda3/bin/python
conda location: /Users/guillaume/anaconda3/lib/python3.5/site-packages/conda
conda-build: /Users/guillaume/anaconda3/bin/conda-build
conda-convert: /Users/guillaume/anaconda3/bin/conda-convert
conda-develop: /Users/guillaume/anaconda3/bin/conda-develop
conda-env: /Users/guillaume/anaconda3/bin/conda-env
conda-index: /Users/guillaume/anaconda3/bin/conda-index
conda-inspect: /Users/guillaume/anaconda3/bin/conda-inspect
conda-metapackage: /Users/guillaume/anaconda3/bin/conda-metapackage
conda-pipbuild: /Users/guillaume/anaconda3/bin/conda-pipbuild
conda-render: /Users/guillaume/anaconda3/bin/conda-render
conda-server: /Users/guillaume/anaconda3/envs/py36/bin/conda-server
conda-sign: /Users/guillaume/anaconda3/bin/conda-sign
conda-skeleton: /Users/guillaume/anaconda3/bin/conda-skeleton
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: py36
CONDA_ENVS_PATH: <not set>
CONDA_PATH_BACKUP: /Users/guillaume/anaconda3/bin:/usr/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin
CONDA_PREFIX: /Users/guillaume/anaconda3/envs/py36
CONDA_PS1_BACKUP: \n\[\033[0;31m\]\d \t - \u \[\033[0;35m\]@ \[\033[0;32m\]\w \[\e[00m\]\[\033[1;32m\]\n \[\033[0;37m\][\#] → \[\e[00m\]
CONDA_ROOT: /Users/guillaume/anaconda3
DYLD_LIBRARY_PATH: <not set>
FTP_PROXY: <not set>
HTTPS_PROXY: <not set>
HTTP_PROXY: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /Users/guillaume/anaconda3/envs/py36/bin:/Users/guillaume/anaconda3/bin:/usr/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

License directories:
    /Users/guillaume/.continuum
    /Users/guillaume/Library/Application Support/Anaconda
    /Users/guillaume/anaconda3/licenses
License files (license*.txt):
Package/feature end dates:

**Comment by jakevdp** [comment] 2017-10-30 14:44
I think the issue is that you have ``CONDA_PREFIX`` set... do you have a ``~/.condarc`` file? If so, that may be the culprit. That said, this is quickly getting beyond my knowledge of conda's internals. I'd suggest raising this issue on the conda mailing list: folks there might be more helpful.

**Comment by gchevrot** [comment] 2017-10-30 15:07
Yes, I have a .condarc file, the content is:

channels:
  - r
  - intel
  - defaults

Should I modify this file?

**Comment by gchevrot** [comment] 2017-10-30 15:15
It is weird because this issue never happened for other packages. I'll make some tests and follow your suggestion.

Thanks for your help!

**Comment by jakevdp** [comment] 2017-10-30 15:31
No, that looks OK. I'm just trying to figure out where your ``CONDA_PREFIX`` setting is coming from. Do you have any conda-related things in your bash startup file?

**Comment by gchevrot** [comment] 2017-10-30 15:37
I just have the normal "/Users/guillaume/anaconda3/bin" added in the PATH.

**Comment by jakevdp** [comment] 2017-10-30 16:17
OK – I'd ask on the conda list.

**Comment by jakevdp** [comment] 2019-05-26 13:55
Closing because this is unrelated to altair

**Closed by jakevdp** 2019-05-26 13:55 UTC
