### ISSUE TITLE
Plot don't display on local computer, but do on server

### ISSUE THREAD

**Issue by rcolpo** [altair-viz/altair#2958] opened 2023-03-13 19:15 UTC
Hello,

I generate two HTML files with function with the function `altairChart.save('altairChart.html')`, and manually put both graphs into a single file. I can open the file and see the graphs, but my coworkers can't, as seen in the screenshots below:

![screenShots](https://user-images.githubusercontent.com/5889181/224801602-fd253ac9-c773-4740-b59b-f10c4a666c34.jpg)

Trying to solve this problem, and after reading [here](https://github.com/altair-viz/altair/issues/986) that AdBlockers could possibly be related to this issue, I created a version 2 of the file, including the "data" from the "URL data sources" directly into the HTML file, but it was still not working to my colleagues. You can find below these two files (I had to change the file extension to .TXT, because GitHub does not accept .HTML. Please rename the files before opening).

[twoCharts.txt](https://github.com/altair-viz/altair/files/10960726/twoCharts.txt)
[twoChartsv2.txt](https://github.com/altair-viz/altair/files/10960723/twoChartsv2.txt)

My coworkers could only see the graphs when I uploaded the files to a server and sent the link instead of the file. The links are:

https://sbmlcomp.bioinf.uni-leipzig.de/jobs/twoChartsv1.html
https://sbmlcomp.bioinf.uni-leipzig.de/jobs/twoChartsv2.html

Why can't they see the plot just by opening the file? (They can, however, open an HTML file with this [Simple Bar Chart](https://altair-viz.github.io/gallery/simple_bar_chart.html))

**Comment by mattijn** [comment] 2023-03-13 22:19
They render fine for me. It is not directly clear what the root cause is. Does the console tab in the DevTools of your coworkers give any hints why their page is not rendering?

**Comment by joelostblom** [comment] 2023-04-03 21:45
Closing, please re-open by adding a comment with more details if this is still an issue.

**Closed by joelostblom** 2023-04-03 21:45 UTC
Labels: bug
