### ISSUE TITLE
The KDE plot is strange when extent is not specified in transform_density

### ISSUE THREAD

**Issue by j4ggr** [altair-viz/altair#3203] opened 2023-09-28 10:27 UTC
When I use the given example for a KDE plot, I also get the expected result:

```Python
import altair as alt
from vega_datasets import data

source = data.iris()

alt.Chart(source).transform_fold(
    ['petalWidth',
     'petalLength',
     'sepalWidth',
     'sepalLength'],
    as_ = ['Measurement_type', 'value']
).transform_density(
    density='value',
    bandwidth=0.3,
    groupby=['Measurement_type'],
    extent=[0, 8]
).mark_area().encode(
    alt.X('value:Q'),
    alt.Y('density:Q'),
    alt.Color('Measurement_type:N')
)
```
![image](https://github.com/altair-viz/altair/assets/43211511/10382513-d79d-438c-a3ae-bcb43dfe6954)

But as soon as I remove the optional extent specification, the chart looks pretty bad:
```Python
import altair as alt
from vega_datasets import data

source = data.iris()

alt.Chart(source).transform_fold(
    ['petalWidth',
     'petalLength',
     'sepalWidth',
     'sepalLength'],
    as_ = ['Measurement_type', 'value']
).transform_density(
    density='value',
    bandwidth=0.3,
    groupby=['Measurement_type']
).mark_area().encode(
    alt.X('value:Q'),
    alt.Y('density:Q'),
    alt.Color('Measurement_type:N')
)
```
![image](https://github.com/altair-viz/altair/assets/43211511/6be18b4b-4b87-4e11-91cd-d24946e8dd13)

### Versions
Python: 3.11.1
Altair: 5.1.1

**Comment by jonmmease** [comment] 2023-09-28 13:00
Thanks for the report @j4ggr, I think this likely has the same root cause as https://github.com/vega/vega-lite/issues/9078. The fix for this has been merged into Vega-Lite in https://github.com/vega/vega-lite/pull/9106, but we need to wait for a Vega-Lite release in order to update Altair with the fix.

**Comment by joelostblom** [comment] 2023-10-19 15:38
This is working as expected in altair 5.1.2 so closing this issue

**Closed by joelostblom** 2023-10-19 15:38 UTC
Labels: bug

**Comment by marianokamp** [comment] 2024-05-30 14:13
![image](https://github.com/vega/altair/assets/3245189/c0b20422-9fdc-495d-a9a4-23c64f03b3f9)
Still broken for me @joelostblom. How did you verify that it does not work anymore? My steps to reproduce: 
- Install 5.1.2 (or 5.2.0 or 5.3.0)
- Restart Jupyter Kernel
- Execute 2nd code snippet.

**Comment by joelostblom** [comment] 2024-05-31 08:36
@marianokamp If you recently installed the new version of ALtair, make sure you clear all outputs in the notebook and then restart jupyterlab (not just the kernel). Otherwise an old version of VegaLite might still be used in the background.

**Comment by marianokamp** [comment] 2024-05-31 09:08
@joelostblom Re-installed 5.3, then restarted jupyterlab (not just the kernel): Now the 2nd code example, without extent, works. Thank you.

**Comment by firasm** [comment] 2025-02-26 22:20
FYI - I'm still seeing this in Altair 5.5.0. I've restarted the kernel, restarted jupyterlab, done things in the cloud (PrairieLearn) but the spiky behaviour is back if I don't specify extent. 

![Image](https://github.com/user-attachments/assets/e15ee80f-79d1-4aab-a0a4-cc738aa33b09)

after adding extent to transform_density:

![Image](https://github.com/user-attachments/assets/63ddee11-0192-42e5-ad07-2c234ed78e3c)

I can try to put together a minimally reproducible example with shareable plots when I have some more time.

**Comment by firasm** [comment] 2025-03-18 04:40
Finally got an MRE setup with a slightly modified stock dataset.

This code:

```
import altair as alt
import pandas as pd
from vega_datasets import data

# Quick bit of Wrangling to add a column to do a split-violin plot
df = data.cars().copy()
df["Binary"] = (df['Miles_per_Gallon'] % 2).fillna(0).astype(int)

chart = alt.Chart(df, width=100).transform_density(
    density="Miles_per_Gallon",
    groupby=["Origin","Binary"],
    as_=["Miles_per_Gallon", "density"],
    #extent=[5, 50],
).mark_area(orient="horizontal").encode(
    alt.X(
        "density:Q",
        stack="center",
        impute=None,
        title=None,
        axis=alt.Axis(labels=False, values=[0], grid=False, ticks=True),
    ),
    alt.Y("Miles_per_Gallon:Q"),
    alt.Color("Binary:N"),
    facet=alt.Facet("Origin:N",spacing=0,header=alt.Header(titleOrient="bottom", labelOrient="bottom", labelPadding=0)),
).configure_view(
    stroke=None
)

chart
```

produces the expected result:

![Image](https://github.com/user-attachments/assets/77b3f836-ad9b-4149-99bd-ccabec73912c)

and just by changing the renderer to the `jupyterlab` one:

```
alt.renderers.enable('jupyterlab')
chart
```

produces a broken plot:

![Image](https://github.com/user-attachments/assets/9016d2e0-d056-4185-becd-29eb238da056)

Adding `extent=[5, 50],` to `transform_density()` fixes the problem.

Hope this helps!

**Comment by joelostblom** [comment] 2025-03-18 13:11
Thanks for posted the example @firasm. It seems like this is a more isolated case than before and specific to the central stacking without an extent and without vegafusion. I opened https://github.com/vega/altair/issues/3819 to track it.
