### ISSUE TITLE
Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror

### ISSUE THREAD

**Issue by altosaar** [altair-viz/altair#2998] opened 2023-03-27 14:51 UTC
Hi! 

We are trying to plot the following data: https://github.com/GulnaraY/codespaces-jupyter/blob/2e16b50885fee127d9d1eb9a21018bfa8231016c/data/chatgpt_users.csv#L33

We are using this notebook as an example for the datathinking.org class: https://github.com/altosaar/datathinking.org-codespace-230327/blob/main/230327-plotting-yyyymmdd-data-and-principles.ipynb

However, the error we are receiving is `Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror`.

We have tried following the advice of ChatGPT and Claude and changed web-browsers, installed missing dependencies, but we still cannot view the inline chart or the chart in a new browser window using GitHub codespaces. It is a blank window:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5317244/227976780-55384be5-bc21-4bf3-8b55-55eac3f434b3.png">

cc @jakevdp @domoritz in case they have run into this before! Thank you so much. And cc @ghalimi who we learned the principles of data visualization from last week.

Thank you so much for any help!

**Comment by altosaar** [comment] 2023-03-27 15:35
Thank you @domoritz ! 

Yes:

This code:

```


import altair as alt
import altair_viewer

alt.renderers.enable('altair_viewer', inline=True)
import pandas as pd

# Create artificial dataset
dates = ['20210101', '20210201', '20210301', '20210401', '20210501',
         '20210601', '20210701', '20210801', '20210901', '20211001',
         '20211101', '20211201', '20220101', '20220201', '20220301',
         '20220401', '20220501', '20220601', '20220701', '20220801',
         '20220901', '20221001', '20221101', '20221201']

y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
     19, 20, 21, 22, 23, 24]

# Convert the date strings to datetime objects and create a DataFrame
df = pd.DataFrame({'date': pd.to_datetime(dates, format='%Y%m%d'), 'y': y})

# Create the Vega-Lite chart
chart = alt.Chart(df).mark_line().encode(
    x='date:T',
    y='y:Q'
).properties(
    title='Example Plot with Dates on X-Axis'
)

# chart.show()

altair_viewer.display(chart, inline=True)
```

Leads to this error:

`Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror`

In this environment: https://github.com/altosaar/datathinking.org-codespace-230327/blob/main/environment.yml

In this codespace virtual machine: https://github.com/altosaar/datathinking.org-codespace-230327/tree/main/.devcontainer

Is this helpful? 

Please let us know if you need any further details to reproduce! 🙏 🙏 🙏

**Comment by domoritz** [comment] 2023-03-27 16:52
Hmm, I get no error and no script is loaded when I run this in my local environment. This seems like an issue with the environment. Maybe the environment is blocking access to external scripts?

**Comment by joelostblom** [comment] 2023-04-03 21:41
@altosaar I'm closing this as it sounds like the issue is with GitHub rather than Altair? But please feel free to share any information you come across that is helpful in a comment in the closed issue, and reopen if you think there is something we can improve.

**Closed by joelostblom** 2023-04-03 21:41 UTC
Labels: bug

**Comment by ashish-ka** [comment] 2025-11-21 04:42
For someone still having this issue, clearing the JS cache worked for me.

```
%%javascript
requirejs.undef('vega-embed');
requirejs.undef('vega');
requirejs.undef('vega-lite');
```
