### ISSUE TITLE
Setting  a domain squishes out-of-domain points onto the y axis

### ISSUE THREAD

**Issue by kevinlinxc** [altair-viz/altair#2524] opened 2021-11-20 20:56 UTC
![image](https://user-images.githubusercontent.com/44324811/142740504-0a2a745a-2e01-4636-a9e3-122e3052fc23.png)
Title, all the previous values are on the y axis and they look bad
Code:
```python
max_clamp = data.shape[0]
min_clamp = 0
if max_clamp > max_x:  # max_x is 30 by default
    min_clamp = max_clamp - max_x

base = chart.transform_fold(
    datatypes, as_=['datatype', 'value']
).mark_line(
    point={
        "filled": False,
        "fill": "white"
    }
).encode(
    x='index:Q',
    y='value:Q',
    color='datatype:N',
    tooltip=datatypes
).properties(
    width=650,
    height=300
)

upper = base.encode(
    alt.X('index:Q',
          scale=alt.Scale(
              domain=(min_clamp, max_clamp),
              clamp=True,
              nice=False  # prevents autoresizing xticks which is awful to look at in real-time
          )
          ),
)

lower = base.properties(
    height=40
).add_selection(brush)

return alt.vconcat(upper, lower).to_dict()

```

Another picture with the brush visible: 
![image](https://user-images.githubusercontent.com/44324811/142740603-6e8c6dcc-c1d9-45e8-98d2-a03baa827607.png)

**Comment by jakevdp** [comment] 2021-11-20 21:25
This is the intended behavior when using `clamp=True` (out-of bounds points are clamped to the domain limit). For more information on configuring domains, see https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits

**Comment by kevinlinxc** [comment] 2021-11-20 21:40
Is there a workaround to that, or a way to limit the domain without clamping?

**Comment by ChristopherDavisUCI** [comment] 2021-11-21 00:35
Does adding `clip=True` inside of `mark_line` produce what you want?

**Comment by kevinlinxc** [comment] 2021-11-26 05:27
no: 
![image](https://user-images.githubusercontent.com/44324811/143531365-937659df-40a2-45f6-b6ff-9ebb89b9c930.png)

**Comment by jakevdp** [comment] 2021-11-26 13:39
It looks like you're still setting `clamp=True`. Set `clamp=False` and the points should no longer be clamped to the edge of the axis.

If you'd like further assistance debugging this, I'd suggest putting together a complete reproducible example, and we can help figure out what the issue is (`data` is not defined in your code above).

**Comment by joelostblom** [comment] 2022-01-12 16:55
Closing for now, @kevinlinxc please fee free to reopen with a complete reproducible example if the issue remains.

**Closed by joelostblom** 2022-01-12 16:55 UTC
