### ISSUE TITLE
Radial charts are "inverted" when used in concatenation

### ISSUE THREAD

**Issue by umichhaidn** [altair-viz/altair#3017] opened 2023-04-10 18:25 UTC
Normally, a radial chart has arcs that extend outward from an inner radius. But when concatenated (either by hconcat, vconcat, or | operator) the arcs extend INWARD into the inner radius as depicted below:

![image](https://user-images.githubusercontent.com/79999494/230967064-c49a6499-fb6c-472d-a3f5-670f767366fb.png)

![image](https://user-images.githubusercontent.com/79999494/230967228-e6499ded-6a03-42b8-987b-5dd367fc6ad9.png)

**Comment by mattijn** [comment] 2023-04-10 20:14
Thanks for raising! This is a bug in Vega-Lite and reported here: https://github.com/vega/vega-lite/issues/7856. 
I've added your example to the issue.

The issue is that there is no `width` and `height` defined on the radial chart in the concatenated chart.

There is a workaround for now, until the core issue is solved and that is by defining a `width` and `height` to the radial chart using parameters (available in Altair version 5)

```python
import pandas as pd
import altair as alt

source = pd.DataFrame({"values": [12, 23, 47, 6, 52, 19]})

radial = alt.Chart(source).mark_arc(innerRadius=20, stroke="#fff").encode(
    theta=alt.Theta("values:Q", stack=True),
    radius=alt.Radius("values", scale=alt.Scale(type="sqrt", zero=True, rangeMin=20)),
    color="values:N",
)
radial

bar = alt.Chart(source).mark_bar().encode(
    x=alt.X('values:Q'),
    y=alt.Y('values:N'),
    color='values:N'
)

w = alt.param(name="width", value=300)
h = alt.param(name="height", value=300)

radial.add_params(w, h) | bar
```
![image](https://user-images.githubusercontent.com/5186265/230987633-6e90a621-47d1-4253-bdd3-805a6ccda7c0.png)

**Comment by umichhaidn** [comment] 2023-04-11 14:57
Many thanks for the update and workaround!

**Comment by joelostblom** [comment] 2023-04-11 23:57
Closing as a workaround was provided and there is nothing to do on the Altair side of things. When the issue is fixed in Vega-Lite it will be available in the next Altair release

**Closed by joelostblom** 2023-04-11 23:57 UTC
Labels: bug
