### ISSUE TITLE
sort channel not working when I add text on top of my bars

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#698] opened 2018-04-02 22:01 UTC
This sorts like I want.

```python
import altair as alt
from vega_datasets import data

barley = data.barley()
alt.Chart(cars.head(10)).mark_bar().encode(
    x='Miles_per_Gallon:Q',
    y=alt.Y('Name:N', sort=alt.SortField(field="Miles_per_Gallon", op="sum", order="descending"))
)
```

![visualization 24](https://user-images.githubusercontent.com/9993/38218436-a9f37122-3686-11e8-91d1-c21a371f6dcf.png)

This does not.

```python
bars = alt.Chart(cars.head(10)).mark_bar().encode(
    x='Miles_per_Gallon:Q',
    y=alt.Y('Name:N', sort=alt.SortField(field="Miles_per_Gallon", op="sum", order="descending"))
)

text = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3,
).encode(text='Miles_per_Gallon:Q')

bars + text
```

![visualization 25](https://user-images.githubusercontent.com/9993/38218443-ae8a7adc-3686-11e8-8cdb-112ed9c470df.png)

Why?

**Comment by afonit** [comment] 2018-04-02 22:08
That is a known bug in vega-lite, I did a search and could not find the issue right away - I will edit this comment if I find it later.

**Comment by jakevdp** [comment] 2019-05-27 13:33
Fixed in Altair 3:
```python
import altair as alt
from vega_datasets import data

cars = data.cars()

bars = alt.Chart(cars.head(10)).mark_bar().encode(
    x='Miles_per_Gallon:Q',
    y=alt.Y('Name:N', sort=alt.EncodingSortField(field="Miles_per_Gallon", op="sum", order="descending"))
)

text = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3,
).encode(text='Miles_per_Gallon:Q')

bars + text
```
![visualization - 2019-05-27T063345 243](https://user-images.githubusercontent.com/781659/58423208-62332e00-8049-11e9-9b6f-148882aeea44.png)

**Closed by jakevdp** 2019-05-27 13:33 UTC
Labels: bug, vega-lite-related

**Comment by aaronbarzilai** [comment] 2019-06-24 22:03
I know this was closed, but wanted to confirm, would you expect this to work if the data was split across multiple dataframes? I can work to assemble it all into a single frame, but I have a situation where I want the data labels in the middle of a stacked bar (similar to https://github.com/altair-viz/altair/issues/1147) and I am doing the position calculation separately. 

I've tried it with two different dataframes as the base and it doesn't work.   I get the similar alphabetical ordering that happens above, even though the frames use the same categories and it matches them up correctly (right text with right bars).

Thanks, and thanks for all the work on Altair, it's great.

Aaron

PS If you'd expect it to work, I can submit a full report.

**Comment by jakevdp** [comment] 2019-06-24 22:37
I'm not certain what you mean when you say the data are split across multiple dataframes, so I'm not sure whether I expect it to work (or what "work" means in this context). An example would be helpful.

**Comment by aaronbarzilai** [comment] 2019-06-25 03:03
```
df=pd.DataFrame({'category': ['Start','Test 1', 'Test 1', 'Finish','Finish', ],
                 'grouping': ['group2', 'group2','group1', 'group2','group1'],
                 'count': [10000,8000,2000,5000,3000], 
                 'position': [5000, 4000, 11000, 2500, 9000]})
display(df)  

bars=alt.Chart(df).mark_bar().encode(
    alt.X('count',axis=None,scale=alt.Scale(domain=[0, 15000])), 
    alt.Y('category',
          axis=alt.Axis(title=None, ticks=False),
         ),
    alt.Color('grouping',
              scale=alt.Scale(
                  domain=['group2', 'group1'],
                  range=['#3d85c6','#D9D9D9',] 
              ),
              legend=None
             )
)
print("Just the bars drawn, not sorted:")
display(bars)

####################################################


bars=alt.Chart(df).mark_bar().encode(
    alt.X('count',axis=None,scale=alt.Scale(domain=[0, 15000])), 
    alt.Y('category',
          sort=['Start','Test 1','Finish'],
          axis=alt.Axis(title=None, ticks=False),
          
         ),
    alt.Color('grouping',
              scale=alt.Scale(
                  domain=['group2', 'group1'],
                  range=['#3d85c6','#D9D9D9',] 
              ),
              legend=None
             )
)

text=alt.Chart(df).mark_text(align='center', baseline='middle').encode(
    alt.X('position', axis=None), 
    alt.Y('category',
          sort=['Start','Test 1','Finish'],
          axis=alt.Axis(title=None, ticks=False),
         ),
    text='count')
print("Sorts with the bars and text when alt.Chart called with same df")
display(alt.layer(bars, text))


#################################

bars=alt.Chart(df).mark_bar().encode(
    alt.X('count',axis=None,scale=alt.Scale(domain=[0, 15000])), 
    alt.Y('category',
          sort=['Start','Test 1','Finish'],
          axis=alt.Axis(title=None, ticks=False),
          
         ),
    alt.Color('grouping',
              scale=alt.Scale(
                  domain=['group2', 'group1'],
                  range=['#3d85c6','#D9D9D9',] 
              ),
              legend=None
             )
)

text1=alt.Chart(df[df['grouping']=='group2']).mark_text(align='center', baseline='middle').encode(
    alt.X('position', axis=None), 
    alt.Y('category',
          sort=['Start','Test 1','Finish'],
          axis=alt.Axis(title=None, ticks=False),
         ),
    text='count')

# Note text 2 is align left
text2=alt.Chart(df[df['grouping']=='group1']).mark_text(align='left', baseline='middle').encode(
    alt.X('position', axis=None), 
    alt.Y('category',
          sort=['Start','Test 1','Finish'],
          axis=alt.Axis(title=None, ticks=False),
         ),
    text='count')

print("Does not Sort with bars and two texts when use text with slice (for diff align).\nSame problem if different df as well.")
display(alt.layer(bars, text1,text2))
```
As an aside, I also couldn't get it to reverse the sorting of the stacking of group2 and group1 (which is closest to 0) so had to list in opposite order.

Here's what it looks like.
![image](https://user-images.githubusercontent.com/15833991/60066029-ea056a00-96d3-11e9-8c8e-9c4dc85344eb.png)

Thanks and sorry if this is a duplicate of another issue.

Aaron

**Comment by jakevdp** [comment] 2019-06-25 15:40
Yeah, I think this is a bug. Here's a simpler reproduction:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'label': ['one', 'two', 'three'],
    'value': [1, 2, 4],
})

df2 = pd.DataFrame({
    'label': ['one', 'two', 'three'],
    'value': [2, 3, 5],
})

bars = alt.Chart(df).mark_bar().encode(
    x='value',
    y=alt.Y('label', sort=['one', 'two', 'three']),
)

text = alt.Chart(df2).mark_text().encode(
    x='value',
    y=alt.Y('label', sort=['one', 'two', 'three']),
    text='value'
)

bars + text
```
![visualization - 2019-06-25T083846 148](https://user-images.githubusercontent.com/781659/60112439-a850df80-9724-11e9-9e2a-279ae37af2d2.png)

Sort order appears to not be respected when scales are drawn from multiple datasets. The workaround until this is fixed is to put all your values in a single dataset.

**Comment by jakevdp** [comment] 2019-06-25 15:41
If you look in the console output, you'll see the reason for this:
```
[Warning] Dropping sort property {"field":"y_label_sort_index","op":"min"} as unioned domains only support boolean or op 'count'.
```

**Comment by jakevdp** [comment] 2019-06-25 15:47
Relevant Vega-Lite issue: https://github.com/vega/vega-lite/issues/5048

**Comment by ananis25** [comment] 2019-12-18 13:04
hi @jakevdp 

The error also seems to come up with a single data source, if an aggregation op for the sort property isn't specified. Here is a small repro.

```
import altair as alt
import pandas as pd
import numpy as np

# data
df = pd.DataFrame(
    {    
        'city': ['D', 'B', 'C', 'A'],
        'col1': [1, 2, 3, 4],
        'col2': 10*np.random.random(4),
    }
).assign(
    colA = lambda x: x.col2 + 1,
    colB = lambda x: x.col2 - 1
)

# common x axes
unsorted_x_axis = alt.X('city', sort=alt.EncodingSortField('col1', order='ascending'))
sorted_x_axis = alt.X('city', sort=alt.EncodingSortField('col1', op='min', order='ascending'))

# expected plot order - D C B A
chart1 = alt.Chart(df).mark_line().encode(x = sorted_x_axis, y = 'col2')
chart2 = chart1.mark_errorbar().encode(y = 'colB', y2 = 'colA')

# underspecified plot - A B C D
chart3 = alt.Chart(df).mark_line().encode(x = unsorted_x_axis, y = 'col2')
chart4 = chart3.mark_errorbar().encode(y = 'colB', y2 = 'colA')

(chart1 + chart2) | (chart3 + chart4)
```
![altair-repro](https://user-images.githubusercontent.com/16446513/71088578-c0ca2000-21c4-11ea-8ffc-d272b66b8109.png)

From the helpful console warning, it seems Vega assumes the default aggregation op to be "mean" when none is specified and proceeds to drop it when layering >1 charts. 
```
WARN Dropping sort property {"field":"num_demos","op":"mean","order":"descending"} as unioned domains only support boolean or op "count", "min", and "max".
```

"mean" feels like the suitable default when an `aggregation op` isn't specified, and we aggregate over values of X. Although the dropped sort  behavior might seem counterintuitive to people who aren't doing any aggregations on X axis and just plotting 2 curves together., like in the example.

Do you think changing the default `aggregation op` to something like `min` is a good idea?

PS. Thank you for your work on this library.

**Comment by jakevdp** [comment] 2019-12-18 13:46
The default aggregation is set within Vega-Lite. It might be worth a feature request there.

**Comment by armsp** [comment] 2020-07-19 07:08
@jakevdp does filtering the same data source but only for text chart, still count as **single data source**? I am getting the exact same issue with sorting here. I have a single dataframe for both bar and text, however to hide some text, I just filter the data when calling `mark_text` and then my graph just sorts alphabetically.

Let me know if you want me to give you an example?

I was hoping that while using the same dataframe, but filtering internally in altair, sorting shoud work too.

**Comment by jakevdp** [comment] 2020-07-20 16:05
@armsp - I'm not sure I understand. Can you give an example that demonstrates the problem you're seeing?

**Comment by armsp** [comment] 2020-07-20 17:35
@jakevdp Sure, I was able to reproduce this behavior with one of the inbuilt datasets.
Let's take the [stacked bar chart with text overlay example](https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html) but order the internal bars based on `site`.

Let's modify the dataset to add an `order` column so that we can easily the order the y-axis based on that -
```py
import altair as alt
from vega_datasets import data

source=data.barley()
source['order'] = source.groupby(['variety'])['yield'].transform('sum')
```
Now I will show you 3 scenarios -
**Coloured Bars ordered by `site`, y-axis is unordered**
```py
bars = alt.Chart(source).mark_bar().encode(
    x=alt.X('sum(yield):Q', stack='zero'),
    y=alt.Y('variety:N'),
    color=alt.Color('site'),
    order = 'site'
)

text = bars.mark_text(dx=-15, dy=3, color='white').encode(
    color=alt.value('white'),
    text=alt.Text('sum(yield):Q', format='.1f')
)

bars + text
```
gives as expected -
![1z](https://user-images.githubusercontent.com/12681262/87967040-d8131800-cadb-11ea-84c3-ad9175daaf1a.png)

**Now, we will order the y-axis too -**
```py
bars = alt.Chart(source).mark_bar().encode(
    x=alt.X('sum(yield):Q', stack='zero'),
    #y=alt.Y('variety:N'),
    y=alt.Y('variety:N', sort=alt.SortField('order', order='descending')),
    color=alt.Color('site'),
    order = 'site'
)

text = bars.mark_text(dx=-15, dy=3, color='white').encode(
    color=alt.value('white'),
    text=alt.Text('sum(yield):Q', format='.1f')
)

bars + text
```
gives as expected -
![2z](https://user-images.githubusercontent.com/12681262/87967612-b6666080-cadc-11ea-9216-f926f5ed4bcc.png)

**However, when I filter the data in text chart (still using the same data source since using it via `bars.mark_text`) to show text labels for only a couple of `site`s, the y-axis order is lost**
```py
bars = alt.Chart(source).mark_bar().encode(
    x=alt.X('sum(yield):Q', stack='zero'),
    #y=alt.Y('variety:N'),
    y=alt.Y('variety:N', sort=alt.SortField('order', order='descending')),
    color=alt.Color('site'),
    order = 'site'
)

text = bars.mark_text(dx=-15, dy=3, color='white').transform_filter({'field': 'site', 'oneOf': ['Crookston', 'Duluth']}).encode(
    color=alt.value('white'),
    text=alt.Text('sum(yield):Q', format='.1f')
)

bars + text
```
gives the following which is not as expected -
![3z](https://user-images.githubusercontent.com/12681262/87967770-f88fa200-cadc-11ea-89c3-28bdbdc487a1.png)

The y-axis order is same as first scenario in this one. I was however expecting that it retain the correct y-axis order.

**Comment by jakevdp** [comment] 2020-07-21 20:37
I'm not sure why this is happening; I think it's a vega-lite bug. Here's a simplified vega-lite spec showing the issue ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA28QAspQA4Gc4B6IgNwFMBzCAOkoEspNEAjG+gezKogFpIY+clHxEBEIiwhpyATxoArfBwB2IAL4AaEFGQQV+AGYdkAW3gBtUAo70VESpWQ8o5S6A64M+ROe2H6clQwDFlA4JBtCHwMEzByZA0AXW0nDkRcFllLEFJpQKhspPUUkHIVAGMOMDtKeFAAD3qQAKCQuBAwtsiQBycXNw6fPx1ZXEGQAEdEfShGaHoKHvwYCoBrDAAvBI4NbWyEFvD23PzhbO1C8YwVDlM7CHRtZWQoZtaIjriEnu-Ejvi+Aq5RqKjq6i0ID+zSuE1u93sTyO3SGjDcEO0qAgsh+cCsIFM0g2HSkiW05SqoLqhyqqBMMLGcLuDyRHxO+DRGgxoF0+iMJnMeNAAVQrn+OmQiHRpUJyGJPMZGFcDTe2lp9I6AHdMJztGAmnBeABGACseoOAGZIRTqrUYeQVQzrh1prN5nMllFHM5qK5vL4emzQsdAwLoBgaEbDFyStpNfQwEx4AA2AAMqfUQA)):
```json
{
  "data": {"url": "https://vega.github.io/vega-datasets/data/barley.json"},
  "transform": [
    {
      "joinaggregate": [{"op": "sum", "field": "yield", "as": "order"}],
      "groupby": ["variety"]
    }
  ],
  "encoding": {
    "x": {
      "field": "yield",
      "aggregate": "sum",
      "type": "quantitative",
      "stack": "zero"
    },
    "y": {
      "field": "variety",
      "type": "nominal",
      "sort": {"field": "order", "order": "descending"}
    },
    "order": {"type": "nominal", "field": "site"}
  },
  "layer": [
    {
      "mark": "bar",
      "encoding": {"color": {"type": "nominal", "field": "site"}}
    },
    {
      "transform": [{"filter": "true"}],
      "mark": {"type": "text", "color": "white", "dx": -15, "dy": 3},
      "encoding": {
        "text": {
          "type": "quantitative",
          "aggregate": "sum",
          "field": "yield",
          "format": ".1f"
        }
      }
    }
  ],
  "width": 600
}
```
If you delete the `filter` line, the sort works as expected.

I think it's probably some issue with unioned domains, though strangely there is no warning in the Vega editor.

As a workaround, you can set `resolve_scale(y='independent')`, which preserves the sort:
```python
import altair as alt
from vega_datasets import data

source=data.barley.url

bars = alt.Chart(source).transform_joinaggregate(
    order='sum(yield)', groupby=['variety']  
).mark_bar().encode(
    x=alt.X('sum(yield):Q', stack='zero'),
    y=alt.Y('variety:N', sort=alt.SortField('order', order='descending')),
    color=alt.Color('site:N'),
    order = 'site:N'
)

text = bars.mark_text(
    dx=-15, dy=3,
).transform_filter(
    {'field': 'site', 'oneOf': ['Crookston', 'Duluth']}
).encode(
    color=alt.value('white'),
    text=alt.Text('sum(yield):Q', format='.1f'),
    y=alt.Y('variety:N', sort=alt.SortField('order', order='descending'), axis=None),
)

(bars + text).resolve_scale(y='independent')
```
![visualization (17)](https://user-images.githubusercontent.com/781659/88104506-6082ce80-cb57-11ea-8e3c-6ad3d34f126d.png)

**Comment by armsp** [comment] 2020-07-23 05:25
@jakevdp Yup, `resolve_scale(y='independent')` helps a lot. Thanks !

**Comment by armsp** [comment] 2020-07-26 14:35
@jakevdp When you say it's probably a Vega-Lite bug, then should we raise an issue in Vega-Lite?

**Comment by tombohub** [comment] 2021-08-21 16:12
I am using with ticks and it's not working:

![2021-08-21 12_11_45-Altair Viewer](https://user-images.githubusercontent.com/3029412/130328092-3188943f-7140-440d-a61d-08e0d0cb6e7c.png)

**Comment by umichhaidn** [comment] 2023-03-30 19:49
Did this get un-fixed in Altair v 5.0.0? I had it working just fine in 4.2.2, but had to update to get alt.param() to work. Now the basic bars + text is no longer sorting again.

**Comment by mattijn** [comment] 2023-03-30 20:13
Can you tell me a bit more on your situation?
If I try the following ([colab notebook](https://colab.research.google.com/drive/1U8MOFS0DVGcbXC5nj9FKqc9O-xMmaa7j?usp=sharing)):

```python
# !pip install altair==5.0.0rc1
import altair as alt
from vega_datasets import data

cars = data.cars()

bars = alt.Chart(cars.head(10)).mark_bar().encode(
    x='Miles_per_Gallon:Q',
    y=alt.Y('Name:N').sort(field="Miles_per_Gallon", op="sum", order="descending")
)

text = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3,
).encode(text='Miles_per_Gallon:Q')

bars + text
```
![image](https://user-images.githubusercontent.com/5186265/228953437-791543b7-a47d-4d97-8849-642ede93cdf1.png)

Then the basic `bars + text` seems to work fine.

**Comment by umichhaidn** [comment] 2023-03-30 20:47
@mattijn 
Looks like the difference there is that you're sorting with op='sum' on the 'Name' field. I'm just specifying another field on which to sort completely. And that works fine on the non-compound charts, but once I put them together it ignores the sort field and just sorts 'Name' alphabetically. That's the only difference I'm seeing.

![image](https://user-images.githubusercontent.com/79999494/228960485-0e282b9a-89cb-4657-887e-ed4678efe30c.png)
