### ISSUE TITLE
Always open links as target="_blank"

### ISSUE THREAD

**Issue by buckle2000** [altair-viz/altair#2184] opened 2020-06-01 06:06 UTC
Currently, there is no way to open links in embed Vega charts in Jupyter Lab. With data visualizatIon in mind, I think all links should be opened in its own tab.

Related to https://github.com/vega/vega/issues/1171.

**Comment by jakevdp** [comment] 2020-06-01 13:00
Duplicate of https://github.com/vega/vega-lite/issues/3795

**Closed by jakevdp** 2020-06-01 13:00 UTC
