### ISSUE TITLE
Dropdown Menu in Geoshape Chart

### ISSUE THREAD

**Issue by philippnb** [altair-viz/altair#2383] opened 2021-01-08 17:48 UTC
Hello,

I'm currently having troubles to integrate a dropdown menu into a geoshape chart with the following code:

```
source = alt.topo_feature(data.world_110m.url, "countries")

background = alt.Chart(source).mark_geoshape(fill="black")

input_dropdown = alt.binding_select(options=['GISAID','CNCB'])

selection = alt.selection_single(fields=['Community'], bind=input_dropdown, name='Community')

color = alt.condition(selection,
                    alt.Color('Count:N', legend=None),
                    alt.value('lightgray'))
foreground = (
    alt.Chart(source)
    .mark_geoshape(stroke="black", strokeWidth=0.15)
    .encode(
        color=color,
        tooltip=[
            alt.Tooltip("country:N", title="Country"),
            alt.Tooltip("countryID:N", title="ID"),
            alt.Tooltip("Count:Q", title="No. of Submissions"),
        ],
    ).transform_lookup(
        lookup='id',
        from_=alt.LookupData(completeDFLong, key='countryID',
                             fields=['country','countryID','Community','Count'])
    )
    .properties(
    title='Locations of Submissions in selected Community'
).add_selection(
    selection
).transform_filter(
    selection
)
)
final_map = (
    (background + foreground)
    .configure_view(strokeWidth=0)
    .configure_title(
    fontSize=20,
    color='black'
)
    .properties(width=700, height=600)
    .project("naturalEarth1")
    
)
final_map
```

The structure of the complete Dataframe is as follows:

![image](https://user-images.githubusercontent.com/38496064/104046610-9fc5da00-51e0-11eb-9454-21f2c95d3938.png)

But unfortunately changing the selection in the dropdown menu doesn't change the chart. Also coloring doesn't match the "Count" column:

![image](https://user-images.githubusercontent.com/38496064/104046723-cedc4b80-51e0-11eb-8e68-715eb11ee782.png)

Is it even possible to use a dropdown menu for a geoshape chart? All examples I found in the documentation were used in `mark_point()` instead of `mark_geoshape()`

If yes, how can I make sure that the selected item is passed into the `selection` variable and subsequently into the color encoding?

Thank you in advance 
and best regards!

**Comment by joelostblom** [comment] 2021-02-24 00:09
@philippnb Could you provide the dataset you're working with or use a vega sample dataset so that we can try to reproduce this?

**Comment by joelostblom** [comment] 2022-03-23 01:23
Closing for now, feel free to reopen and provide the requested details to reproduce this issue.

**Closed by joelostblom** 2022-03-23 01:23 UTC
Labels: question

**Comment by DajanaMuho** [comment] 2022-05-07 04:57
Hello @joelostblom, 
I'm having the same issue. I'm trying to visualize the spread of immigrants across US. 
Here is the format of my dataset 
![image](https://user-images.githubusercontent.com/44034311/167238609-bf39609c-b414-4cca-9659-fefc2327c063.png)

The code:
```
input_dropdown = alt.binding_select(options=list(ds.Year.unique()), name='Year')
selector = alt.selection_single(fields=['Year'], bind=input_dropdown, init={'Year': 2011})

base = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

chart = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color='Immigrants:Q',
    tooltip=['State:N', 'Immigrants:Q'],
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(ds, key='id', fields=['State', 'Immigrants', 'Year'])
).add_selection(
    selector
).transform_filter(
    datum.Year == selector["Year"][0]
).properties(
    width=700,
    height=400,
    projection={'type': 'albersUsa'},
)
layer = base + chart
layer = layer.configure_view(stroke=None).configure_title(fontSize=20)
```

But I'm not getting the data filtered by the selected year. 
![image](https://user-images.githubusercontent.com/44034311/167238943-f07c7ac2-3499-45f1-9b44-c68621971216.png)

If I change the tranform_filter to a condition like :
`datum.Year == 2020`
It behaves as expected.
![image](https://user-images.githubusercontent.com/44034311/167239008-04d88d49-c050-42c5-9d32-9501e161136a.png)


**So how can I make the filtering of the data dynamic ?** 

Thanks!

**Comment by joelostblom** [comment] 2022-05-07 17:06
Try just using `.transform_filter(selector)` as in the second example here https://altair-viz.github.io/user_guide/interactions.html#input-element-binding

**Comment by DajanaMuho** [comment] 2022-05-07 20:32
@joelostblom Thanks for your reply!
I have tried that but isn't working as expected. Shows the same output as the first image I attached. 
I believe the issue is caused by tranfrom_lookup that doesn't reflect the filter on the dataset. 
That's why when filtering with the datum.Year == specific value it works. 
I'm wondering if there is a way to get the selected value from the dropdown in Altair this way I can use that in the condition. 

Thanks!

**Comment by joelostblom** [comment] 2022-05-07 21:37
Hmm I wonder if it is an issue with your data being interpreted as the
wrong type, or maybe the difference between i dicing multi and single
select selectors. Could you post a sample of your data as text and include
the full code you use to read in the data so I can copy, paste and run it
on my end?

**Comment by DajanaMuho** [comment] 2022-05-07 21:48
Thanks @joelostblom 
I uploaded them on a drive so you can easily access both the code and the dataset [https://drive.google.com/drive/folders/1n5T4WEfuN46T66PpPsJQgxfNgNF8t28I?usp=sharing](https://drive.google.com/drive/folders/1n5T4WEfuN46T66PpPsJQgxfNgNF8t28I?usp=sharing)
Yeah also that issue can be, Year is of type int and maybe the check fails because of that.

**Comment by joelostblom** [comment] 2022-05-08 18:34
Thanks @DajanaMuho , I prefer not downloading files so I copied part of your data into this reproducible example:

```python
import pandas as pd
import altair as alt
from vega_datasets import data
from io import StringIO


datastring = """
Year	State	Immigrants	id	Latitude	Longitude
2011	Alabama	4063	1	33.2588817	-86.8295337
2011	Alaska	1799	2	64.4459613	-149.680909
2011	Arizona	20333	4	34.395342	-111.763275
2011	Arkansas	2874	5	35.2048883	-92.4479108
2012	California	210591	6	36.7014631	-118.755997
2012	Colorado	13547	8	38.7251776	-105.607716
2012	Connecticut	12577	9	41.6500201	-72.7342163
2012	Delaware	2355	10	38.6920451	-75.4013315
"""

ds = pd.read_csv(StringIO(datastring), sep='\t')
states = alt.topo_feature(data.us_10m.url, feature='states')

input_dropdown = alt.binding_select(options=list(ds.Year.unique()), name='Year')
selector = alt.selection_single(fields=['Year'], bind=input_dropdown, init={'Year': 2011})

base = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

chart = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color='Immigrants:Q',
    tooltip=['State:N', 'Immigrants:Q'],
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(ds, key='id', fields=['State', 'Immigrants', 'Year'])
).add_selection(
    selector
).transform_filter(
    selector
).properties(
    width=700,
    height=400,
    projection={'type': 'albersUsa'},
)

(base + chart).configure_view(stroke=None).configure_title(fontSize=20)
```

![image](https://user-images.githubusercontent.com/4560057/167310326-ca4eaf35-c3ce-4d07-9eb9-18ae6ed3c71a.png)

As you can see, this works as expected and changing the dropdown changes the displayed states. I believe your issue is with reading in the excel data, rather than with something related to Altair. Make sure that the `Year` column is an int:

```
ds.dtypes

Year            int64
State          object
Immigrants      int64
id              int64
Latitude      float64
Longitude     float64
dtype: object
```

You might need something like `ds['Year'] = ds['Year'].astype(int)` and a general tip is to store data in CSV files or similar plain text formats instead of Excel, which can avoid some issues like this.

**Comment by DajanaMuho** [comment] 2022-05-09 05:20
Hey, @joelostblom I tried to convert to text and the issue still occurred, I wasn't able to get data in the map for all years.
 But finally I understood why !!!! 
So the issue is for column `**id**` I'm using to merge the two datasets. 
As you can notice in the dataset the id column has duplicated values as every state is repeated for every year, this way the filter in the transformed lookup isn't able to perform the group by year too.

You can reproduce the issue by using
datastring = """
Year	State	Immigrants	id	
2011	Alabama	4063	1	
2011	Alaska	1799	2	
2011	Arizona	20333	4	
2011	Arkansas	2874	5	
2012	Alabama	3873	1	
2012	Alaska	1612	2
2012	Arizona	18434	4
2012	Arkansas	2795	5
""" 
So, any idea how I can make this merge work in Altair?
Thanks!

**Comment by joelostblom** [comment] 2022-05-09 06:30
Good find! I am not sure if there is a simple workaround for that. An inelegant way to solve it would be to pivot to a wide dataframe so that every row has a unique ID and then use `transform_longer` in altair:

```python
import pandas as pd
import altair as alt
from vega_datasets import data
from io import StringIO


datastring = """
Year State Immigrants id
2011 Alabama 406 1
2011 Alaska 179 2
2011 Arizona 203 4
2011 Arkansas 287 5
2012 Alabama 3873 1
2012 Alaska 1612 2
2012 Arizona 18434 4
2012 Arkansas 2795 5
"""
ds = pd.read_csv(
    StringIO(datastring), sep=' '
).pivot(
    index=['State', 'id'], columns='Year', values='Immigrants'
).reset_index()
ds.columns = ds.columns.astype(str)

states = alt.topo_feature(data.us_10m.url, feature='states')

input_dropdown = alt.binding_select(options=ds.columns[2:].tolist(), name='Year')
selector = alt.selection_single(fields=['Year'], bind=input_dropdown, init={'Year': '2011'})

base = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

chart = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color='Immigrants:Q',
    tooltip=['State:N', 'Immigrants:Q'],
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(ds, key='id', fields=['State'] + ds.columns[2:].tolist())
).transform_fold(
    as_=['Year', 'Immigrants'],
    fold=['2011', '2012']
).add_selection(
    selector
).transform_filter(
    selector
).properties(
    width=700,
    height=400,
    projection={'type': 'albersUsa'},
)

(base + chart).configure_view(stroke=None).configure_title(fontSize=20)
```

**Comment by mattijn** [comment] 2022-05-09 09:33
Think reverse. Lookup the `geometry` instead of the `stats`. 

```python
.transform_lookup(
    lookup='id',
    from_=alt.LookupData(states, key='id', fields=['geometry', 'type'])
)
```

In combination with `alt.Chart(ds)`. 

Full spec:
```python
import pandas as pd
import altair as alt
from vega_datasets import data
from io import StringIO


datastring = """
Year State Immigrants id
2011 Alabama 4063 1
2011 Alaska 1799 2
2011 Arizona 20333 4
2011 Arkansas 2874 5
2012 Alabama 3873 1
2012 Alaska 1612 2
2012 Arizona 18434 4
2012 Arkansas 2795 5
"""

ds = pd.read_csv(StringIO(datastring), sep=' ')
states = alt.topo_feature(data.us_10m.url, feature='states')

input_dropdown = alt.binding_select(options=list(ds.Year.unique()), name='Year')
# next altair version: from `init={'Year': 2011}` to `value=2011`
selector = alt.selection_single(fields=['Year'], bind=input_dropdown, init={'Year': 2011})

base = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

chart = alt.Chart(ds).mark_geoshape(stroke='black').encode(
    color='Immigrants:Q',
    tooltip=['State:N', 'Immigrants:Q'],
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(states, key='id', fields=['geometry', 'type'])
).add_selection(
    selector
).transform_filter(
    selector
).properties(
    width=700,
    height=400,
    projection={'type': 'albersUsa'},
)

(base + chart).configure_view(stroke=None).configure_title(fontSize=20)
```

**Comment by DajanaMuho** [comment] 2022-05-09 22:08
YES, it worked!
Thank you very much @joelostblom  and @mattijn
