### ISSUE TITLE
Programmatically select element within Selection

### ISSUE THREAD

**Issue by BenAbyss** [altair-viz/altair#2446] opened 2021-04-04 22:39 UTC
This may be a feature already, but my searching hasn't alluded to it being. It would be really useful to be able to set the value of the currently selected element in a Selection object, similar to how you can with the `init` tag but after the objects creation.
This would be great for further compatibility with other elements of python. In my current case, it would allow for interactions with the PyQt library for non-graphical interactions with the users selection

**Comment by joelostblom** [comment] 2023-02-06 01:19
There is no way to interact with the selection programmatically using only altair, but you can if you use the panel library. Closing this as a duplicate of https://github.com/altair-viz/altair/issues/1153 and more info can be found there.

**Closed by joelostblom** 2023-02-06 01:19 UTC
Labels: enhancement
