### ISSUE TITLE
Chart title displayed under column title and labels

### ISSUE THREAD

**Issue by janfreyberg** [altair-viz/altair#782] opened 2018-04-26 09:32 UTC
When both a chart title and a column encoding is specified, the chart title is displayed *under* the column labels and title:

```python
import altair as alt

cars = alt.load_dataset('cars')

chart = alt.Chart(cars, title='Chart title').mark_bar().encode(
    x=alt.X('Horsepower'),
    y=alt.Y('count(*):Q'),
    column=alt.Column('Acceleration', header=alt.Header(title='Acceleration'), bin=alt.Bin(maxbins=3)),
)

chart
```

![image](https://user-images.githubusercontent.com/4092425/39298043-0c12010c-493d-11e8-9593-5282f4e24d7e.png)

It seems to me that the chart title should be displayed above everything else in the chart.

**Comment by jakevdp** [comment] 2018-04-26 14:38
Thanks! I've reported this issue in vega-lite: https://github.com/vega/vega-lite/issues/3672

**Comment by jakevdp** [comment] 2018-04-26 17:42
Update: looks like this is a regression in the vega package, and will be fixed soon.

**Comment by jakevdp** [comment] 2019-05-30 03:19
This is fixed in Altair 3:
```python
import altair as alt

cars = alt.load_dataset('cars')

alt.Chart(cars, title='Chart title').mark_bar().encode(
    x=alt.X('Horsepower'),
    y=alt.Y('count(*):Q'),
    column=alt.Column('Acceleration', header=alt.Header(title='Acceleration'), bin=alt.Bin(maxbins=3)),
).properties(
    width=200,
    height=200
)
```
![visualization - 2019-05-29T201902 555](https://user-images.githubusercontent.com/781659/58606112-0afeaa80-824f-11e9-9cc2-6a0453b6469a.png)

**Closed** 2019-05-30 03:19 UTC
Labels: vega-lite-related
