### ISSUE TITLE
Altair use in VS Code with Interactive Python Extension broken

### ISSUE THREAD

**Issue by hathawayj** [altair-viz/altair#2285] opened 2020-09-09 00:53 UTC
I know this isn't quite the right spot for this issue.  Today I tried to create an Altair chart in VS Code and it would not display.  The code either runs with no output or returns the following error.

```
Error loading script: Script error for "vega-util", needed by: vega-embed https://requirejs.org/docs/errors.html#scripterror
```

I can still save charts using altair-saver.  Are there any other uses of VS Code with Altair having an issue?

This chart is a good example for one that will not render - https://altair-viz.github.io/gallery/simple_line_chart.html.

Issue posted on StackOverflow - https://stackoverflow.com/questions/63803312/altair-use-in-vs-code-with-interactive-python-extension-broken

**Comment by jakevdp** [comment] 2020-09-09 01:11
Duplicate of #2280; clear your javascript caches and it will work again.

**Closed by jakevdp** 2020-09-09 01:11 UTC

**Comment by hathawayj** [comment] 2020-09-09 01:44
I don't understand how to clear my cache in VS Code.  I am not using jupyter notebooks in a browser.  Sorry for not understanding what you mean by 'clear your javascript caches'.

**Comment by jakevdp** [comment] 2020-09-09 02:04
I don't know how to do this; I would suggest consulting the VSCode docs or help forums.

**Comment by Honghe** [comment] 2024-09-27 03:10
> I don't know how to do this; I would suggest consulting the VSCode docs or help forums.

Just reopen `.jpynb`.
