### ISSUE TITLE
Empty plot when using DataFrame as Chart object

### ISSUE THREAD

**Issue by rpalloni** [altair-viz/altair#765] opened 2018-04-17 20:21 UTC
Chart() seems to get a url to dataframe but not a DataFrame object as described in the guide.
But this is not handy as, while doing analysis, you usually load data on top, go through some stats and calcualtions and than visulize them.
Basically, you cannot use the DataFrame object created with pd.read_csv into Chart().
See example below:

`
stocks = pd.read_csv('C:\\Program Files\\Python\\Python36-32\\lib\\site-packages\\vega_datasets\\data\\stocks.csv')

type(stocks)

stocks.tail()

stocks.groupby(['symbol']).agg({'price': 'mean'})

alt.Chart(data=stocks).mark_line().encode(
    x='date:T',
    y='price:Q',
    color="symbol:N",
    column="symbol:N")
`

![csv_pandas](https://user-images.githubusercontent.com/17080117/38894399-67d70818-428d-11e8-840a-034043b9f7a9.PNG)

**Comment by jakevdp** [comment] 2018-04-17 20:28
In the future, could you copy and paste the actual code rather than inserting a screen shot? It makes it so that I can copy your code when trying to reproduce your bug, rather than having to re-type in manually, and also makes your code indexable by search engines.

**Comment by jakevdp** [comment] 2018-04-17 20:30
As to your question: Altair should be able to work with any dataframe, so lets figure out what's going wrong here.

If you output your chart to a dictionary, what is the result? (i.e. ``chart.to_dict()``) what is the result?

**Comment by jakevdp** [comment] 2018-04-17 20:34
Also, are you able to show other charts? In other words, is this an isolated failure in a frontend where charts generally display correctly, or are you unable to see any charts at all?

**Comment by jakevdp** [comment] 2018-04-17 20:35
Another question: what frontend are you using, and do you know what version of the Vega-Lite library it is running?

**Comment by jakevdp** [comment] 2018-04-17 20:44
For what it's worth, this works fine for me on JupyterLab:
```python
import altair as alt

from vega_datasets import data
import pandas as pd
from urllib.request import urlretrieve
urlretrieve(data.stocks.url, 'stocks.csv')
stocks = pd.read_csv('stocks.csv')

alt.Chart(stocks).mark_line().encode(
    x='date:T',
    y='price:Q',
    color='symbol:N'
)
```
![visualization 2](https://user-images.githubusercontent.com/781659/38895602-52315ea2-4245-11e8-8c41-ceef55ba26ff.png)

**Comment by rpalloni** [comment] 2018-04-18 11:50
to_dict() output is as follows:

`
{'config': {'background': 'white', 'axis': {'titleColor': 'black'}},
 'data': {'url': 'C:\\Program Files\\Python\\Python36-32\\lib\\site-packages\\vega_datasets\\data\\stocks.csv'},
 'mark': 'line',
 'encoding': {'color': {'type': 'nominal', 'field': 'symbol'},
  'column': {'type': 'nominal', 'field': 'symbol'},
  'x': {'type': 'temporal', 'field': 'date'},
  'y': {'type': 'quantitative', 'field': 'price'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v2.3.0.json'}
`

I'm running Alatir 2.3 on Hydrogen 2.4 and if I load data using:

`
from vega_datasets import data
stocks = data.stocks.url
`
it works.

But note that stocks is a url when using data.stocks.url

**Comment by jakevdp** [comment] 2018-04-18 15:41
OK, if that's the output of ``to_dict()`` on your chart, then it looks like you're not passing the dataframe to as chart data, but rather passing a string containing the local CSV file path to the chart. That local filepath is not a valid URL, which is why you're not getting any output.

If you want to pass data using a string referencing a local filepath, you should use a URL starting with ``file://``; e.g. ``alt.Chart(data="file://C:/Program Files/Python/Python36-32/lib/site-packages/vega_datasets/data/stocks.csv")``

But since you said above that you were trying to pass the dataframe itself as data, I suspect that you somewhere mixed up your variable names. Make certain you that what you are passing to the chart is actually what you think it is.

**Comment by jakevdp** [comment] 2018-05-01 19:31
I'm going to close this, since it doesn't look like you have more questions. Feel free to ask if something else comes up!

**Closed by jakevdp** 2018-05-01 19:31 UTC

**Comment by rpalloni** [comment] 2020-03-05 18:34
Hello @jakevdp.
I'm still on this issue [Ubuntu 18.04 / python 3.7 / altair 4.0]
Here the code I c/p from here https://altair-viz.github.io/getting_started/overview.html

But still I'm getting the empty square despite fig.to_dict() returns a dictionary with everything

import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

fig = alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()

fig.to_dict()
fig


![Screenshot from 2020-03-05 19-33-36](https://user-images.githubusercontent.com/17080117/76013513-4766e180-5f18-11ea-90a2-5a16988be27b.png)

**Comment by jakevdp** [comment] 2020-03-05 20:39
I would inquire with the Hydrogen project regarding how rich outputs are displayed. I'm not familiar with that platform, so I don't have any advice.

**Comment by rpalloni** [comment] 2020-03-06 07:27
Ok, thanks anyway.
Apparently it is working ok on Jupyter so i'll ask to Hydrogen folks. Thanks.

![Screenshot from 2020-03-06 08-24-51](https://user-images.githubusercontent.com/17080117/76061631-3b186e00-5f84-11ea-853c-c37184e6f4dd.png)

**Comment by jakevdp** [comment] 2020-03-06 07:43
The ``fig.to_dict()`` line is not doing anything here; it can be removed.
