### ISSUE TITLE
Altair not importing data json saved to disk

### ISSUE THREAD

**Issue by claysmyth** [altair-viz/altair#2948] opened 2023-03-06 20:01 UTC
Hi,

I love Altair, but I believe it not importing data saved to disk in json format. I am attempting to save data to disk because my dataframes are quite large (1M+ rows). However, when I use the recommendations [here](https://altair-viz.github.io/user_guide/data_transformers.html#storing-json-data-in-a-separate-directory) and [here](https://altair-viz.github.io/user_guide/large_datasets.html), my jupyter notebook plots appear as figures with axes but no data (i.e. empty plots). It is correctly writing the data to the json file, which I have verified via inspection of the json in a text editor. Additionally, when running `chart.to_dict()`, the data field correctly points to the right json file.
However, it appears that altair is unable to retrieve the data json that it writes to disk. 

In terminal, there is a `404 GET /path/to/altairdata/data.json` within the jupyter notebook execution info. 

Here is some example code that recreates the issue on my end with Altair version 4.2.2:

```import os
from toolz.curried import pipe
import pandas as pd
import altair as alt


def json_dir(data, data_dir='/path/to/altairdata'):
    os.makedirs(data_dir, exist_ok=True)
    return pipe(data, alt.to_json(filename=data_dir + '/{prefix}-{hash}.{extension}') )


alt.data_transformers.register('json_dir', json_dir)
alt.data_transformers.enable('json_dir')
alt.data_transformers.disable_max_rows()

chart = alt.Chart(pd.DataFrame({'A': [1,2,3], 'B': [5,8,10]})).mark_point().encode(x='A', y='B')
```

EDIT: It appears that my issue is covered here in #1867 , however, none the offered solutions fixed my problem working with jupyter in VS Code. Is there `data_transformers.enable()` method that is known to work for VS Code? It would be very helpful if I could save chart data to disk.

---

Please follow these steps to make it more efficient to solve your issue:

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by binste** [comment] 2023-03-10 19:38
Thank you @claysmyth for reporting this. I can replicate the issue with your code and a fix for me is to remove the first `/` from the path you pass to `data_dir` so it becomes `data_dir='path/to/altairdata'` and therefore stores the json files in a subdirectory of your current working directory instead of a folder starting at root level.

Not fully sure what the issue is but maybe VS Code does not have access to that specific folder. At least I'm getting a 401 Unauthorized response with your example. As Altair constructs the filepath properly I don't think there is anything we can do here. Hopefully switching to a different folder works for you.

**Comment by joelostblom** [comment] 2023-03-15 18:30
Closing as a workaround was provided, please reopen with additional comments if you think there is something altair should change here @claysmyth

**Closed by joelostblom** 2023-03-15 18:30 UTC
Labels: bug
