### ISSUE TITLE
Can not pan the x axis of the second chart if only call interactive() once.

### ISSUE THREAD

**Issue by ruoyu0088** [altair-viz/altair#1514] opened 2019-05-17 05:10 UTC
Here is the code:

```
import altair as alt
from vega_datasets import data
cars = data.cars()

chart = alt.Chart(cars).mark_point().properties(
    width=250,
    height=250
).interactive()

chart.encode(x='Miles_per_Gallon:Q', y='Weight_in_lbs:Q') | chart.encode(x='Acceleration:Q', y='Horsepower:Q')
```

the second chart cannot be panned along x axis with mouse. Call `interactive()` for both charts can solve the problem.

```
import altair as alt
from vega_datasets import data
cars = data.cars()

chart = alt.Chart(cars).mark_point().properties(
    width=250,
    height=250
)

chart.encode(x='Miles_per_Gallon:Q', y='Weight_in_lbs:Q').interactive() | chart.encode(x='Acceleration:Q', y='Horsepower:Q').interactive()
```

**Comment by jakevdp** [comment] 2019-05-17 15:45
This seems to be a regression in Vega-Lite 3 - it works as expected in Vega-Lite 2. Here is a reproduction on the vega editor ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBjWLAZwDoArCgewDtIBfAGnCgAsSmz58AbU4RQEcVAC25ANb5IAB3oBLRgI4SIkAKaNe0VQHN8YzVoAeJyPACeC7fICOGWGuWJ4ygG4O2UAGbK2jjQ8gCyyjjaFAD69lgxAOKwODhMrBpmUDZWtvZOLm4e3r4BQSHyAOrayoZc8DGqMTgARhSsIuLsnVoUwdoknumo6H1Rg-RYAAxTAEy5dg6okKrw2lheKZB+kC2qocsUZFHtLCyd3RKmEpDSWHLLSqvbPVC6+kYmrxYL+cvOrk8xR82zKwQOUAAgiQSP0sAhlOlLllIDkRtZFgVAe4ESCdoFwfIABKTPpKADu6w6ZmRNzGAyGzHR9Im0zmvyWUFW602eB2e0YEMgRxS0VY5wkErAAF0QCwgA)).

**Comment by joelostblom** [comment] 2021-02-23 22:19
This works in the latest version of Altair so closing this issue.

**Closed by joelostblom** 2021-02-23 22:19 UTC
Labels: bug, vega-lite-related
